bugfix: nccl logical stream over max cnt
Oneflow-Inc/oneflow pull request #10118
Opened 2023-04-12 10:03 UTC by chengtbf

修复一个边角 case 下的 bug：

当 构造的 chain 特别多时， nccl logical subgraph 数量超过 8 个，此时不会插入 stream hint，也不会插入 logical chain id，导致后续检查失败。

但此时也不应该插入 nccl logical op，而是转为 slice boxing（因为当多个 nccl logical chain 复用同一个 stream ，有死锁风险）

本 PR 修复了这个问题。并附上测试用例

2023-04-12 10:05 UTC, chengtbf commented on oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
> -      break;  // NOTE(chengcheng): ONLY support kMaxNcclComputeStreamCount insert nccl subgraphs.
这里不应该 break，break 仍会插入 nccl logical op，但是用的是默认的 compute stream，多个 chain 会存在死锁风险。

2023-04-12 10:05 UTC, chengtbf commented on oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
> +    return 0;  // NOTE(chengcheng): ONLY support kMaxNcclComputeStreamCount insert nccl subgraphs.
因此直接改为 return

2023-04-12 10:06 UTC, chengtbf commented on oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
> +  (*nccl_compute_stream_id)++;
这里不能每个 chain 都++，而是符合 nccl insert 的才 ++

2023-04-12 10:06 UTC, chengtbf commented on oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
> +  return nccl_op_confs.size() + subgraph_ordered_nodes.size();
返回值修改，原来是 void，现在包含了 chain 内新增的 nccl op 和 计算 op，计算总 op 数量更加准确

2023-04-12 10:06 UTC, chengtbf commented on python/oneflow/test/graph/test_comb1to2d.py
> +        flow.boxing.nccl.enable_use_compute_stream(True)
开启 nccl use compute stream

2023-04-12 10:12 UTC, strint commented on python/oneflow/test/graph/test_comb1to2d.py
> +    def test_lazy_boxing_2d_all_combination_diff_hierarchy(test_case):
这个名字应该不用改

2023-04-12 10:13 UTC, strint commented on python/oneflow/test/graph/test_comb1to2d.py
> +    def test_lazy_boxing_2d_all_combination_diff_placement(test_case):
test_lazy_boxing_2d_all_combination_diff_placement_with_nccl_logical ?

2023-04-12 10:17 UTC, chengtbf commented on python/oneflow/test/graph/test_comb1to2d.py
> +    def test_lazy_boxing_2d_all_combination_diff_hierarchy(test_case):
好的

2023-04-12 10:17 UTC, chengtbf commented on python/oneflow/test/graph/test_comb1to2d.py
> +    def test_lazy_boxing_2d_all_combination_diff_placement(test_case):
好的

2023-04-12 11:32 UTC, chengtbf commented on python/oneflow/test/graph/test_comb1to2d.py
> +        # flow.boxing.nccl.enable_use_compute_stream(False)
ok

2023-04-12 11:59 UTC, leaves-zwx approved these changes

2023-04-12 13:05 UTC, strint approved these changes

2023-04-14 15:13 UTC, chengtbf commented on python/oneflow/test/graph/test_comb1to2d.py
> +    def test_lazy_boxing_2d_all_combination_diff_placement_with_nccl_logical(test_case):
连续两次必现： Python bus error


- https://github.com/Oneflow-Inc/oneflow/actions/runs/4696805412/jobs/8331550992?pr=10118
- https://github.com/Oneflow-Inc/oneflow/actions/runs/4696805412/jobs/8334774435?pr=10118

```
  File "/opt/conda/lib/python3.7/runpy.py", line 193 in _run_module_as_main
[wg=1][device=0,1,2,3] python/oneflow/test/graph/test_comb1to2d.py ....Fatal Python error: Bus error
[wg=1][device=0,1,2,3] 
[wg=1][device=0,1,2,3] Thread 0x00007f8e4a5fa0c0 (most recent call first):
[wg=1][device=0,1,2,3]   File "/opt/conda/lib/python3.7/site-packages/oneflow/framework/tensor.py", line 404 in _numpy
[wg=1][device=0,1,2,3]   File "/home/ci-user/runners/gpu/_work/oneflow/oneflow/python/oneflow/test/graph/test_comb1to2d.py", line 142 in test_lazy_boxing_2d_all_combination_diff_placement_with_nccl_logical
[wg=1][device=0,1,2,3]   File "/opt/conda/lib/python3.7/unittest/case.py", line 628 in run
[wg=1][device=0,1,2,3]   File "/opt/conda/lib/python3.7/unittest/case.py", line 676 in __call__
[wg=1][device=0,1,2,3]   File "/opt/conda/lib/python3.7/site-packages/_pytest/unittest.py", line 330 in runtest
[wg=1][device=0,1,2,3]   File "/opt/conda/lib/python3.7/site-packages/_pytest/runner.py", line 167 in pytest_runtest_call
[wg=1][device=0,1,2,3]   File "/opt/conda/lib/python3.7/site-packages/pluggy/_callers.py", line 39 in _multicall
```


### 猜测：

虽然我们在单进程内限制了 nccl max stream cnt = 8，但是 CI 里有至少 4 组测试在同时测试，可能会触发上限导致 BUG ？ （其实还不清楚为什么会有此 BUG）

我计划将 kMaxNcclComputeStreamCount 变成可配置项试试，配置成 1

2023-04-15 07:27 UTC, chengtbf commented on python/oneflow/test/graph/test_comb1to2d.py
> +        # test_case.assertTrue(np.allclose(x.numpy(), z.numpy(), 1e-05, 1e-05))
BUG 出现在这里，猜测 z 不是内存连续的，不能直接 .numpy

2023-04-15 07:27 UTC, chengtbf commented on python/oneflow/test/graph/test_comb1to2d.py
> +    def test_lazy_boxing_2d_all_combination_diff_placement_with_nccl_logical(test_case):
https://github.com/Oneflow-Inc/oneflow/pull/10118/files#r1167417473

2023-04-17 07:03 UTC, Yipeng1994 requested changes
test comb 是为了测试middle nodes的功能，打nccl use compute stream了以后就会测广义基础传输的功能了。而广义基础传输的功能在test_gbc系列有。

2023-04-17 07:04 UTC, Yipeng1994 commented on python/oneflow/test/graph/test_comb1to2d.py
> +        # test_case.assertTrue(np.allclose(x.numpy(), z.numpy(), 1e-05, 1e-05))
这个测试以前是没有问题的，如果现在过不了，应该查看现在的code

2023-04-17 07:05 UTC, Yipeng1994 commented on python/oneflow/test/graph/test_comb1to2d.py
> +        flow.boxing.nccl.enable_use_compute_stream(True)
这里不能开启

2023-04-17 07:07 UTC, Yipeng1994 commented on python/oneflow/test/graph/test_comb1to2d.py
> +        # flow.boxing.nccl.enable_use_compute_stream(False)
不能去掉

2023-04-17 07:37 UTC, Yipeng1994 approved these changes
了解到是一个新加的功能，建议移动到一个新的文件。（这个文件是test middle nodes的，打开nccl logical compute stream的话就只会用广义基础传输了）

2023-04-17 08:08 UTC, strint commented on python/oneflow/test/graph/test_comb1to2d.py
> -
@Yipeng1994  测试已经剥离

2023-04-17 08:39 UTC, chengtbf commented on python/oneflow/test/graph/test_nccl_comm_with_nccl_logical_pass.py
> +        y = graph_diff_hierarchy(x)
这里还会出现 bus error，还不确定原因

2023-05-05 07:25 UTC, chengtbf commented on python/oneflow/test/graph/test_nccl_comm_with_nccl_logical_pass.py
> +        flow.boxing.nccl.enable_use_compute_stream(True)
这里还是报错了：

- https://github.com/Oneflow-Inc/oneflow/actions/runs/4839062019/jobs/8623971594?pr=10118

这个报错很奇怪：

```
[wg=2][device=0,1,2,3] >               self._c_nn_graph.compile_plan_for_runtime()
[wg=2][device=0,1,2,3] E               oneflow._oneflow_internal.exception.RuntimeError: Error: Partial SBP in the consumer or not running on CUDA
[wg=2][device=0,1,2,3] 
[wg=2][device=0,1,2,3] /opt/conda/lib/python3.7/site-packages/oneflow/nn/graph/graph.py:1311: RuntimeError
```

Nccl Logical 不支持 to partial

2023-05-05 07:33 UTC, chengtbf commented on python/oneflow/test/graph/test_nccl_comm_with_nccl_logical_pass.py
> +        flow.boxing.nccl.enable_use_compute_stream(True)
这里和 @Yipeng1994  讨论了一下，原因是 CollectiveBoxing 通过 MiddleNodes 支持了 * -> P， 但是 NcclLogical 里的 SendRecv 还没支持这部分。所以当 NcclLogical 开启时，要避免 to global P  @strint

2023-05-05 07:36 UTC, Yipeng1994 commented on python/oneflow/test/graph/test_nccl_comm_with_nccl_logical_pass.py
> +        flow.boxing.nccl.enable_use_compute_stream(True)
嗯嗯，反正正常图里面不会有主动to partial的，可以在单测里面跳过（事实上，广义基础传输研发出来以后都没有人提到说碰到了to partial的报错，这次是第一次）

2023-05-05 11:34 UTC, merged