nn.MaxPool2d support 3D input tensor
Oneflow-Inc/oneflow pull request #10110
Opened 2023-04-11 06:48 UTC by Flowingsun007

需求来源，issue：https://github.com/Oneflow-Inc/oneflow/issues/10106
- nn.MaxPool2d支持输入3D tensor作为input
- test case

2023-04-11 06:52 UTC, BBuf commented on python/oneflow/nn/modules/pooling.py
> +            y = flow._C.max_pool2d(
我看了一下在pytorch里面对于conv和pool系列的module，支持batch rule，也就是batch维度可以折叠。这个我之前已经处理过conv了，可以参考一下ConvBaseFunctor的做法。在python层就不要处理了

2023-04-13 02:04 UTC, ccssu requested changes

2023-04-14 05:01 UTC, Flowingsun007 commented on python/oneflow/nn/modules/pooling.py
> +            y = flow._C.max_pool2d(
好的，已修改

2023-04-14 05:02 UTC, Flowingsun007 commented on python/oneflow/test/modules/test_maxpool.py
> +    def test_maxpool2d_with_3d_input_tensor(test_case):
已修改

2023-04-14 05:40 UTC, ccssu approved these changes

2023-04-17 04:12 UTC, BBuf approved these changes
LGTM

2023-04-17 11:16 UTC, merged