[bugfix]fix bug of oneflow backend be stuck
Oneflow-Inc/oneflow pull request #10435
Opened 2024-02-09 05:28 UTC by crazy-JiangDongHua

修复了 [torch compile 对接 oneflow backend，跑 resnet50 会卡死](https://github.com/Oneflow-Inc/OneTeam/issues/2193)问题

2024-02-09 05:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Oneflow-Inc/oneflow?pullRequest=10435) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Oneflow-Inc/oneflow?pullRequest=10435) before we can accept your contribution.<br/><hr/>**JiangDongHua** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Oneflow-Inc/oneflow?pullRequest=10435) it.</sub>

2024-02-18 01:29 UTC, levi131 commented on python/oneflow/framework/infer_compiler/__init__.py
> +import torch
这里是不是不需要import torch

2024-02-18 02:37 UTC, crazy-JiangDongHua commented on python/oneflow/framework/infer_compiler/__init__.py
> +import torch
oneflow_backend 函数里面用到了 torch.Tensor （39，44 行），如果不 import torch 会报错

2024-02-20 05:49 UTC, levi131 commented on python/oneflow/framework/infer_compiler/__init__.py
> +import torch
@linzs148 应该有一个 oneflow 代码中需要用到 torch API，但是不直接 import torch 的解决方案，可以讨论一下

2024-02-22 03:06 UTC, mosout commented on python/oneflow/framework/infer_compiler/__init__.py
> +try:
这个try应该放到`with_oneflow_backend.py`里？因为torch是在 `args_tree = ArgsTree((args, kwargs), False, tensor_type=torch.Tensor)` 这时用的，这个代码已经被挪到`with_oneflow_backend.py`了

2024-02-22 03:16 UTC, crazy-JiangDongHua commented on python/oneflow/framework/infer_compiler/__init__.py
> +try:
`infer_compiler` 模块下其他模块类似 `with_fx_graph.py` ，`with_oneflow_compile.py` 等都有 `import torch` ，所有放在 `__init__.py` 下面尝试导入一次，如果失败就给出提示信息。

2024-02-22 03:17 UTC, mosout commented on python/oneflow/framework/infer_compiler/__init__.py
> +try:
好的

2024-02-22 06:07 UTC, mosout approved these changes

2024-02-29 04:25 UTC, mosout requested changes

2024-02-29 04:25 UTC, mosout commented on python/oneflow/framework/infer_compiler/with_oneflow_backend.py
> +    return wrapped_forward
空行

2024-02-29 05:39 UTC, crazy-JiangDongHua commented on python/oneflow/framework/infer_compiler/with_oneflow_backend.py
> +    return wrapped_forward
用 of_format 改好格式了

2024-02-29 07:48 UTC, merged