Add polyval op
Oneflow-Inc/oneflow pull request #3541
Opened 2020-09-07 09:55 UTC by hengzi

2020-11-12 12:30 UTC, MARD1NO requested changes
参照 [#3602](https://github.com/Oneflow-Inc/oneflow/pull/3602/files#diff-255f0859691142d79e317af431ceba01e09254ef1dbac6f02ac2725b6c54022bR276-R313) 对测试脚本的case增加 单机单卡和单机2卡的测试，注意对于GPU的test_case需要加上
```
@unittest.skipIf(os.getenv("ONEFLOW_TEST_CPU_ONLY"), "only test cpu cases")
```
修饰符

2020-11-12 12:30 UTC, MARD1NO commented on oneflow/python/ops/math_ops.py
> +        import oneflow as flow
code-block下要换行，不然API文档渲染会有格式问题

2020-11-12 12:30 UTC, MARD1NO commented on oneflow/python/test/ops/test_polyval.py
> +    @flow.global_function(function_config=func_config)
globalfunction设置type为"train"模式，构造一个variable。 

具体可参照 [#3602](https://github.com/Oneflow-Inc/oneflow/pull/3602/files#diff-255f0859691142d79e317af431ceba01e09254ef1dbac6f02ac2725b6c54022bR192-R205) 这部分修改

2020-11-12 12:30 UTC, MARD1NO commented on oneflow/python/ops/math_ops.py
> +    if not isinstance(coeffs, list):
这里也允许 Tuple 传入吧，很多地方我们tuple和list都可以传入，最好保持一致

2020-11-12 12:30 UTC, MARD1NO commented on oneflow/python/test/ops/test_polyval.py
> +
这里只验证了输出一致，而没有验证梯度。

虽然该算子是由python已有算子拼接而来，理论上是不存在反向传播不一致的问题。

但如果后续重构成C++，迟早是会要做梯度验证的。可以用tf构造，也可以用numpy构造

可参考 oneflow/python/ops/test/test_smooth_l1_loss.py 该文件，使用flow.watch_diff来去验证梯度

2020-11-12 12:30 UTC, MARD1NO commented on oneflow/python/ops/math_ops.py
> +    coeffs: Sequence, x: remote_blob_util.BlobDef, name: Optional[str] = None
这里我觉得把 Sequence换成 `Optional[List, Tuple]` 好点。Sequence包括了range

2020-11-12 12:30 UTC, MARD1NO commented on oneflow/python/ops/math_ops.py
> +        remote_blob_util.BlobDef: A Blob, has the same type of x.
-> has the same data type of x

2020-11-16 08:50 UTC, hengzi commented on oneflow/python/ops/math_ops.py
> +    if not isinstance(coeffs, list):
没看到 `Optional[List, Tuple]` 这样的用法，而且 Optional 放这里意思也不对吧

2020-11-16 09:02 UTC, MARD1NO commented on oneflow/python/ops/math_ops.py
> +    if not isinstance(coeffs, list):
你可以这样 `if not isinstance(x, (list, tuple))`

2020-11-16 09:08 UTC, hengzi commented on oneflow/python/ops/math_ops.py
> +    coeffs: Sequence, x: remote_blob_util.BlobDef, name: Optional[str] = None
刚写回复错了，应该在这里。
``` python
def polyval(
    coeffs: Optional[List, Tuple], x: remote_blob_util.BlobDef, name: Optional[str] = None)
```
这里要改成这样吗？

2020-11-16 09:17 UTC, MARD1NO commented on oneflow/python/ops/math_ops.py
> +    coeffs: Sequence, x: remote_blob_util.BlobDef, name: Optional[str] = None
是的

2020-11-16 09:26 UTC, hengzi commented on oneflow/python/ops/math_ops.py
> +    coeffs: Sequence, x: remote_blob_util.BlobDef, name: Optional[str] = None
应该是Union吧

2020-11-24 07:35 UTC, MARD1NO approved these changes

2020-11-24 09:28 UTC, MARD1NO approved these changes

2020-11-24 20:02 UTC, merged