Dev integrate cfg
Oneflow-Inc/oneflow pull request #3597
Opened 2020-09-23 13:03 UTC by clackhan

2020-09-24 14:46 UTC, jackalcooper requested changes

2020-09-24 14:46 UTC, jackalcooper commented on cmake/cfg.cmake
> +set(PYBIND_REGISTRY_CC "${PROJECT_SOURCE_DIR}/tools/cfg/pybind_module_registry.cpp")
这个要封装成python脚本而不是写死

2020-09-24 14:46 UTC, jackalcooper commented on cmake/cfg.cmake
> +  list(APPEND ALL_CONVERT_PROTO oneflow/core/common/data_type.proto)
这些append 可以写在一起吧

2020-09-24 14:46 UTC, jackalcooper commented on cmake/cfg.cmake
> +  set(${SRCS})
这两个set是干嘛的

2020-09-24 14:46 UTC, jackalcooper commented on cmake/cfg.cmake
> +function(RELATIVE_PYBIND11_GENERATE_CPP SRCS HDRS PYBIND_SRCS ROOT_DIR)
这个函数名字改改，这个relative什么意思看不出来

2020-09-24 14:46 UTC, jackalcooper commented on cmake/oneflow.cmake
> +# PYBIND11_SRCS must be put before oneflow/api/python/init.cpp, and PYBIND_REGISTRY_CC must be the last arg
记一下不然会编译错误

2020-09-27 03:37 UTC, clackhan commented on cmake/cfg.cmake
> +set(PYBIND_REGISTRY_CC "${PROJECT_SOURCE_DIR}/tools/cfg/pybind_module_registry.cpp")
${PROJECT_SOURCE_DIR}/tools/cfg/pybind_module_registry.cpp是cfg模块下的源代码，不是生成的，此处只是取了一个别名PYBIND_REGISTRY_CC 而已，如果把set(...)删掉，将oneflow.cmake
pybind11_add_module(oneflow_internal ${PYBIND11_SRCS} ${PROJECT_SOURCE_DIR}/oneflow/api/python/init.cpp ${of_pybind_obj_cc} ${SWIG_SRCS} ${SWIG_HDRS} ${of_main_cc} ${PYBIND_REGISTRY_CC})
改为：
pybind11_add_module(oneflow_internal ${PYBIND11_SRCS} ${PROJECT_SOURCE_DIR}/oneflow/api/python/init.cpp ${of_pybind_obj_cc} ${SWIG_SRCS} ${SWIG_HDRS} ${of_main_cc} ${PROJECT_SOURCE_DIR}/tools/cfg/pybind_module_registry.cpp)
是等价的。
不太明白你说的封装成脚本是什么意思。

2020-09-27 03:37 UTC, clackhan commented on cmake/cfg.cmake
> +  list(APPEND ALL_CONVERT_PROTO oneflow/core/common/data_type.proto)
已更改

2020-09-27 03:37 UTC, clackhan commented on cmake/cfg.cmake
> +  set(${SRCS})
这个是参考：
proto2cpp.cmake中的
https://github.com/Oneflow-Inc/oneflow/blob/2e3ce2e6b633541dfe78017c87fa50b55c568434/cmake/proto2cpp.cmake#L7
以及swig.cmake中的
https://github.com/Oneflow-Inc/oneflow/blob/2e3ce2e6b633541dfe78017c87fa50b55c568434/cmake/swig.cmake#L7
做了一把实验，这两个set()写不写都一样，那是不是proto2cpp.cmake和swig.cmake中的set()也可以删除了？

2020-09-27 03:37 UTC, clackhan commented on cmake/cfg.cmake
> +function(RELATIVE_PYBIND11_GENERATE_CPP SRCS HDRS PYBIND_SRCS ROOT_DIR)
已更改

2020-09-27 03:37 UTC, clackhan commented on cmake/oneflow.cmake
> +# PYBIND11_SRCS must be put before oneflow/api/python/init.cpp, and PYBIND_REGISTRY_CC must be the last arg
已经做出说明

2020-09-27 03:39 UTC, jackalcooper commented
请测试两个东西：
1. 修改 cfg 的 proto 定义，会不会导致整个 oneflow 重新编译
2. 关闭 third party，能否正常编译

2020-09-27 03:40 UTC, jackalcooper commented
> 请测试两个东西：
> 1. 修改 cfg 的 proto 定义，会不会导致整个 oneflow 重新编译
> 2. 关闭 third party，能否正常编译

2 应该没问题，ci里面会测试到

2020-09-27 03:52 UTC, jackalcooper commented on cmake/cfg.cmake
> +set(PYBIND_REGISTRY_CC "${PROJECT_SOURCE_DIR}/tools/cfg/pybind_module_registry.cpp")
`python3 -m oneflow_cfg get_cpp_path`
cmake 运行类似这样的命令得到这个文件的路径，而不需要在cmake里面写死，因为以后这个文件可能变化

2020-09-27 03:54 UTC, jackalcooper commented on cmake/cfg.cmake
> +  set(${SRCS})
那就都去掉吧

2020-09-27 04:22 UTC, clackhan commented
> > 请测试两个东西：
> > 
> > 1. 修改 cfg 的 proto 定义，会不会导致整个 oneflow 重新编译
> > 2. 关闭 third party，能否正常编译
> 
> 2 应该没问题，ci里面会测试到

1是指的增加或减少下面ALL_CFG_CONVERT_PROTO里的proto文件配置吧
```cmake
list(APPEND ALL_CFG_CONVERT_PROTO
      oneflow/core/common/data_type.proto
      oneflow/core/common/device_type.proto
      oneflow/core/job/sbp_parallel.proto
      oneflow/core/job/mirrored_parallel.proto
      oneflow/core/job/scope.proto
      oneflow/core/record/record.proto
      oneflow/core/record/image.proto
  )
```
做了两把实验，增加或减少proto文件配置都不会导致整个 oneflow 重新编译

2020-09-27 04:55 UTC, jackalcooper commented
> > > 请测试两个东西：
> > > 
> > > 1. 修改 cfg 的 proto 定义，会不会导致整个 oneflow 重新编译
> > > 2. 关闭 third party，能否正常编译
> > 
> > 
> > 2 应该没问题，ci里面会测试到
> 
> 1是指的增加或减少下面ALL_CFG_CONVERT_PROTO里的proto文件配置吧
> 
> ```cmake
> list(APPEND ALL_CFG_CONVERT_PROTO
>       oneflow/core/common/data_type.proto
>       oneflow/core/common/device_type.proto
>       oneflow/core/job/sbp_parallel.proto
>       oneflow/core/job/mirrored_parallel.proto
>       oneflow/core/job/scope.proto
>       oneflow/core/record/record.proto
>       oneflow/core/record/image.proto
>   )
> ```
> 
> 做了两把实验，增加或减少proto文件配置都不会导致整个 oneflow 重新编译

我想的是修改。减少的话，被删除的 proto 原先产生的文件有消失吗。

2020-09-27 07:19 UTC, clackhan commented
> 减少的话，被删除的 proto 原先产生的文件有消失吗。

减少的话，被删除的 proto 原先产生的文件不会消失，只是编译的时候不会编译原先产生的源文件而已，这个proto2cpp那边好像也是一样的情况吧。

2020-09-27 07:20 UTC, clackhan commented
> > > > 请测试两个东西：
> > > > 
> > > > 1. 修改 cfg 的 proto 定义，会不会导致整个 oneflow 重新编译
> > > > 2. 关闭 third party，能否正常编译
> > > 
> > > 
> > > 2 应该没问题，ci里面会测试到
> > 
> > 
> > 1是指的增加或减少下面ALL_CFG_CONVERT_PROTO里的proto文件配置吧
> > ```cmake
> > list(APPEND ALL_CFG_CONVERT_PROTO
> >       oneflow/core/common/data_type.proto
> >       oneflow/core/common/device_type.proto
> >       oneflow/core/job/sbp_parallel.proto
> >       oneflow/core/job/mirrored_parallel.proto
> >       oneflow/core/job/scope.proto
> >       oneflow/core/record/record.proto
> >       oneflow/core/record/image.proto
> >   )
> > ```
> > 
> > 
> > 做了两把实验，增加或减少proto文件配置都不会导致整个 oneflow 重新编译
> 
> 我想的是修改。减少的话，被删除的 proto 原先产生的文件有消失吗。

减少的话，被删除的 proto 原先产生的文件不会消失，只是编译的时候不会编译原先产生的源文件而已，这个proto2cpp那边好像也是一样的情况吧。

2020-10-07 04:20 UTC, lixinqi approved these changes

2020-10-07 06:33 UTC, merged