add cpu version oneflow_range
Oneflow-Inc/oneflow pull request #3725
Opened 2020-10-27 04:09 UTC by MARD1NO

CPU版本的 oneflow.range

2020-10-29 01:46 UTC, doombeaker commented on oneflow/user/kernels/range_kernel.cpp
> +}  // namespace oneflow
文件末尾没有换行，下同

2020-10-29 01:47 UTC, doombeaker commented on oneflow/python/test/ops/test_range.py
> +        arg_dict["device_type"] = ["cpu"]
为什么只有 CPU 的测试

2020-10-29 01:54 UTC, MARD1NO commented on oneflow/python/test/ops/test_range.py
> +        arg_dict["device_type"] = ["cpu"]
。。忘记这里加上了，只在assert那里改了，我等等改个

2020-10-29 01:55 UTC, doombeaker commented on oneflow/user/kernels/range_kernel.cu
> +      (user_op::HobDeviceTag() == "gpu")                                              \
为什么可以直接用 "gpu" 字符串……

2020-10-29 01:58 UTC, doombeaker commented on oneflow/user/kernels/range_kernel.cpp
> +REGISTER_RANGE_KERNEL(DeviceType::kCPU, int64_t)
我看 paddle，一共支持  'float32', 'float64', 'int32', 'int64'  四种类型。你这里只有一种

2020-10-29 02:00 UTC, Ldpe2G commented on oneflow/user/kernels/range_kernel.cu
> +      (user_op::HobDeviceTag() == "gpu")                                              \
这个可以看 [HobStringContextGetter](https://github.com/Oneflow-Inc/oneflow/blob/968dc8e6670c8a3856482f119b5f45c3d127d56a/oneflow/core/framework/user_op_hob.h#L57) 这个类提供了一个 接受 const char * 的构造函数，所以这里的 "gpu" 会隐式转换为 HobStringContextGetter

2020-10-29 02:00 UTC, doombeaker commented on oneflow/user/ops/range_op.cpp
> +    .Attr<int64_t>("start")
同之前提到的，支持的类型写死为 int64_t 是不准确的。其它框架支持多种数据格式

2020-10-29 02:04 UTC, doombeaker commented on oneflow/user/ops/range_op.cpp
> +      *out_shape = Shape(dim_vec);
感觉可以省去这个临时的dim_vec变量，*out_shape = Shape({ctx->Attr<int64_t>("range_shape")});
现在的写法，多余了一次DimVector 构造，一次push_back调用

2020-10-29 02:07 UTC, doombeaker commented on oneflow/user/kernels/range_kernel.cu
> +class RangeGpuKernel final : public user_op::OpKernel {
可以将CPU和GPU的Kernel，利用模板参数+仿函数合并。
具体可以参考 oneflow/oneflow/user/kernels/where_kernel.cpp 或其它文件

2020-10-29 02:09 UTC, doombeaker approved these changes
需要增加更多类型的支持，需要合并 CPU 和 GPU 的Kernel类

2020-10-29 02:11 UTC, doombeaker requested changes
需要增加更多类型支持，需要合并CPU和GPU的Kernel

2020-10-29 02:22 UTC, doombeaker commented on oneflow/user/kernels/range_kernel.cu
> +      (user_op::HobDeviceTag() == "gpu")                                              \
哦哦，那语法上是ok的。不过还是请zekang换成枚举值，省去这次隐式转换吧。

2020-10-29 03:34 UTC, MARD1NO commented on oneflow/user/ops/range_op.cpp
> +    .Attr<int64_t>("start")
这个之前和文骁讨论过
start limit delta 都要求为整数

后续如果有 convert_to_variable 类似的API出现，会考虑以tensorflow的形式，做一个类型继承，选择最合适的类型

2020-10-29 03:44 UTC, doombeaker commented on oneflow/user/ops/range_op.cpp
> +    .Attr<int64_t>("start")
整数也不止 int64_t 一种，是确定了只做整数，还是只做 int64_t

2020-10-29 08:28 UTC, doombeaker commented on oneflow/user/kernels/range_kernel.cpp
> +  REGISTER_RANGE_KERNEL(device, float)
为什么做float的同事，不做double呢？

2020-10-29 08:41 UTC, Flowingsun007 commented on oneflow/user/kernels/range_kernel.cpp
> +  REGISTER_RANGE_KERNEL(device, int32_t)           \
int8_t、uint8_t、double是否需要？注册CUDA时还需要float16吧？

2020-10-29 09:17 UTC, doombeaker commented on oneflow/user/kernels/range_kernel_util.cu
> +  CUDA_1D_KERNEL_LOOP(i, range_shape) { out[i] = start + i * delta; }
OneFlow里有 XPU_1D_KERNEL_LOOP 宏，可以同时满足 CPU和GPU的循环。
可以多写一个函数，内部使用XPU_1D_KERNEL_LOOP宏，然后KERENEL调用那个函数，这样就把CPU和GPU的代码也给合并了。

2020-10-29 09:23 UTC, doombeaker commented on oneflow/python/ops/math_ops.py
> +    _range_shape = div_ceil((limit - start), delta)
是的，感觉这个attr可以去掉，在C++种完成。好处是：1. 少设置一个没必要的attr， 2. C++端计算更快（这个我不确认是否是一个充分理由）

2020-10-29 09:28 UTC, doombeaker requested changes
加入 float16、double 的支持。合并CPU和GPU的逻辑。去掉不必要的 _range_shape 属性

2020-10-29 10:04 UTC, MARD1NO commented on oneflow/user/kernels/range_kernel.cpp
> +  REGISTER_RANGE_KERNEL(device, int32_t)           \
float16后续再补充

2020-11-06 17:16 UTC, doombeaker commented on oneflow/user/kernels/range_kernel.cpp
> +    RangeFunctor<device_type, T>().Range(ctx->device_ctx(), start, delta, range_shape, output);
这里现在很不好看，但是是之前你想偷懒留下的坑。
一开始就建议你用仿函数（重载 operator()）。结果不用，然后又想美观一点，就偷偷用了个静态成员(`RangeFunctor::Range`)。
然后留下了模板特例化的坑……

请参照其它OP，和这个commit里模板特例化为解决链接错误的改动。将相关内容修正。

2020-11-09 04:02 UTC, doombeaker commented on oneflow/user/kernels/range_kernel.cpp
> +    const int64_t range_shape =
这个变量名字改成 range_elem_cnt 一类的是否更贴切

2020-11-09 04:02 UTC, doombeaker commented on oneflow/user/kernels/range_kernel_util.cu
> +  // Use Loop to set the value
信息量不大的注释可以去掉

2020-11-09 04:03 UTC, doombeaker commented on oneflow/user/kernels/range_kernel_util.cu
> +    // Run cuda range forward kernel
同上，开发过程中给自己看作为提醒笔记的注释可以去掉。其它的地方请自己检查下。

2020-11-09 04:08 UTC, doombeaker commented on oneflow/user/kernels/range_kernel_util.cpp
> +  void operator()(DeviceCtx* ctx, const int start, const int delta, const int range_shape, T* out) {
这里的 start, delta, range_shape 在 op 属性里设置的是 int64_t，但是此处都使用的是int。在数据大小超过32位的情况下，会造成截断出错。需要一致

2020-11-09 04:11 UTC, doombeaker commented on oneflow/user/ops/range_op.cpp
> +    .SetGetSbpFn([](user_op::SbpContext* ctx) -> Maybe<void> {
待补全 SBP

2020-11-19 06:27 UTC, doombeaker approved these changes

2020-11-19 06:27 UTC, merged