Reflection pad2d op
Oneflow-Inc/oneflow pull request #3777
Opened 2020-11-06 13:15 UTC by Flowingsun007

2020-11-09 01:18 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +int64_t dim_factorial(int64_t idx, const ShapeView  shape){
https://github.com/Oneflow-Inc/oneflow/blob/d0bdbd5d28b8690832cc11986c0523c3478f5f3a/oneflow/core/common/shape.cpp#L109

ShapeView 类已经提供了 Count 函数来做类似的功能，

2020-11-09 01:26 UTC, Ldpe2G commented on oneflow/user/ops/reflection_pad2d.cpp
> +REGISTER_USER_OP_GRAD("reflection_pad2d_grad")
reflection_pad2d_grad 这个算子 是 rereflection_pad2d 的反向实现，对这个算子本身就不需要在注册梯度实现了？

2020-11-09 01:36 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +    for(int64_t i=0; i<4; ++i){
这里改成 shape.NumAxes 好些，如果要限制 维度不能超过4，可以放到 op 注册 infer shape 那里判断

2020-11-09 01:37 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +  while(i >=0){
```
while(i >= 0) 
```
编码风格

2020-11-09 01:39 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +    int64_t num=1;
```
num = 1
```
统一编码风格，操作符两边加空格，下面有很多地方没加

2020-11-09 02:23 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +    int y_vector_count = int(y_shape.At(0)* y_shape.At(1) * y_shape.At(2)* y_shape.At(3));
https://github.com/Oneflow-Inc/oneflow/blob/d0bdbd5d28b8690832cc11986c0523c3478f5f3a/oneflow/core/common/shape_view.h#L39

shape_view 的  elem_cnt 函数已经实现了计算元素个数

2020-11-09 02:31 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +std::vector<int64_t>  index_to_coordinate(const int64_t idx, const std::vector<int64_t> shape){
```C++
void index_to_coordinate(std::vector<int64_t>& coordinate, const int64_t idx, const std::vector<int64_t> shape)
```

建议把 std::vector<int64_t>  coordinate(shape.size());放在函数外面，然后引用传参，而不是return 返回可以少一次拷贝操作。

2020-11-09 02:53 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +    for(int i=0;i< y_vector_count; i++){
这里padding的实现我觉得有点复杂了，我理解你的意思是对对角线上的元素作额外处理是吧。
但是其实可以不需要的，你可以参考下面python的实现，这样会容易理解一些，先算左右的padding，再算上下的padding就行了，对角线不需要特殊处理：

```python
import tensorflow as tf
import numpy as np

# 首先我们创建一个常量 Tensor 表示 pad op 的输入
t = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 接着再创建另一个常量 Tensor 表示 padding 的大小
paddings = tf.constant([[1, 1], [2, 2]]) # 表示上下各 pad 1 左右各 pad 2

# 把 tensorflow 的张量转换为 numpy array
input_nd = t.numpy()

# 新建易读变量保存 paddings 张量内的值
pad_top = paddings[0][0]
pad_bottom = paddings[0][1]
pad_left = paddings[1][0]
pad_right = paddings[1][1]

# 新建一个保存 "REFLECT" pad 的计算结果
numpy_reflect = np.zeros((t.shape[0] + pad_top + pad_bottom, t.shape[1] + pad_left + pad_right), np.int32)

# 填充结果中间的部分
numpy_reflect[pad_top : numpy_reflect.shape[0] - pad_bottom, pad_left : numpy_reflect.shape[1] - pad_right] = input_nd

# 先计算左右 pad 的结果
for h in range(pad_top, numpy_reflect.shape[0] - pad_bottom):
    # 计算左边 pad
    for w in range(pad_left):
        numpy_reflect[h, w] = numpy_reflect[h, pad_left * 2 - w]
    # 计算右边 pad
    for w in range(numpy_reflect.shape[1] - pad_right, numpy_reflect.shape[1]):
        numpy_reflect[h, w] = numpy_reflect[h, 2 * (numpy_reflect.shape[1] - pad_right - 1) - w]

# 计算顶部 pad 的结果
for h in range(pad_top):
    numpy_reflect[h, :] = numpy_reflect[pad_top * 2 - h, :]

# 计算底部 pad 的结果
for h in range(numpy_reflect.shape[0] - pad_bottom, numpy_reflect.shape[0]):
    numpy_reflect[h, :] = numpy_reflect[2 * (numpy_reflect.shape[0] - pad_bottom - 1) - h, :]
```

2020-11-09 03:03 UTC, doombeaker commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +    for(int64_t i=0; i<4; ++i){
oneflow 框架提供了 NdIndexOffsetHelper，它的静态使用方法比较复杂。
可以先参考维度动态的方式。
https://github.com/Oneflow-Inc/oneflow/blob/1a66fa67e784ffbdc2bd99a3688c4d9dd7087a0b/oneflow/user/kernels/dim_gather_kernel_util.h#L34

2020-11-09 03:03 UTC, doombeaker commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +    for(int64_t i=0; i<4; ++i){
oneflow 框架提供了 NdIndexOffsetHelper，它的静态使用方法比较复杂。
可以先参考维度动态的方式。
https://github.com/Oneflow-Inc/oneflow/blob/1a66fa67e784ffbdc2bd99a3688c4d9dd7087a0b/oneflow/user/kernels/dim_gather_kernel_util.h#L34

2020-11-09 10:36 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +int64_t dim_factorial(int64_t idx, const ShapeView  shape){
好的，已换成Shape::Count()

2020-11-09 10:37 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +    for(int64_t i=0; i<4; ++i){
> 这里改成 shape.NumAxes 好些，如果要限制 维度不能超过4，可以放到 op 注册 infer shape 那里判断

ok,已换成shape.NumAxes()

2020-11-09 13:02 UTC, Flowingsun007 commented on oneflow/user/ops/reflection_pad2d.cpp
> +REGISTER_USER_OP_GRAD("reflection_pad2d_grad")
已去掉

2020-11-09 13:02 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +std::vector<int64_t>  index_to_coordinate(const int64_t idx, const std::vector<int64_t> shape){
已修改

2020-11-11 14:21 UTC, doombeaker commented on oneflow/python/ops/pad.py
> +          Same as :https://pytorch.org/docs/master/generated/torch.nn.ReflectionPad2d.html?highlight=reflection#torch.nn.ReflectionPad2d
这种引用外部框架的文档之前有，现在已经基本全部去掉了。可以参考OneFlow中其它的 API docstring。

2020-11-11 14:22 UTC, doombeaker commented on oneflow/python/ops/pad.py
> +
缺少 example，可以参考OneFlow 其它的 API docstring。

2020-11-11 14:22 UTC, doombeaker commented on oneflow/python/ops/pad.py
> +        )
行末没有换行

2020-11-11 14:27 UTC, Flowingsun007 commented on oneflow/python/ops/pad.py
> +
好的，我加一下代码示例

2020-11-11 14:27 UTC, doombeaker commented on oneflow/python/test/ops/test_reflection_pad2d.py
> +
多余的空行

2020-11-11 14:29 UTC, doombeaker commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +int64_t coordinate_to_index(const std::vector<int64_t> coordinate,  const ShapeView shape, const int64_t size_of_data_type){
OneFlow 自带了 NdIndexOffsetHelper，应该优先使用
（已经评论说过一次了）

2020-11-11 14:30 UTC, doombeaker commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +/**
不必要的接口注释

2020-11-11 14:31 UTC, doombeaker commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +        //printf("i:%d >>>>>>coord_y:  [%ld, %ld, %ld, %ld];  coord_x: [%ld, %ld, %ld, %ld]\n", i, coord_y[0], coord_y[1], coord_y[2], coord_y[3], coord_y[0], coord_y[1], x_h, x_w);
不必要的注释

2020-11-11 14:59 UTC, doombeaker commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +      const user_op::Tensor* x = ctx->Tensor4ArgNameAndIndex("x", 0);
函数太长

2020-11-11 15:01 UTC, doombeaker commented on oneflow/user/ops/reflection_pad2d_op.cpp
> +        int64_t h_x, w_x;
声明一行一个。（这种习惯是因为多个同时声明容易可能会出现 `int* v1, v2` 这样的不容易理解的地方。

2020-11-12 11:38 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +int64_t coordinate_to_index(const std::vector<int64_t> coordinate,  const ShapeView shape, const int64_t size_of_data_type){
已将原方法改为用NdIndexOffsetHelper实现

2020-11-14 04:38 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +    for(int i=0;i< y_vector_count; i++){
用numpy的方式看起来确实直观不少，不过c++代码里貌似实现起来没那么简单。如果用这种方式在c++里实现，左右上下4个部分各需要一个4层的for循环，看起来没有numpy里这个简单明了？

2020-11-17 10:28 UTC, doombeaker commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +      const user_op::Tensor* x = ctx->Tensor4ArgNameAndIndex("x", 0);
可以参考 pytorch 的实现修改：
https://github.com/pytorch/pytorch/blob/49f0e5dfeb64a928c6a2368dd5f86573b07d20fb/aten/src/ATen/native/ReflectionPad.cpp#L297

2020-11-18 05:29 UTC, doombeaker commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +void TraverseDiagonalElements(const int64_t  w_idx, NdIndexOffsetHelper<int64_t, 4> &index_helper, const std::vector<int64_t> &index_vector,
DeviceType device_type是模板参数，不可以像这样作为普通参数传递。
需要和你的kernel类似：
```
template<DeviceType device_type, typename T>
void TraverseDiagonalElements ...
```

2020-11-18 05:31 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +void TraverseDiagonalElements(const int64_t  w_idx, NdIndexOffsetHelper<int64_t, 4> &index_helper, const std::vector<int64_t> &index_vector,
哦哦好的

2020-11-18 05:31 UTC, doombeaker commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +    TraverseDiagonalElements<T>(w_idx, index_helper, index_vector, x, y, ctx, device_type);
TraverseDiagonalElements 增加模板参数后，这里的调用也要变化
```
TraverseDiagonalElements<device_type, T> ...
```

2020-11-18 05:32 UTC, doombeaker commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +void TraverseDiagonalElements(const int64_t  w_idx, NdIndexOffsetHelper<int64_t, 4> &index_helper, const std::vector<int64_t> &index_vector,
另外，虽然语法上没错，但这里的模板参数不必要用 `T_IN` 吧？可以和kernel的一致用 `T`。

2020-11-18 06:15 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +      const user_op::Tensor* x = ctx->Tensor4ArgNameAndIndex("x", 0);
> 函数太长

已精简（抽取成了方法）

2020-11-18 06:32 UTC, liujuncheng requested changes

2020-11-18 06:32 UTC, liujuncheng commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +          Memcpy<device_type>(ctx->device_ctx(), y->mut_dptr<T>() + i,
这是在循环里面调用Memcpy么？如果是CPU直接赋值就可以了，如果是GPU这个性能会非常差吧

2020-11-19 08:43 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +    for(int i=0;i< y_vector_count; i++){
或者可以参考一下 pytorch 的实现，我看他也没有对对角线分开考虑，而是对输出坐标的 x 和 y 分别采用相同的策略计算到输入坐标的映射，实现挺间接的：
https://github.com/pytorch/pytorch/blob/cf8a9b50cacb1702f5855859c657a5358976437b/aten%2Fsrc%2FATen%2Fnative%2FReflectionPad.cpp#L235

2020-11-19 12:49 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +    FillBodyElements<device_type, T>(ndims, dy, dx, sizeof_dtype, ctx, true);
你这里求导好像没考虑padding部分的梯度，需要把输出梯度padding的部分累加到输入梯度对应位置上，可以看下 pytroch 的实现

https://github.com/pytorch/pytorch/blob/cf8a9b50cacb1702f5855859c657a5358976437b/aten%2Fsrc%2FATen%2Fnative%2FReflectionPad.cpp#L370

2020-12-14 01:18 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +    for(int i=0;i< y_vector_count; i++){
已经把实现逻辑和pytorch对齐

2020-12-14 01:19 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +          Memcpy<device_type>(ctx->device_ctx(), y->mut_dptr<T>() + i,
已去掉Memcpy

2020-12-14 01:19 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel.cpp
> +    FillBodyElements<device_type, T>(ndims, dy, dx, sizeof_dtype, ctx, true);
已修改

2020-12-16 14:51 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel_util.cu
> +    RUN_CUDA_KERNEL((DoCUDAReflectionPad2dGrad<T>), ctx, BlocksNum4ThreadsNum(elem_cnt),
这个宏 [RUN_CUDA_KERNEL](https://github.com/Oneflow-Inc/oneflow/blob/ed70c73fb94ce835ab668774640398567043a39a/oneflow%2Fcore%2Fdevice%2Fcuda_util.h#L124)，第三个参数表示抛的线程数，不是 block 的数量
```
#define RUN_CUDA_KERNEL(func, device_ctx_ptr, thread_num, ...)           \
  func<<<SMBlocksNum4ThreadsNum(thread_num), kCudaThreadsNumPerBlock, 0, \
         (device_ctx_ptr)->cuda_stream()>>>(__VA_ARGS__)
```

2020-12-16 14:57 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel_util.h
> +  XPU_1D_KERNEL_LOOP(n, n_batch){
这里的实现相当于每个线程处理一个batch的数据，虽然是没错，但是相当于只有 n_batch 个线程在工作，其他线程就是空转没充分利用GPU。而且你这里是一个线程处理了整个batch的数据，相当于只是在batch维度的并行。这样子不需要用到原子加，因为batch之间的写操作不会有冲突。

2020-12-16 15:01 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel_util.cu
> +    RUN_CUDA_KERNEL((DoCUDAReflectionPad2dGrad<T>), ctx, BlocksNum4ThreadsNum(elem_cnt),
这里应该是改成直接抛 elem_cnt 个线程，然后这样子下面就需要用到原子加，但是可以换个思路，你这里是启 输出梯度大小个线程，改成启动 输入梯度大小个线程，这样子，每个线程代表了输入梯度上的一个元素位置，这样子相当于从forward的角度去算梯度，每个线程就去找输出梯度上所有的与自己有关的梯度，加起来就好了，也不会与其他线程产生写冲突，就不需要用到原子加。

2020-12-16 15:06 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel_util.cu
> +    RUN_CUDA_KERNEL((DoCUDAReflectionPad2dGrad<T>), ctx, BlocksNum4ThreadsNum(elem_cnt),
而且改成启动 elem_cnt 个线程的话，下面的kernel实现需要改下，不能是一个线程处理整个batch，这样子能想象到很慢应该

2020-12-17 15:14 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel_util.cu
> +    RUN_CUDA_KERNEL((DoCUDAReflectionPad2dGrad<T>), ctx, BlocksNum4ThreadsNum(elem_cnt),
已修改

2020-12-17 15:15 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel_util.h
> +  XPU_1D_KERNEL_LOOP(n, n_batch){
修改并发线程数为elem_cnt

2020-12-18 07:34 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel_util.cu
> +    <<<BlocksNum4ThreadsNum(elem_cnt), thread_num, 0, ctx->cuda_stream()>>>(
https://github.com/Oneflow-Inc/oneflow/blob/ed70c73fb94ce835ab668774640398567043a39a/oneflow%2Fcore%2Fdevice%2Fcuda_util.h#L125

BlocksNum4ThreadsNum -> SMBlocksNum4ThreadsNum
thread_num -> kCudaThreadsNumPerBlock

2020-12-18 07:40 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel_util.cu
> +      <<<BlocksNum4ThreadsNum(elem_cnt), thread_num, 0, ctx->cuda_stream()>>>(
https://github.com/Oneflow-Inc/oneflow/blob/ed70c73fb94ce835ab668774640398567043a39a/oneflow%2Fcore%2Fdevice%2Fcuda_util.h#L125

BlocksNum4ThreadsNum -> SMBlocksNum4ThreadsNum
thread_num -> kCudaThreadsNumPerBlock

2020-12-18 07:58 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel_util.h
> +  int64_t elem_num = n_batch * dest_num;
elem_num， dest_num 和 src_num 都可以在kernel函数外算好再传进来，这样子不用每个线程都重新算一边

2020-12-18 07:59 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel_util.h
> +  int64_t elem_num = n_batch * src_num;
同上，上面3个变量可以在kernel函数外计算好

2020-12-18 08:06 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel_util.h
> +  XPU_1D_KERNEL_LOOP(k , elem_num){
这里是复用了前向计算的代码，启动输出梯度大小个线程，还是需要原子加，如果float16的原子实现不了。
那么建议换成启动输入大小个线程，然后每个线程对应到输入梯度的某个点的计算，实现的就是去输出梯度中找所有关联的点，然后加起来，这样子也只有边界的点线程工作多一些。但是所有线程都是直接写，而现在的实现是每个线程最后都会调用原子加，原子操作我记得是挺慢的。

2020-12-18 08:07 UTC, Ldpe2G commented on oneflow/user/kernels/reflection_pad2d_kernel_util.h
> +  XPU_1D_KERNEL_LOOP(k , elem_num){
一般padding的大小都不大，所以换成启动输入大小个线程和输出大小其实差不多。

2020-12-18 10:23 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel_util.h
> +  int64_t elem_num = n_batch * src_num;
已修改

2020-12-18 10:23 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel_util.h
> +  int64_t elem_num = n_batch * dest_num;
已修改

2020-12-18 10:23 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel_util.cu
> +      <<<BlocksNum4ThreadsNum(elem_cnt), thread_num, 0, ctx->cuda_stream()>>>(
已修改

2020-12-18 10:23 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel_util.cu
> +    <<<BlocksNum4ThreadsNum(elem_cnt), thread_num, 0, ctx->cuda_stream()>>>(
已修改

2020-12-18 10:35 UTC, Flowingsun007 commented on oneflow/user/kernels/reflection_pad2d_kernel_util.h
> +  XPU_1D_KERNEL_LOOP(n, n_batch){
已修改

2020-12-18 11:45 UTC, Ldpe2G commented on oneflow/python/test/ops/test_reflection_pad2d.py
> +            # ,(np.float32, flow.float16)
所以现在fp16是能跑的吗

2020-12-18 11:59 UTC, Flowingsun007 commented on oneflow/python/test/ops/test_reflection_pad2d.py
> +            # ,(np.float32, flow.float16)
> 所以现在fp16是能跑的吗

跑不了，有点问题

2020-12-18 12:42 UTC, Ldpe2G commented on oneflow/user/ops/reflection_pad2d_op.cpp
> +  FOR_RANGE(int64_t, i, 0, x_tensor.shape().NumAxes()) {
这里的split，貌似只能在第0和1维上切，在2和3上切，逻辑上就不对，因为pad的时候是pad第2和3维度，合并回来shape就不对了

2020-12-18 12:45 UTC, Ldpe2G commented on oneflow/user/ops/reflection_pad2d_op.cpp
> +  FOR_RANGE(int64_t, i, 0, x_tensor.shape().NumAxes()) {
https://github.com/Oneflow-Inc/oneflow/blob/856ba4ab2c04535965d396c830df051baa8a5a10/oneflow%2Fuser%2Fops%2Fpad_op.cpp#L47

这个可以参考原来的pad_op，只有当2和3维的pad为0的时候才能切

2020-12-18 12:48 UTC, Ldpe2G commented on oneflow/user/ops/reflection_pad2d_op.cpp
> +    ctx->NewBuilder().Split(ctx->inputs(), i).Split(ctx->outputs(), i).Build();
同上

2020-12-18 12:52 UTC, Flowingsun007 commented on oneflow/user/ops/reflection_pad2d_op.cpp
> +  FOR_RANGE(int64_t, i, 0, x_tensor.shape().NumAxes()) {
好的，我看下

2020-12-18 13:02 UTC, Ldpe2G commented
还有可以测一下kernel的有效带宽，根据这个 https://github.com/Oneflow-Inc/OneTeam/issues/167 提到的方法测下 gpu实现的有效带宽

2020-12-21 05:08 UTC, Flowingsun007 commented on oneflow/user/ops/reflection_pad2d_op.cpp
> +  FOR_RANGE(int64_t, i, 0, x_tensor.shape().NumAxes()) {
已修改

2020-12-21 05:08 UTC, Flowingsun007 commented on oneflow/python/test/ops/test_reflection_pad2d.py
> +            # ,(np.float32, flow.float16)
现在fp16可以正常跑了

2020-12-21 06:14 UTC, Flowingsun007 commented
> 还有可以测一下内核的有效带宽，根据这个[Oneflow-Inc / OneTeam＃167](https://github.com/Oneflow-Inc/OneTeam/issues/167)提到的方法测下gpu实现的有效带宽

15服务器
```shell
# debug版带宽
I1221 13:49:49.377595 40255 kernel.cpp:89] PROFILER::KERNEL::CUDA_MEMORY_BANDWIDTH op_name: Reflection_Pad2d2 elapsed(ms): 0.206976 memory_size(Byte): 50430048 bandwidth(GB/s): 226.918
I1221 13:49:49.378180 40255 kernel.cpp:89] PROFILER::KERNEL::CUDA_MEMORY_BANDWIDTH op_name: Reflection_Pad2d2_grad elapsed(ms): 0.30992 memory_size(Byte): 50430048 bandwidth(GB/s): 151.544
# release版带宽
I1221 14:11:39.015688 46634 kernel.cpp:89] PROFILER::KERNEL::CUDA_MEMORY_BANDWIDTH op_name: Reflection_Pad2d2 elapsed(ms): 0.142944 memory_size(Byte): 50430048 bandwidth(GB/s): 328.567
I1221 14:11:39.015939 46634 kernel.cpp:89] PROFILER::KERNEL::CUDA_MEMORY_BANDWIDTH op_name: Reflection_Pad2d2_grad elapsed(ms): 0.234144 memory_size(Byte): 50430048 bandwidth(GB/s): 200.589
```

2020-12-21 06:40 UTC, Ldpe2G approved these changes

2020-12-26 02:17 UTC, merged