add l1 loss op in python
Oneflow-Inc/oneflow pull request #3793
Opened 2020-11-10 13:32 UTC by MARD1NO

增加 L1 Loss op

2020-11-11 03:19 UTC, doombeaker commented on oneflow/python/test/ops/test_l1_loss.py
> +    @flow.global_function(function_config=func_config, type="train")
type  和 function_conf 按照test case的编程习惯，type写前面。

2020-11-11 03:22 UTC, doombeaker commented on oneflow/python/test/ops/test_l1_loss.py
> +def compare_l1loss_with_np(
仅当前脚本使用的函数，习惯上下划线开头

2020-11-11 09:31 UTC, doombeaker commented on oneflow/python/test/ops/test_l1_loss.py
> +    def test_l1loss_gpu(test_case):
GPU 的test case 要加上 `@unittest.skipIf(os.getenv("ONEFLOW_TEST_CPU_ONLY"), "only test cpu cases")`，要不然过不了CPU-ONLY的测试。可以参考 `test_broadcast_maximum.py` 等文件

2020-11-11 09:33 UTC, doombeaker commented on oneflow/python/test/ops/test_l1_loss.py
> +    for i in range(1, len(np_out_l1loss)):
这里是不是把numpy的标量转成数字，再直接用 numpy.allcose 更好？循环一个一个比效率低也不好看。

2020-11-11 09:34 UTC, doombeaker commented on oneflow/python/test/ops/test_l1_loss.py
> +    def test_l1loss_gpu(test_case):
GPU 的test case 要加上 `@unittest.skipIf(os.getenv("ONEFLOW_TEST_CPU_ONLY"), "only test cpu cases")`，要不然过不了CPU-ONLY的测试。可以参考 `test_broadcast_maximum.py` 等文件

2020-11-11 09:46 UTC, doombeaker commented on oneflow/python/test/ops/test_l1_loss.py
> +            initializer=flow.ones_initializer(),
这里用 `ones_initializer` 是有什么特别用意吗？一般用 `zeros_initializer` 更直观，不会让其它人多想？

2020-11-11 09:48 UTC, doombeaker commented on oneflow/python/ops/nn_ops.py
> +        output = |Target - Input|
还没有添加 reduction 参数有关的说明以及公式变化

2020-11-11 10:00 UTC, doombeaker commented on oneflow/python/test/ops/test_l1_loss.py
> +def _compare_l1loss_with_np(
需要添加关于反向diff的测试

2020-11-11 10:01 UTC, doombeaker requested changes
添加反向diff的测试，以及其它comment中相关

2020-11-11 11:14 UTC, MARD1NO commented on oneflow/python/test/ops/test_l1_loss.py
> +    for i in range(1, len(np_out_l1loss)):
呃这里我是拿一个job做了 reduce='none', 'mean', 'sum' 的三组测试。返回一个里面有3个元素的列表。 

numpy也是这样做

然后列表每个元素进行比较。

2020-11-11 11:14 UTC, MARD1NO commented on oneflow/python/test/ops/test_l1_loss.py
> +            initializer=flow.ones_initializer(),
只是我随便加的，换成zero有啥区别吗，是为了减少对代码的误解？

2020-11-11 11:15 UTC, MARD1NO commented on oneflow/python/ops/nn_ops.py
> +        output = |Target - Input|
好的，在mse那里加了这里忘记加了，后续会补上

2020-11-11 11:15 UTC, MARD1NO commented on oneflow/python/test/ops/test_l1_loss.py
> +def _compare_l1loss_with_np(
好的，添加到todo list

2020-11-12 09:45 UTC, wyg1997 commented on oneflow/python/ops/nn_ops.py
> +            # It's equal to `Torch.nn.L1Loss(reduction="mean")
我们是不是不需要专门标出来对标其它哪个框架的哪个op？

2020-11-12 09:45 UTC, wyg1997 commented on oneflow/python/ops/nn_ops.py
> +            # It's equal to `Torch.nn.L1Loss(reduction="sum")
这个也一样，不需要专门标出

2020-11-12 09:45 UTC, wyg1997 commented on oneflow/python/ops/nn_ops.py
> +        name = "L1Loss"
```suggestion
        name = id_util.UniqueStr("L1Loss_")
```

2020-11-12 09:45 UTC, wyg1997 commented on oneflow/python/ops/nn_ops.py
> +        reduction (str): The reduce type, it can be the one of "none", "mean", "sum". Defaults to "mean".
代码中没有对 `reduction` 做检察。

2020-11-12 09:51 UTC, MARD1NO commented on oneflow/python/ops/nn_ops.py
> +        reduction (str): The reduce type, it can be the one of "none", "mean", "sum". Defaults to "mean".
谢谢提醒，新版本已增加 T T

2020-11-13 14:33 UTC, doombeaker commented on oneflow/python/ops/nn_ops.py
> +
还有个 文件 `oneflow/python/ops/loss_ops.py`，好像是专门放loss的，但是目前只放了一个 smooth_loss，你可以权衡下，放哪个文件比较好。

2020-11-13 14:38 UTC, doombeaker commented on oneflow/python/test/ops/test_l1_loss.py
> +"""
文件名叫做 `test_l1loss.py` 更好？现在的习惯都是 `test_opname.py`，你的op是 `l1loss`不是`l1_loss`

2020-11-13 14:40 UTC, doombeaker commented on oneflow/python/test/ops/test_l1_loss.py
> +from typing import List, Dict
List 已经没有用到了

2020-11-13 14:42 UTC, doombeaker commented on oneflow/python/test/ops/test_l1_loss.py
> +        elemcnt = np.reshape(elemcnt, -1)
这句多余了

2020-11-13 14:44 UTC, doombeaker requested changes
考虑下文件名，去除不必要的代码

2020-11-13 15:05 UTC, doombeaker commented on oneflow/python/ops/nn_ops.py
> +        name = "L1Loss_"
这个 `_` 是多余的？因为你后面做字符串拼接已经有下划线。
虽然不影响功能，但是和你写的另外的loss的风格不一致

2020-11-13 23:40 UTC, MARD1NO commented on oneflow/python/ops/nn_ops.py
> +
我有想过。但如果和torch对齐，是放在nn模块下的话（nn.L1Loss)

在 loss_ops.py下，export成 `nn.L1Loss` 会不会有点怪

2020-11-16 01:40 UTC, doombeaker approved these changes

2020-11-18 11:12 UTC, merged