add bceloss
Oneflow-Inc/oneflow pull request #3804
Opened 2020-11-11 13:42 UTC by MARD1NO

增加 Binary Cross entropy loss 
公式为
![图片](https://user-images.githubusercontent.com/42901638/98818530-a8ab6100-2466-11eb-845c-62a3d74b297f.png)

TODO:
- [ ] 增加测试例子
- [ ] 增加梯度验证

2020-11-12 07:46 UTC, doombeaker commented on oneflow/python/ops/nn_ops.py
> +        weight (remote_blob_util, optional): The manual rescaling weight to the loss, the default scale factor is 1. Defaults to None.
the default scale factor is 1. Defaults to None.
这里是不是容易有歧义，想要表达的是不是
Default to None, whose corresponding weight value is 1.

2020-11-12 07:46 UTC, doombeaker commented on oneflow/python/ops/nn_ops.py
> +        reduction (str, optional): The reduce type, it can be the one of "none", "mean", "sum". Defaults to "mean".
the one -> one

2020-11-12 07:49 UTC, doombeaker commented on oneflow/python/ops/nn_ops.py
> +    weight: remote_blob_util = None,
weight 的注解类型是不对的，想写的是 remote_blob_util.BlobDef 吗？
我看实现，其实应该是float类型？

2020-11-12 07:51 UTC, doombeaker commented on oneflow/python/test/ops/test_bce_loss.py
> +
github 提示这里没有换行，估计是末尾的换行符不是 `\n`

2020-11-12 09:39 UTC, MARD1NO commented on oneflow/python/ops/nn_ops.py
> +    weight: remote_blob_util = None,
weight不是float类型

他是用于缩放loss的， 所以是一个矩阵元素对应相乘

2020-11-13 02:23 UTC, doombeaker commented on oneflow/python/test/ops/test_bce_loss.py
> +        elemcnt = np.reshape(elemcnt, -1)
这一步是必须的吗？elemcnt如果是数字，后续会被自动广播的吧

2020-11-13 02:25 UTC, doombeaker commented on oneflow/python/test/ops/test_bce_loss.py
> +        arg_dict = OrderedDict()
产生样本数据的代码可以考虑封装复用下

2020-11-13 02:26 UTC, MARD1NO commented on oneflow/python/test/ops/test_bce_loss.py
> +        elemcnt = np.reshape(elemcnt, -1)
...好像是改代码改错了，不应该有这句话的，我去删了

2020-11-13 07:34 UTC, doombeaker commented on oneflow/python/test/ops/test_bce_loss.py
> +        arg_dict = _gen_arg_dict(shape, device_type, machine_ids, device_counts)
直接`arg_dict = _gen_arg_dict((3, 16),  ”cpu", "0:0",  1)` 就可以了？
如果是想提示参数意义，那就可以：
`arg_dict = _gen_arg_dict(shape=(3, 16),  device_type=”cpu", machine_ids="0:0",  device_counts=1)`

2020-11-13 07:38 UTC, doombeaker commented on oneflow/python/test/ops/test_bce_loss.py
> +            "np_bce_grad_sum": np_bce_grad_sum,
这个 sum 的梯度貌似其实一直没有用到？可以去掉，这个函数也就不用返回dict了

2020-11-13 07:39 UTC, doombeaker requested changes
去掉多余的代码。简化测试参数

2020-11-13 08:37 UTC, doombeaker approved these changes

2020-11-22 12:02 UTC, jackalcooper commented
note:
this branch seems to consistently reproduce eager crash

2020-11-22 18:02 UTC, merged