Dev cpp instructions builder
Oneflow-Inc/oneflow pull request #3829
Opened 2020-11-14 12:36 UTC by lixinqi

c++ instruction builder

2020-11-15 07:35 UTC, clackhan requested changes

2020-11-15 07:35 UTC, clackhan commented on oneflow/core/framework/instructions_builder.cpp
> +Maybe<int64_t> NewSymbolId(vm::IdGenerator* id_generator,
换个函数名是不是个更合适？例如GetNewSymbolIdAndInitInstructionHead

2020-11-15 07:35 UTC, clackhan commented on oneflow/core/framework/symbol_id_cache.h
> +  template<typename CreateT>
CreateT是一个Id生成器吧，改成CreateId语义更加合适

2020-11-15 07:46 UTC, lixinqi commented on oneflow/core/framework/instructions_builder.cpp
> +Maybe<int64_t> NewSymbolId(vm::IdGenerator* id_generator,
匿名空间里的函数取简略一点应该没事

2020-11-15 07:46 UTC, lixinqi commented on oneflow/core/framework/symbol_id_cache.h
> +  template<typename CreateT>
CreateT其实就是Create的类型，我把这里换成std::function吧

2020-11-16 07:39 UTC, clackhan approved these changes

2020-11-17 02:24 UTC, merged