Add SElu activation
Oneflow-Inc/oneflow pull request #4129
Opened 2021-01-18 07:00 UTC by BBuf

这个激活函数来自论文：https://arxiv.org/abs/1706.02515 。这篇论文核心就是提出了这一激活函数，然后论文写了93页公式来证明只需要把激活函数换成SELU就能使得输入在经过一定层数之后变成固定的分布。在数学形式上这个激活函数实际上就是在ELU激活函数的基础上乘以了一个$\lambda$，但需要注意的是这个$\lambda$是大于1的。详细讨论见：https://www.zhihu.com/question/60910412 。 本地已测试完毕。

2021-01-18 07:17 UTC, doombeaker commented
.github/PULL_REQUEST_TEMPLATE 下有 OP 的 PR 模板，供参考：
https://github.com/Oneflow-Inc/oneflow/blob/master/.github/PULL_REQUEST_TEMPLATE/op_template.md

需要按照模板要求填写相关信息，另外也需要按照模板提示，添加 `label` （否则过不了CI检查）

2021-01-18 07:49 UTC, MARD1NO requested changes

2021-01-18 07:49 UTC, MARD1NO commented on oneflow/python/ops/nn_ops.py
> +    """
https://github.com/Oneflow-Inc/oneflow/blob/master/oneflow/python/ops/nn_ops.py#L403-L405 可以参考这里，加一个 Attention，强调说明一下lambda的合理取值范围

2021-01-18 07:49 UTC, MARD1NO commented on oneflow/python/ops/nn_ops.py
> +    lambda_ = float(lambda_)
加个assert数值检查，这样报错更加清晰

2021-01-18 08:33 UTC, BBuf commented on oneflow/python/ops/nn_ops.py
> +    lambda_ = float(lambda_)
在c++里面写了，还需要在python端写一次吗

2021-01-18 08:34 UTC, BBuf commented on oneflow/python/ops/nn_ops.py
> +    lambda_ = float(lambda_)
刚测了一下，如果lambda的值不是大于1，测试的时候会抛出oneflow_api.exception.CheckFailedException: msg: "lambda_ value: 1 for SELU op is illegal." ，是有报错提醒的。

2021-01-18 08:45 UTC, BBuf commented on oneflow/python/ops/nn_ops.py
> +    lambda_ = float(lambda_)
好的，我去改一下。

2021-01-18 09:48 UTC, doombeaker commented on oneflow/user/kernels/selu_kernel.cpp
> +template<DeviceType device_type, typename T>
和上一个 PR 的问题类似，CPU/GPU Kernel class 可以合并

2021-01-27 03:55 UTC, MARD1NO requested changes

2021-01-27 03:55 UTC, MARD1NO commented on oneflow/python/ops/nn_ops.py
> +    lambda_: float = 1.0507009873554804934193349852946,
参数命名去掉下划线，下同

2021-01-27 03:55 UTC, MARD1NO commented on oneflow/python/ops/nn_ops.py
> +    lambda_: float = 1.0507009873554804934193349852946,
参数命名为  scale 和 alpha

2021-01-27 03:55 UTC, MARD1NO commented on oneflow/python/ops/nn_ops.py
> +        .Attr("lambda_", lambda_)
C++层的参数名字也要换

2021-01-27 03:55 UTC, MARD1NO commented on oneflow/python/test/ops/test_selu.py
> +        lambda_ = np.array(lambda_).astype(np.float16)
单测部分的命名也记得换

2021-01-27 03:55 UTC, MARD1NO commented on oneflow/python/ops/nn_ops.py
> +    For example: make
make去掉

2021-01-27 03:55 UTC, MARD1NO commented on oneflow/python/ops/nn_ops.py
> +        \text{SELU}(x) = \begin{cases}
公式修改

2021-01-27 03:55 UTC, MARD1NO commented on oneflow/python/ops/nn_ops.py
> +        oneflow_api.BlobDesc: The activated Tensor.
API文档可参考指南 https://github.com/Oneflow-Inc/OneTeam/issues/94。生成文档。如果是服务器上生成，可以下载到本地来查看效果

2021-01-27 03:55 UTC, MARD1NO commented on oneflow/user/kernels/selu_kernel.h
> +    const T lambda_ = static_cast<T>(ctx->Attr<double>("lambda_"));
不要在这里强制转换，依旧保持double类型，否则对于SELU这种参数的小数点有效位多的情况，会出现中间截断，精度损失。在functor运算结果那里再强制转换

2021-01-27 11:24 UTC, MARD1NO requested changes

2021-01-27 11:24 UTC, MARD1NO commented on oneflow/python/ops/nn_ops.py
> +            return flow.nn.selu(x, scale=1.2, alpha=1.0)
要不例子就不要设置scale和alpha了，用应该也是用默认值

2021-01-27 11:24 UTC, MARD1NO commented on oneflow/python/test/ops/test_elu.py
> +            alpha=5.2,
elu的单测就不要包含在你这个PR里，我另外起一个修改

2021-01-27 11:24 UTC, MARD1NO commented on oneflow/python/test/ops/test_selu.py
> +            return np.array(out).astype(np.float16).astype(value_type[0])
可以加个注释，解释为什么要这么做（因为要对齐cuda的float2half类似这些）

2021-01-27 11:24 UTC, MARD1NO commented on oneflow/user/kernels/selu_kernel.cpp
> +}  // namespace oneflow
结尾换行

2021-01-27 11:24 UTC, MARD1NO commented on oneflow/user/kernels/selu_kernel.h
> +    const double scale = static_cast<T>(ctx->Attr<double>("scale"));
去掉static_cast

2021-01-27 11:24 UTC, MARD1NO commented on oneflow/user/kernels/selu_kernel.h
> +    const double alpha = static_cast<T>(ctx->Attr<double>("alpha"));
去掉static_cast

2021-01-27 11:24 UTC, MARD1NO commented on oneflow/user/kernels/selu_kernel.cpp
> +  void operator()(DeviceCtx* ctx, const int64_t elem_cnt, T scale, T alpha, T* out, const T* in) {
scale alpha 的类型都设置为double，下面也是

2021-01-27 12:27 UTC, BBuf commented on oneflow/python/test/ops/test_selu.py
> +            return np.array(out).astype(np.float16).astype(value_type[0])
注释我不加，上次我加了注释，你让我把注释去掉。

2021-01-28 01:44 UTC, MARD1NO requested changes

2021-01-28 01:44 UTC, MARD1NO commented on oneflow/user/kernels/selu_kernel.cu
> +  void operator()(DeviceCtx* ctx, const int64_t elem_cnt, T scale, T alpha, T* out, const T* in) {
scale alpha类型改成double

2021-01-28 01:44 UTC, MARD1NO commented on oneflow/user/kernels/selu_kernel.cu
> +  void operator()(DeviceCtx* ctx, const int64_t elem_cnt, T scale, T alpha, T* dx, const T* y,
同上

2021-01-28 01:44 UTC, MARD1NO commented on oneflow/user/kernels/selu_kernel.h
> +    return (x > static_cast<T>(0)) ? scale * x : scale * alpha * (exp(x) - static_cast<T>(1));
返回的结果也加static_cast<T>

2021-01-28 01:44 UTC, MARD1NO commented on oneflow/user/kernels/selu_kernel.h
> +    return (x > static_cast<T>(0)) ? scale * dy : dy * scale * alpha * (exp(x));
同上

2021-01-28 01:44 UTC, MARD1NO commented on oneflow/user/kernels/selu_kernel.h
> +  void operator()(DeviceCtx* ctx, const int64_t elem_cnt, T scale, T alpha, T* out, const T* in);
scale alpha类型改成double

2021-01-28 01:44 UTC, MARD1NO commented on oneflow/user/kernels/selu_kernel.h
> +  void operator()(DeviceCtx* ctx, const int64_t elem_cnt, T scale, T alpha, T* dx, const T* x,
scale alpha类型改成double

2021-01-28 01:44 UTC, MARD1NO commented on oneflow/user/kernels/selu_kernel.h
> +#endif  // _ONEFLOW_USER_KERNELS_ELEMENTWISE_SELU_KERNEL_H_
结尾换行

2021-01-30 10:46 UTC, Ldpe2G commented on oneflow/python/ops/nn_ops.py
> +    For example:
文档例子一般是放最后，参数的解释放例子之前

2021-01-30 11:30 UTC, Ldpe2G commented on oneflow/user/ops/selu_op.cpp
> +      if (scale > 1.0) { return Maybe<void>::Ok(); }
一般逻辑，函数最后返回 maybe::OK ，只有异常情况才返回 error

2021-01-30 11:34 UTC, Ldpe2G commented on oneflow/user/ops/selu_op.cpp
> +      if (scale > 1.0) { return Maybe<void>::Ok(); }
这里同上

2021-01-31 03:55 UTC, doombeaker commented on oneflow/python/ops/nn_ops.py
> +    Args:
不知大为什么 github 会解析到按道理和这个PR无关的 elu 部分的代码会变化。
可能是误操作也可能是 github 解析失败了。
一般保险起见，应该把新增的代码放到文件最后，放在中间会有github解析出错的可能。

2021-01-31 03:57 UTC, doombeaker commented on oneflow/python/test/ops/test_selu.py
> +def _compare_selu_with_np(
看文件名变化，是做了 `git mv oneflow/python/test/ops/test_elu.py oneflow/python/test/ops/test_selu.py` 吗，那原来的 `test_elu.py` 是不是被（不小心）删除了

2021-01-31 04:10 UTC, BBuf commented on oneflow/python/test/ops/test_selu.py
> +def _compare_selu_with_np(
不小心被删除了。

2021-01-31 04:12 UTC, BBuf commented on oneflow/python/test/ops/test_selu.py
> +def _compare_selu_with_np(
我记得了，上次再elu里面加了个注释，然后文件就变化了，后面在file changed界面误点了删除

2021-01-31 04:13 UTC, BBuf commented on oneflow/python/ops/nn_ops.py
> +    Args:
应该是那个elu被删除的问题吧？我需要把这个再放末尾吗

2021-02-01 00:54 UTC, doombeaker commented on oneflow/user/kernels/selu_kernel.cu
> +struct ElemwiseSeluFunctor<DeviceType::kGPU, Opt, T> final {
这里的 Opt 没用上

2021-04-29 09:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Oneflow-Inc/oneflow?pullRequest=4129) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Oneflow-Inc/oneflow?pullRequest=4129) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: guo-ran<br/>:x: BBuf<br/>:x: MARD1NO<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Oneflow-Inc/oneflow?pullRequest=4129) it.</sub>

2021-07-12 09:10 UTC, closed without merging