Reduce unittest cost
Oneflow-Inc/oneflow pull request #4253
Opened 2021-02-23 11:28 UTC by chengtbf

通过移除一些冗余的测试选项，节省op单测的时间。

2021-02-23 11:29 UTC, jackalcooper approved these changes

2021-02-23 15:32 UTC, liujuncheng requested changes

2021-02-23 15:32 UTC, liujuncheng commented on oneflow/python/test/ops/test_broadcast_normal.py
> +        arg_dict["data_type"] = ["float32"]
别删double的测试

2021-02-24 08:26 UTC, chengtbf commented
重构了 test_boxing_v2 和 test_broadcast_logical_ops ，在不减少测试用例的情况下，大幅减少需要创建的job的数量（减少6-12倍），测试速度提升2-16倍。约节省十几分钟的CI时间。 @liujuncheng

2021-02-24 09:26 UTC, liujuncheng commented on oneflow/python/test/ops/test_tril.py
> +        arg_dict["fill_value"] = [1.0]
原来的 1.0 与 0 是不同的参数数据类型

2021-02-24 09:26 UTC, liujuncheng commented on oneflow/python/test/ops/test_tril.py
> +        arg_dict["fill_value"] = [1.0]
原来的 1.0 与 0 是不同的参数数据类型

2021-02-24 09:26 UTC, liujuncheng commented on oneflow/python/test/ops/test_fused_scale_tril.py
> +        arg_dict["fill_value"] = [1.0]
1.0和0是不同的参数类型

2021-02-24 09:26 UTC, liujuncheng commented on oneflow/python/test/ops/test_moments.py
> +        arg_dict["axes"] = [[0], [0, 1]]
`[0, 2]`要保留，因为是不连续的维度

2021-02-24 09:26 UTC, liujuncheng commented on oneflow/python/test/ops/test_prelu.py
> +        arg_dict["shared_axes"] = [(2,), (1, 2, 3)]
(1,2)应该保留吧，如果能加上[0, 2]这种就更好了

2021-02-24 09:26 UTC, liujuncheng commented on oneflow/python/test/ops/test_sort.py
> +    arg_dict["data_type"] = ["int32", "int64"]
sort和数据类型还挺相关的，最好保留

2021-02-24 09:26 UTC, liujuncheng commented on oneflow/python/test/ops/test_top_k.py
> +    arg_dict["data_type"] = ["double", "int64"]
top_k 类似 sort

2021-02-24 09:47 UTC, ScXfjiang commented on oneflow/python/test/ops/test_sort.py
> +    arg_dict["in_shape"] = [(100,), (10, 10, 200)]
sort & argsort跑起来还是比较耗时的，建议尽可能较少笛卡尔积和输入Tensor大小。
```suggestion
    arg_dict["in_shape"] = [(10,), (10, 10, 20)]
```

2021-02-24 09:47 UTC, ScXfjiang commented on oneflow/python/test/ops/test_sort.py
> +    arg_dict["axis"] = [-2, -1, 0, 2]
```suggestion
    arg_dict["axis"] = [-2, 0, 2]
```

2021-02-24 09:47 UTC, ScXfjiang commented on oneflow/python/test/ops/test_argsort.py
>      arg_dict["in_shape"] = [(100,), (100, 100), (10, 10, 200)]
```suggestion
    arg_dict["in_shape"] = [(10,), (10, 10, 20)]
```

2021-02-24 09:47 UTC, ScXfjiang commented on oneflow/python/test/ops/test_argsort.py
> +    arg_dict["axis"] = [-2, 0, 1, 2]
```suggestion
    arg_dict["axis"] = [-2, 0, 2]
```

2021-02-24 09:47 UTC, ScXfjiang commented on oneflow/python/test/ops/test_top_k.py
> +    arg_dict["axis"] = [-2, -1, 0, 2]
```suggestion
    arg_dict["axis"] = [-2, 0, 2]
```

2021-02-24 10:46 UTC, liujuncheng approved these changes

2021-02-24 11:05 UTC, ScXfjiang commented on oneflow/python/test/ops/test_top_k.py
> -    arg_dict["k"] = [1, 50, 200]
这里不能去掉200，GPU && k > 128时会调用另一种算法，对应上面输入形状500的情况也要保留

2021-02-24 11:17 UTC, ScXfjiang approved these changes

2021-02-24 18:33 UTC, merged