Dev diag op
Oneflow-Inc/oneflow pull request #4382
Opened 2021-03-12 03:11 UTC by hengzi

## 概述
If `input` is a vector (1-D tensor), then returns a 2-D square tensor with the elements of `input` as the diagonal.
If `input` is a matrix (2-D tensor), then returns a 1-D tensor with the diagonal elements of `input`.

The argument `diagonal` controls which diagonal to consider:

- If `diagonal` = 0, it is the main diagonal.
- If `diagonal` > 0, it is above the main diagonal.
- If `diagonal` < 0, it is below the main diagonal.

## 功能 CheckList

### Op
 - [ ] Op SetBatchAxisInferFn
 - [ ] Op SetGetSbpFn
 - [ ] Op SetInputArgModifyFn
 - [ ] Op 反向梯度注册

### Kernel
 - [ ] CPU in:float32 
 - [ ] CPU in:float64
 - [ ] CPU in:int32
 - [ ] CPU in:int64
 - [ ] CPU in:int8

 - [ ] GPU in:float32 
 - [ ] GPU in:float64
 - [ ] GPU in:int32
 - [ ] GPU in:int64
 - [ ] GPU in:float16
 - [ ] GPU in:int8

### Python Wrapper
 - [ ] Python API 参数检查及异常提示
 - [ ] 接口注释
 - [ ] Example 

### 测试
 - [ ] 单机单卡  CPU Test Case 
 - [ ] 单机单卡  GPU Test Case 
 - [ ] 单机多卡  CPU Test Case 
 - [ ] 单机多卡  GPU Test Case
 - [ ] 分布式  CPU Test Case  
 - [ ] 分布式  GPU Test Case  

## GPU 有效带宽

理论带宽：
```text
 Device to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)	Bandwidth(MB/s)
   33554432			250798.5
```

实际带宽：
```
PROFILER::KERNEL::CUDA_MEMORY_BANDWIDTH op_name: sqrt_2 elapsed(ms): 0.196064 memory_size(Byte): 50331648 bandwidth(GB/s): 239.08
PROFILER::KERNEL::CUDA_MEMORY_BANDWIDTH op_name: sqrt_2_grad elapsed(ms): 0.29072 memory_size(Byte): 75497472 bandwidth(GB/s): 241.856
```

## PR Checklist
 - [ ] PR 标题语句通畅，明确表达 PR 内容，适合直接作为新版本发布时的 changelog
 - [ ] 代码格式化 
 - [ ] 已经本地编译通过
 - [ ] 已本地针对改动测试
 - [ ] 已添加 type 标签:(填写 type 标签名，如 `bug, enhancement, purge, feature, documentation`)
 - [ ] 已添加 component 标签:(填写 component 标签名，如 `op, system, eager, build, xla, python, ci, test, tooling, onnx`)
 - [ ] Draft 转正式 PR 前已请人 Review

2021-04-08 02:22 UTC, MARD1NO requested changes

2021-04-08 02:22 UTC, MARD1NO commented on oneflow/user/ops/diag_op.cpp
> +    .Attr<int32_t>("diagonal", 0)
我们接口有改动，将推导数据类型的，单独放在`SetInferDataTypeFn`。可参考 https://github.com/Oneflow-Inc/OneTeam/issues/335 该issue来进行修改。（但是可能需要切换到指定分支才能编译通过）

2021-04-08 02:22 UTC, MARD1NO commented on oneflow/python/test/ops/test_diag.py
> +
需要增加多卡单测

2021-04-08 02:22 UTC, MARD1NO commented on oneflow/user/ops/diag_op.cpp
> +        if (i == axis) { continue; }
这句是不是没必要

2021-04-08 02:22 UTC, MARD1NO commented on oneflow/user/ops/diag_op.cpp
> +        if (i == axis) { continue; }
这句是不是没必要

2021-04-08 02:22 UTC, MARD1NO commented on oneflow/user/ops/diag_op.cpp
> +      *out_desc->mut_data_type() = oneflow::kFloat;
这句话去掉

2021-04-23 07:07 UTC, hengzi commented on oneflow/python/test/ops/test_diag.py
> +        arg_dict["dtype"] = ["float32", "int32"]
加了多种测试情况，感觉跑测试的时间有点长

2021-04-23 07:09 UTC, hengzi commented on oneflow/user/kernels/diag_kernel.h
> +        size = std::min(in_shape.At(0), in_shape.At(1) - diagonal);
在Ubuntu Python3.8环境测试了没问题，Paddle注释上说的是Windows Python3.8，暂时没测试条件

2021-04-23 07:31 UTC, hengzi commented on oneflow/user/ops/diag_op.cpp
> +      *out_desc->mut_data_type() = oneflow::kFloat;
diag op 涉及到1维和2维之间的转换，应该不能使用Split

2021-04-25 02:20 UTC, MARD1NO approved these changes

2021-04-25 05:26 UTC, merged