Dev module tanh
Oneflow-Inc/oneflow pull request #4385
Opened 2021-03-12 05:26 UTC by Zailiang

add nn.Tanh

2021-03-17 10:28 UTC, doombeaker requested changes

2021-03-17 10:28 UTC, doombeaker commented on oneflow/python/nn/modules/activation.py
> +
github 这里提示文件结尾换行由问题，请检查排除下

2021-03-17 10:28 UTC, doombeaker commented on oneflow/python/nn/modules/activation.py
> +            flow.builtin_op("tanh").Name("tanh").Input("x").Output("y").Build()
此处写死 Name，会导致多次实例化的对象的 Name 属性重复了，应该使用 `id_util.UniqueStr`， 可以参考 https://github.com/Oneflow-Inc/oneflow/pull/4422/files 等其它 PR

2021-03-17 10:28 UTC, doombeaker commented on oneflow/python/test/ops/test_module.py
> +        test_case.assertTrue(np.allclose(y.numpy(), z, atol=1e-4))
```suggestion
        test_case.assertTrue(np.allclose(y.numpy(), z, rtol=1e-4, atol=1e-4 ))
```
相对和绝对误差都设置，保险一点（到底设多少，根据测试情况自己定一下，suggestion里的应该是可以的。

2021-03-17 10:28 UTC, doombeaker commented on oneflow/python/test/ops/test_module.py
> +        input_arr = np.array([-1, 0, 1]).astype(np.float32)
参考 `oneflow/python/test/xrt/test_tanh.py` 文件，测试样例看能否可以多几组，覆盖多一点的输入形状和值？

2021-04-02 09:27 UTC, Zailiang commented on oneflow/python/nn/modules/activation.py
> +            flow.builtin_op("tanh").Name("tanh").Input("x").Output("y").Build()
是不是现在又不用id_util了？

2021-04-02 09:28 UTC, Zailiang commented on oneflow/python/test/ops/test_module.py
> +        input_arr = np.array([-1, 0, 1]).astype(np.float32)
已建新测试文件 test_nn_tanh.py

2021-04-29 09:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Oneflow-Inc/oneflow?pullRequest=4385) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Oneflow-Inc/oneflow?pullRequest=4385) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Oneflow-Inc/oneflow?pullRequest=4385) it.</sub>

2021-06-07 09:01 UTC, BBuf commented on oneflow/python/nn/modules/activation.py
> +@register_tensor_op_by_module("tanh")
这个module master已经有了，我关掉这个pr。

2021-06-07 09:01 UTC, closed without merging