Create gelu.py
Oneflow-Inc/oneflow pull request #4396
Opened 2021-03-14 16:37 UTC by Zailiang

nn.gelu added

2021-03-17 10:37 UTC, doombeaker requested changes

2021-03-17 10:37 UTC, doombeaker commented on oneflow/python/nn/modules/activation.py
> +        return res
文末换行有问题。

2021-03-17 10:37 UTC, doombeaker commented on oneflow/python/test/ops/test_module.py
> +        test_case.assertTrue(np.allclose(y.numpy(), z, atol=1e-4))
通 tanh PR，最好设置 atol 和 rtol

2021-03-17 10:37 UTC, doombeaker commented on oneflow/python/test/ops/test_module.py
> +        z = np.array([-0.15426877, 0., 0.34573123])
可以多增几组测试样例

2021-04-29 09:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Oneflow-Inc/oneflow?pullRequest=4396) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Oneflow-Inc/oneflow?pullRequest=4396) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Oneflow-Inc/oneflow?pullRequest=4396) it.</sub>

2021-05-10 02:55 UTC, Zailiang commented on oneflow/python/test/ops/test_module.py
> +        test_case.assertTrue(np.allclose(y.numpy(), z, atol=1e-4))
已添加

2021-05-10 02:56 UTC, Zailiang commented on oneflow/python/nn/modules/activation.py
> +        return res
resolved

2023-04-13 08:14 UTC, closed without merging