split vector-matrix norm
Oneflow-Inc/oneflow pull request #5478
Opened 2021-07-13 09:19 UTC by puchapu

- 拆分 matrix norm 与 vector norm，满足 clip_by_norm 对齐需求。
- `torch.norm` 后续会弃用，因此选择与 `torch.linalg.norm` 接口对齐。
- `vector_norm` 支持 float 类型 order
- doctest
![doctest](https://user-images.githubusercontent.com/35329085/125784275-6bf84939-a07b-46b9-a34e-10f7a0cc341a.PNG)
- matrix_norm
![matrix_norm](https://user-images.githubusercontent.com/35329085/125784303-cd7711ee-b69d-42e1-9fdc-f25c150f5781.PNG)
- vector_norm
![vector_norm1](https://user-images.githubusercontent.com/35329085/125784393-22273d45-91f7-4354-bfc6-7fec2fbc7a20.PNG)

2021-07-13 10:01 UTC, MARD1NO requested changes

2021-07-16 02:03 UTC, MARD1NO commented on oneflow/python/nn/modules/norm.py
> +        return flow.experimental.max(input, dim= dim,keepdim = keepdim)
=后面这些空格都去掉

2021-07-16 02:03 UTC, MARD1NO commented on oneflow/python/nn/modules/norm.py
> +        return flow.experimental.max(input, dim= dim,keepdim = keepdim)
=后面这些空格都去掉

2021-07-16 02:34 UTC, puchapu commented on oneflow/python/nn/modules/norm.py
> +        elif isinstance(ord, (int, float)):
去除了 float 的话，传入 float 就会报错了吧

2021-07-16 02:34 UTC, puchapu commented on oneflow/python/nn/modules/norm.py
>          if isinstance(ord, str) and ord in ["fro", "nuc"]:
已修改

2021-07-16 02:37 UTC, puchapu commented on oneflow/python/nn/modules/norm.py
> +        elif dim == None:
这边感觉不能去掉吧，linalg.norm 的默认 dim == None，在那个里面调 Matrix_norm 的话就会把 none 传进来了（line 157）。或者就是我在 linalg.norm 里判断一下

2021-07-16 03:04 UTC, MARD1NO approved these changes

2021-07-16 03:04 UTC, MARD1NO commented on oneflow/python/nn/modules/norm.py
> +        elif isinstance(ord, (int, float)):
噢噢那这里不用去

2021-07-16 21:40 UTC, merged