add zhangshen op-test
Oneflow-Inc/oneflow pull request #5600
Opened 2021-07-26 08:17 UTC by zhangshen12356

2021-07-26 08:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Oneflow-Inc/oneflow?pullRequest=5600) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Oneflow-Inc/oneflow?pullRequest=5600) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Oneflow-Inc/oneflow?pullRequest=5600) it.</sub>

2021-07-26 16:03 UTC, guikarist commented
@zhangshen12356 `nn.AdaptiveAvgPoolXd`的bug已经解决

2021-07-26 16:05 UTC, guikarist commented on oneflow/python/test/modules/test_adaptive_pool.py
以前的测试都可以删除了

2021-07-26 16:06 UTC, guikarist commented on oneflow/python/test/modules/test_adaptive_pool.py
> +        m = torch.nn.AdaptiveAvgPool2d(output_size=random(1, 5).to(int))
`output_size`除了可以输入`int`以外还可以用`tuple`的形式输入，也需要测试

2021-07-26 16:08 UTC, zhangshen12356 commented on oneflow/python/test/modules/test_adaptive_pool.py
好的

2021-07-26 16:08 UTC, zhangshen12356 commented on oneflow/python/test/modules/test_adaptive_pool.py
> +        m = torch.nn.AdaptiveAvgPool2d(output_size=random(1, 5).to(int))
> `output_size`除了可以输入`int`以外还可以用`tuple`的形式输入，也需要测试

好的

2021-07-27 01:04 UTC, guikarist commented on oneflow/python/test/modules/test_adaptive_pool.py
> +        m = torch.nn.AdaptiveAvgPool2d(output_size=random(1, 5).to(int))
@zhangshen12356 相关测试我已经帮你在 #5615 ( 0415486 )写好了

2021-07-28 01:10 UTC, guikarist commented
@BBuf @zhangshen12356 `nn.AdaptiveAvgPool3d` GPU版本存在bug，PyTorch已经在`1.10.0`的nightly版本修复。因此暂时跳过，直到我们使用上述版本的PyTorch进行测试。

2021-07-30 01:17 UTC, BBuf commented
> 
> 
> @BBuf @zhangshen12356 `nn.AdaptiveAvgPool3d` GPU版本存在bug，PyTorch已经在`1.10.0`的nightly版本修复。因此暂时跳过，直到我们使用上述版本的PyTorch进行测试。

好，你先处理一下pr冲突。

2021-07-30 01:38 UTC, BBuf commented on oneflow/python/nn/modules/adaptive_pool.py
> +@oneflow_export("nn.AdaptiveAvgPool1d")
现在已经没有oneflow/python目录了，这里处理冲突的位置不对

2021-07-30 01:57 UTC, guikarist commented on oneflow/python/nn/modules/adaptive_pool.py
> +@oneflow_export("nn.AdaptiveAvgPool1d")
改好了

2021-07-30 02:01 UTC, guikarist commented
@zhangshen12356 你可以检查一下旧的test，如果不是使用numpy模拟的，是直接通过hard-coded输入输出测试的，都可以删除了

2021-07-30 02:03 UTC, zhangshen12356 commented
> @zhangshen12356 你可以检查一下旧的test，如果不是使用numpy模拟的，是直接通过hard-coded输入输出测试的，都可以删除了

好的

2021-07-30 02:19 UTC, BBuf commented on oneflow/user/kernels/adaptive_pool_gpu_kernel.cu
> +          // TODO: Use 'atmoic::Add' when necessary
这个TODO是不是无效。

2021-07-30 02:19 UTC, BBuf commented on oneflow/user/kernels/adaptive_pool_gpu_kernel.cu
> +    // TODO: Replace following codes with 'NdIndexOffsetHelper'
TODO后面记一下名字

2021-07-30 02:19 UTC, BBuf commented on python/oneflow/nn/modules/adaptive_pool.py
> +@experimental_api
这里还是不对，目前已经没有experimental空间了

2021-07-30 02:19 UTC, BBuf commented on python/oneflow/nn/modules/adaptive_pool.py
> +        >>> import oneflow.experimental as flow
这里也不对，参考一下最新的docstring写法

2021-07-30 02:19 UTC, BBuf commented on python/oneflow/nn/modules/adaptive_pool.py
> +        assert len(self.output_size) == 1,  f"the length of 'output_size' does not match the input size, 1 expected"
第一个assert和第二个assert可以合并
```suggestion
        assert len(x.shape) == 3 and assert len(self.output_size) == 1,  f"the length of 'output_size' does not match the input size, 1 expected"
```

2021-07-30 02:19 UTC, BBuf commented on python/oneflow/nn/modules/adaptive_pool.py
> +        >>> import oneflow.experimental.nn as nn
同上

2021-07-30 02:19 UTC, BBuf commented on python/oneflow/nn/modules/adaptive_pool.py
>          assert len(x.shape) == 4
assert 后面加一句提示语

2021-07-30 02:19 UTC, BBuf commented on python/oneflow/nn/modules/adaptive_pool.py
> +    See :mod:`oneflow.experimental.nn.AdaptiveAvgPool2d`
experimental已经没有了

2021-07-30 02:19 UTC, BBuf commented on python/oneflow/test/modules/test_negative.py
> +    def test_flow_tensor_negative_with_random_data(test_case):
由于这个api很简单，numpy数据不是精心构造的，那么就可以把上面的numpy模拟全部删掉

2021-07-30 02:19 UTC, BBuf commented on python/oneflow/test/modules/test_avgpool.py
>  class TestPoolingModule(flow.unittest.TestCase):
改下名字：TestAvgPooling

2021-07-30 02:19 UTC, BBuf commented on python/oneflow/test/modules/test_avgpool.py
> +    @autotest()
自动测试写法没有问题的话，可以把上面的numpy模拟全部删掉

2021-07-30 02:19 UTC, BBuf commented on python/oneflow/test/modules/test_pooling.py
> +    @autotest()
同上，可以删掉所有的numpy模拟

2021-07-30 02:19 UTC, BBuf commented on python/oneflow/test/modules/test_repeat.py
> +        import random
这里不需要import random

2021-07-30 02:19 UTC, BBuf commented on python/oneflow/test/modules/test_repeat.py
> +import oneflow.experimental as flow
没有这个命名空间了

2021-07-30 02:19 UTC, BBuf commented on python/oneflow/test/modules/test_tile.py
> +        import random
同上

2021-07-30 02:19 UTC, BBuf commented on python/oneflow/test_utils/automated_test_util/generators.py
> +import typing  # This unused import is needed
为什么要大量改动自动测试框架？

2021-07-30 02:44 UTC, zhangshen12356 commented on python/oneflow/test/modules/test_pooling.py
> +    @autotest()
好的

2021-07-30 02:46 UTC, zhangshen12356 commented on python/oneflow/test_utils/automated_test_util/generators.py
> +import typing  # This unused import is needed
我记得当时好像没有修改，可能是手误还是啥的可能弄错了

2021-07-30 03:06 UTC, guikarist commented on oneflow/user/kernels/adaptive_pool_gpu_kernel.cu
> +          // TODO: Use 'atmoic::Add' when necessary
不是的，这个意思是需要用的时候再用，但是按理说只有output_size比input_size大才需要。然而，加上述判断会出现别的bug...

2021-07-30 04:16 UTC, guikarist commented on oneflow/user/kernels/adaptive_pool_gpu_kernel.cu
> +    // TODO: Replace following codes with 'NdIndexOffsetHelper'
@zhangshen12356 
`adaptive_pool_gpu_kernel.cu`和`adaptive_pool_cpu_kernel.cpp`这俩文件的TODO都帮我改成这样的吧（加括号）：
```
// TODO (Tianyu): ...
```

2021-07-30 04:18 UTC, zhangshen12356 commented on oneflow/user/kernels/adaptive_pool_gpu_kernel.cu
> +    // TODO: Replace following codes with 'NdIndexOffsetHelper'
好的

2021-08-05 12:19 UTC, guikarist requested changes
AvgPool和MaxPool有一些东西要改

2021-08-05 12:19 UTC, guikarist commented on python/oneflow/test/modules/test_pooling.py
> +            dilation=random(1, 2).to(int),
@zhangshen12356 
`random`表示的是左闭**右开**区间，这么写的话`kernel_size`、`padding`、`dilation`都没有随机性了。
`MaxPool2d`、`MaxPool3d`、`AvgPool2d`、`AvgPool3d`都有这样的问题。

2021-08-05 12:19 UTC, guikarist commented on python/oneflow/test/modules/test_pooling.py
> +            dilation=random(1, 2).to(int),
@zhangshen12356 
是不是要考虑一下**非正方形**输入的测试？同理：`MaxPool3d`、`AvgPool2d`、`AvgPool3d`

2021-08-05 12:19 UTC, guikarist commented on python/oneflow/test/modules/test_avgpool.py
> +class TestAvgPoolingModule(flow.unittest.TestCase):
@zhangshen12356 
现在有`nn.AvgPool1d`了

2021-08-09 01:00 UTC, guikarist commented on python/oneflow/test/modules/test_pooling.py
> +            dilation=random(1, 2).to(int),
已解决

2021-08-09 01:00 UTC, guikarist commented on python/oneflow/test/modules/test_pooling.py
> +            dilation=random(1, 2).to(int),
已解决

2021-08-09 01:01 UTC, guikarist commented on python/oneflow/test/modules/test_avgpool.py
> +class TestAvgPoolingModule(flow.unittest.TestCase):
已添加

2021-08-09 01:25 UTC, guikarist approved these changes

2021-08-09 01:55 UTC, guikarist commented on python/oneflow/test/modules/test_pooling.py
> +            ceil_mode=random()
暂时没法测试`return_indices`，因为当这个值为`true`时，返回的obj是`tuple`，暂时自动测试框架中没有对应的checker

2021-08-09 02:08 UTC, daquexian commented on python/oneflow/test/modules/test_pooling.py
> +            ceil_mode=random()
可以先手动解包一下返回，这样自动测试框架是支持的

2021-08-09 02:14 UTC, guikarist commented
已经完善所有测试，`nn.AvgPoolXd`和`nn.MaxPoolXd`存在bug，待修复

2021-08-09 02:35 UTC, Flowingsun007 commented
> 已经完善所有测试，`nn.AvgPoolXd`和`nn.MaxPoolXd`存在bug，待修复
> 
> 除了`nn.AvgPool1d`和`nn.AvgPool2d`的bug是`ValueError: operands could not be broadcast together with shapes ...`（下方有traceback），其余module的bug均为梯度对不上
> 
> ```python
> Traceback (most recent call last):
>   File "/home/zhaotianyu/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 310, in new_f
>     test_case.assertTrue(check_equality(x, rtol=rtol, atol=atol), x)
>   File "/home/zhaotianyu/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 237, in check_equality
>     return checker(dual_object.pytorch, dual_object.oneflow, rtol, atol)
>   File "/home/zhaotianyu/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 259, in check_tensor_equality
>     equal_nan=True,
>   File "<__array_function__ internals>", line 6, in allclose
>   File "/home/zhaotianyu/.miniconda3/envs/oneflow-dev-gcc7/lib/python3.6/site-packages/numpy/core/numeric.py", line 2189, in allclose
>     res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
>   File "<__array_function__ internals>", line 6, in isclose
>   File "/home/zhaotianyu/.miniconda3/envs/oneflow-dev-gcc7/lib/python3.6/site-packages/numpy/core/numeric.py", line 2290, in isclose
>     return within_tol(x, y, atol, rtol)
>   File "/home/zhaotianyu/.miniconda3/envs/oneflow-dev-gcc7/lib/python3.6/site-packages/numpy/core/numeric.py", line 2276, in within_tol
>     return less_equal(abs(x-y), atol + rtol * abs(y))
> ValueError: operands could not be broadcast together with shapes (1,5,6) (1,5,7) 
> ```

可以构造一个复现的最小demo吗？（譬如输入是什么shape时，一定会触发bug）

2021-08-09 03:51 UTC, chengtbf commented
experimental 是不是可以去掉了

2021-08-09 04:04 UTC, zhangshen12356 commented
> experimental 是不是可以去掉了

好的

2021-08-09 04:32 UTC, guikarist commented
@Flowingsun007 好的稍等，不过这个pr下的test应该是每次都会复现错误

2021-08-09 04:33 UTC, guikarist commented
> experimental 是不是可以去掉了
> 
> 

pr里没来得及改，代码里都没了233

2021-08-09 10:06 UTC, guikarist commented
@Flowingsun007 
有关`nn.AvgPool1d`和`nn.AvgPool2d`bug的复现demo：
```python
@autotest(n=100)
def test_avgpool1d_with_random_data(test_case):
    m = torch.nn.AvgPool1d(
        kernel_size=4, stride=4, padding=2, ceil_mode=True
    )
    m.train(random())
    device = random_device()
    m.to(device)
    x = random_pytorch_tensor(ndim=3, dim0=1, dim1=4, dim2=21).to(device)
    y = m(x)
    return y

@autotest(n=100)
def test_avgpool2d_with_random_data(test_case):
    m = torch.nn.AvgPool2d(
        kernel_size=4, stride=4, padding=2, ceil_mode=True
    )
    m.train(random())
    device = random_device()
    m.to(device)
    x = random_pytorch_tensor(ndim=4, dim0=1, dim1=4, dim2=21, dim3=21).to(device)
    y = m(x)
    return y
```

2021-08-09 10:13 UTC, Flowingsun007 commented
> @Flowingsun007
> 有关`nn.AvgPoolXd`的shape bug复现demo：
> 
> ```python
> @autotest(n=100)
> def test_avgpool1d_with_random_data(test_case):
>     m = torch.nn.AvgPool1d(
>         kernel_size=4, stride=4, padding=2, ceil_mode=True
>     )
>     m.train(random())
>     device = random_device()
>     m.to(device)
>     x = random_pytorch_tensor(ndim=3, dim0=1, dim1=4, dim2=21).to(device)
>     y = m(x)
>     return y
> 
> @autotest(n=100)
> def test_avgpool2d_with_random_data(test_case):
>     m = torch.nn.AvgPool2d(
>         kernel_size=4, stride=4, padding=2, ceil_mode=True
>     )
>     m.train(random())
>     device = random_device()
>     m.to(device)
>     x = random_pytorch_tensor(ndim=4, dim0=1, dim1=4, dim2=21, dim3=21).to(device)
>     y = m(x)
>     return y
> 
> @autotest(n=100)
> def test_avgpool3d_with_random_data(test_case):
>     m = torch.nn.AvgPool3d(
>         kernel_size=4, stride=4, padding=2, ceil_mode=True
>     )
>     m.train(random())
>     device = random_device()
>     m.to(device)
>     x = random_pytorch_tensor(ndim=5, dim0=1, dim1=4, dim2=21, dim3=21, dim4=21).to(device)
>     y = m(x)
>     return y
> ```

不是随机的demo哈，我意思是有没有固定会触发bug的demo，特定shape/参数下一定会触发bug的（类似doctest里那样）

2021-08-09 10:15 UTC, guikarist commented
@Flowingsun007 这就是固定的demo，除了input tensor的数据是随机的以外

2021-08-09 10:18 UTC, Flowingsun007 commented
> @Flowingsun007 这就是固定的demo，除了input tensor的数据是随机的以外。而且是一定会触发的

好的，这个avgpool的bug泽康有空看下吧 @MARD1NO

2021-08-09 10:57 UTC, guikarist commented
> > @Flowingsun007 这就是固定的demo，除了input tensor的数据是随机的以外。而且是一定会触发的
> 
> 好的，这个avgpool的bug泽康有空看下吧 @MARD1NO
> 另外，maxpool系列是什么bug? 也麻烦给一个demo吧

所有的demo都给了

2021-08-09 11:35 UTC, guikarist commented on python/oneflow/test/modules/test_pooling.py
> +            ceil_mode=random()
已更改～

2021-08-11 01:24 UTC, Flowingsun007 commented
maxpoolxd的bug已在这个pr里修复：https://github.com/Oneflow-Inc/oneflow/pull/5818（已合并到master）

2021-08-16 03:18 UTC, BBuf approved these changes

2021-08-19 18:16 UTC, merged