Dev logical_xor module
Oneflow-Inc/oneflow pull request #5694
Opened 2021-08-02 09:37 UTC by LYZFU

2021-08-02 09:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Oneflow-Inc/oneflow?pullRequest=5694) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Oneflow-Inc/oneflow?pullRequest=5694) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Oneflow-Inc/oneflow?pullRequest=5694) it.</sub>

2021-08-03 02:34 UTC, hengzi commented on oneflow/core/ndarray/binary_func.h
> +  static OF_DEVICE_FUNC const int8_t Invoke(const T x, const T y) { return x != y; }
验证 （1 XOR 2）  是否正确

2021-08-04 02:55 UTC, hengzi reviewed
添加API文档截图，参考 #5636

2021-08-04 02:55 UTC, hengzi commented on python/oneflow/nn/modules/logical_xor.py
> +    .. code-block:: python
这里应该有一个换行，不然文档显示不对，参考其它文件

2021-08-06 02:36 UTC, hengzi commented on python/oneflow/compatible/single_client/nn/modules/logical_xor.py
> +    See :func:`oneflow.logical_and`
logical_and -> logical_xor

2021-08-06 02:36 UTC, hengzi commented on python/oneflow/compatible/single_client/nn/modules/logical_xor.py
> +        >>> out = flow.logical_and(input1, input2)
logical_and -> logical_xor
运行这个文件看下是否有报错

2021-08-06 02:36 UTC, hengzi commented on python/oneflow/nn/modules/logical_xor.py
> +    logical_or() -> Tensor
logical_or -> logical_xor

2021-08-06 07:26 UTC, doombeaker commented on python/oneflow/compatible/single_client/nn/modules/logical_xor.py
> +    return LogicalXor()(input, other)
之前因为功能的局限，才不得不用实例化 Module 的方式调用。现在有了 `flow.F` 下的 functional call，尽量直接调用。
可以参考这个PR 进行修改 https://github.com/Oneflow-Inc/oneflow/pull/5754

2021-08-06 07:31 UTC, doombeaker commented on python/oneflow/nn/modules/logical_xor.py
> +    return LogicalXor()(input, other)
之前因为功能的局限，才不得不用实例化 Module 的方式调用。现在有了 flow.F 下的 functional call，尽量直接调用。
可以参考这个PR 进行修改 #5754

2021-08-06 07:31 UTC, doombeaker commented on python/oneflow/compatible/single_client/__init__.py
>  import oneflow.compatible.single_client.nn.modules.greater_equal
single_client 下的文件不用修改，都复原吧。

2021-08-06 11:06 UTC, doombeaker requested changes

2021-08-06 11:06 UTC, doombeaker commented on python/oneflow/nn/modules/logical_xor.py
> +        other = flow.cast(other, input.dtype)
在这里加个以shape 的检查吧。类似
```
assert input.shape == other.shape, "shape of input and other should be same"
```
因为你这个算子内部是支持 broadcast 的，但是文档和 pytorch 对齐，是element-wise的。

或者，如果想作为 pytorch 超集，就在文档钟说明支持 broadcast。并且在 doctest、test 里添加相关的例子。

2021-08-09 01:43 UTC, hengzi commented on oneflow/core/ndarray/binary_func.h
>  struct BinaryFuncAny final {
这里是从上面移到下面了，还是需要的

2021-08-10 14:29 UTC, doombeaker approved these changes

2021-08-11 04:34 UTC, merged