Refactor scatter in cpp instead of in python
Oneflow-Inc/oneflow pull request #5715
Opened 2021-08-03 16:07 UTC by doombeaker

2021-08-03 16:09 UTC, doombeaker commented on oneflow/api/python/functional/python_functions.cpp
> +      return functional::OnesLike(in);  // TODO(yaochi): remove OnesLike
【问题】：这里的 `OnesLike` 的调用是多余的，其实上一句已经抛异常了，但是为了编译检查通过，必需返回个 `Maybe<Tensor>` 的对象。我们有办法构建个空白对象吗（像 nullptr 那种）

2021-08-03 16:11 UTC, doombeaker commented on oneflow/api/python/functional/python_functions.cpp
> +        src_value = *JUST(PyUnpackScalar(obj));
实测这个分支的结果是错的。
我猜测很有可能是因为 `src_value` 类型为 `Scalar`，而 `Scalar` 里的联合体，包含了 `double` 类型，但是没有 `float` 类型。而很不巧的，`dim_scatter_update_scalar` 算子的 `src` 这个属性，恰好是 `float` 类型。所以这里需要请教下，怎么 unpack 出 `Float` 类型。

2021-08-04 03:51 UTC, doombeaker commented on oneflow/api/python/functional/python_functions.cpp
> +        src_value = *JUST(PyUnpackScalar(obj));
已经解决，是不正确的使用了 `Optional` 和 `Scalar` 对象。

2021-08-04 04:53 UTC, hjchen2 requested changes

2021-08-04 04:53 UTC, hjchen2 commented on oneflow/api/python/functional/python_functions.cpp
> +    const auto& in = JUST(PyUnpackTensor(input));
先PyTensorCheck检查一下类型

2021-08-04 04:53 UTC, hjchen2 commented on oneflow/api/python/functional/python_functions.cpp
> +      Scalar& src_scalar = *JUST(src.value());
不要加引用，可能会导致bug

2021-08-04 09:00 UTC, doombeaker commented on oneflow/api/python/functional/python_functions.cpp
> +    const auto& in = JUST(PyUnpackTensor(input));
已经为各个要unpack的变量添加检查

2021-08-04 09:01 UTC, doombeaker commented on oneflow/api/python/functional/python_functions.cpp
> +    const auto& in = JUST(PyUnpackTensor(input));
已经通过本地的 moudles 测试 和 doctest 测试

2021-08-04 14:17 UTC, doombeaker commented on oneflow/api/python/functional/python_functions.cpp
> +      Scalar& src_scalar = *JUST(src.value());
已修改

2021-08-06 23:41 UTC, hjchen2 approved these changes

2021-08-08 02:11 UTC, merged