Feat eager consistent 2d sbp infer
Oneflow-Inc/oneflow pull request #7143
Opened 2021-12-29 12:56 UTC by wyg1997

2022-01-06 03:44 UTC, hjchen2 commented on oneflow/core/framework/sbp_infer_util.cpp
> +      total_cost += JUST(ComputCopyCostBetweenTwoSbpParallel(
拆成每个dim分别计算cost，这里的logical shape需要对前面已经计算过的维度进行切分么，或者切出剩下维度的logical shape

2022-01-06 03:44 UTC, hjchen2 commented on oneflow/core/operator/operator.cpp
> +        if (blob_modifier_.has_is_mutable() && blob_modifier_.is_mutable()) {
这里少考虑了inplace的问题？

2022-01-06 03:50 UTC, wyg1997 commented on oneflow/core/operator/operator.cpp
> +        if (blob_modifier_.has_is_mutable() && blob_modifier_.is_mutable()) {
inplace 的话有什么特征吗？之前考虑 inplace op 应该在 GetNdSbp 的时候就过滤掉了，这里就只考虑 op 间的代价了。

2022-01-06 05:06 UTC, hjchen2 commented on oneflow/core/operator/operator.cpp
> +        if (blob_modifier_.has_is_mutable() && blob_modifier_.is_mutable()) {
inplace影响的是推导sbp时的nd_sbp_constraints，确实你这里是GetNdSbp之后做的，已经是满足inplace要求的sbp，那就不需要再考虑了

2022-01-06 05:06 UTC, hjchen2 approved these changes

2022-01-06 06:28 UTC, wyg1997 commented on oneflow/core/framework/sbp_infer_util.cpp
> +      total_cost += JUST(ComputCopyCostBetweenTwoSbpParallel(
这个好像不好切，如果第 0 维是 S0 -> S1，第 1 维是 P -> B 的话，这里传的  logical_shape 就不好确定了。目前这样做粗略的估计已经基本可以搜索出代价更小的方案了，后面给 boxing 注册代价计算函数再做准确估计。

2022-01-06 13:01 UTC, leaves-zwx commented
使用 master 测试用户的 swin-transformer 模型，会遇到如下报错：

```
F0106 12:59:17.990619 1139777 op_graph.cpp:313]
  File "/home/zhangwenxiao/repos/oneflow/oneflow/core/graph/op_graph.cpp", line 313, in InferOpNodeNdSbpSignature
    op_node->mut_op()->InferNdSbpSignatureIf(nd_sbp_sig_conf, op_node->parallel_desc(), NdSbpInferHint4Ibn)
  File "/home/zhangwenxiao/repos/oneflow/oneflow/core/operator/operator.cpp", line 665, in InferNdSbpSignatureIf
    InferNdSbpSignature(&nd_sbp_signature, nd_sbp_constraints, parallel_desc, NdSbpInferHint4Ibn)
  File "/home/zhangwenxiao/repos/oneflow/oneflow/core/operator/user_op.cpp", line 758, in InferNdSbpSignature
    Operator::InferNdSbpSignature(nd_sbp_signature, nd_sbp_constraints, parallel_desc, NdSbpInferHint4Ibn)
op: model-expand_5_grad can't find available sbp signature.
Supported SBP signatures are: (in_0) -> (out_0): [
        (S(1)) -> (S(1)),
        (S(2)) -> (S(2)),
        (P) -> (P),
        (B) -> (B),
], but got (S(0)) -> ? at hierarchy dim 0, since the SBP of inputs are: in_0: (S(0), B)
*** Check failure stack trace: ***
```

可以看到是一个反向推导 2d sbp 遇到的错误，切换为本分支再跑一次（没改任何东西），遇到如下报错：

```
[ERROR](GRAPH:TrainGraph_0:TrainGraph) building graph got error: <class 'oneflow._oneflow_internal.exception.CheckFailedException'>
  File "/dataset/zwx_home/shared/tmp/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 139, in Dispatch<oneflow::one::Tensor>
    Dispatch<TensorTuple>(op_expr, inputs, ctx)
  File "/dataset/zwx_home/shared/tmp/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 131, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, inputs, outputs.get(), ctx)
  File "/dataset/zwx_home/shared/tmp/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 96, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/dataset/zwx_home/shared/tmp/oneflow/oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp", line 672, in ApplyImpl
    infer_ctx->AddAndInferConsistentOp(*op_conf)
  File "/dataset/zwx_home/shared/tmp/oneflow/oneflow/core/job/job_build_and_infer_ctx.cpp", line 604, in AddAndInferOp
    InferOpOutNdSbp(op, nd_sbp_sig_conf, parallel_desc)
  File "/dataset/zwx_home/shared/tmp/oneflow/oneflow/core/job/job_build_and_infer_ctx.cpp", line 252, in InferOpOutNdSbp
    op->InferNdSbpSignatureIf(nd_sbp_sig_conf, parallel_desc, NdSbpInferHint4Ibn)
  File "/dataset/zwx_home/shared/tmp/oneflow/oneflow/core/operator/operator.cpp", line 793, in InferNdSbpSignatureIf
    InferNdSbpSignature(&nd_sbp_signature, nd_sbp_constraints, parallel_desc, NdSbpInferHint4Ibn)
  File "/dataset/zwx_home/shared/tmp/oneflow/oneflow/core/operator/user_op.cpp", line 756, in InferNdSbpSignature
    val_->nd_sbp_infer_fn(&ctx)
  File "/dataset/zwx_home/shared/tmp/oneflow/oneflow/user/ops/reshape_user_op_util.cpp", line 213, in InferNdSbp
    ApplySbpParallel(out_sbp, parallel_hierarchy.At(i), &out_shape)
  File "/dataset/zwx_home/shared/tmp/oneflow/oneflow/user/ops/reshape_user_op_util.cpp", line 144, in ApplySbpParallel
    Check failed: (shape->At(axis) % parallel_num) == (0) (4 vs 0)
```

2022-01-06 16:41 UTC, Yipeng1994 commented on oneflow/core/framework/sbp_infer_util.cpp
> +      total_cost += JUST(ComputCopyCostBetweenTwoSbpParallel(
这里的粗略估计应该是这样，比如（S0, S1）-> (B, B), 一个4乘4的tensor，在（2,2）分级的卡上.
在算第二个维度 S1->B 的时候，后江的疑问应该是这里的 S1->B的logical blob shape 怎么算，是4呢？还是8呢？还是16呢？
因为是拆分估计，理论上某一个的可行传输逻辑其实是
(S0, S1) -> (B, S1) -> (B, B).
这也是我们这次粗略估计所采纳的逻辑。（后面精细估计由boxing注册的代价函数决定，取决于具体实现。）
每一次只变动一个维度的sbp，这时候就很好估计了。
这时候对于其他相同的sbp，碰到s就除以分级在该维度的分量。
所以计算的shape size在第一个维度的变动时为8，在第二个维度的变动时为16。
而总传输量在第一个维度的变动时为16， 在第二个维度的变动时为32. （传输量在AllGather时为shape size*(N_0 -1)*N_1），N_0时变动的维度的分级，N_1为不变的维度的分级的乘积，在这个例子的他们的值都为2.

结论：
在估计logical shape size时，shape取决于producer的小于当前维度的sbp以及consumer大于当前维度的sbp。
至于变更的维度可以用B来代替，然后再乘以通信的系数。
例子 （S0, S1, P, B, S2, S1, S0, B） -> (B, B, B, B, S1, S1, S1, S1)
在维度4的变更 S2 -> S1 时shape取决于
(S0, S1, P, B, B, S1, S1, S1)

2022-01-07 03:46 UTC, Yipeng1994 requested changes

2022-01-07 03:46 UTC, Yipeng1994 commented on oneflow/core/framework/sbp_infer_util.cpp
> +  }
这一段要分开写。
reduced_in_parallel_desc跟reduced_out_parallel_desc的形状不是一定一样的。
可以是(2, 2) 跟 4, 或者（2，3）跟（3, 2）。
然后不是加算，是乘算。
total_cost *= reduced_out_parallel_desc.hierarchy()->At(i)。
乘的时候不用减一。

2022-01-07 03:56 UTC, wyg1997 commented on oneflow/core/framework/sbp_infer_util.cpp
> +  }
哎是的

2022-01-07 04:25 UTC, Yipeng1994 requested changes

2022-01-07 04:25 UTC, Yipeng1994 commented on oneflow/core/operator/operator.cpp
> +        min_copy_cost = total_copy_cost;
这里两块代码执行同样的东西就尽量合并吧。
不然如果做一个改动，另外一个地方也需要复制粘贴。
一个是繁琐，第二个是有可能会忘了改导致出错。
从代码效率的角度，
min_copy_cost赋值为 GetValidMaxCopyCost()，
然后去掉 if (total_copy_cost <= GetValidMaxCopyCost()) {，
去掉  if (select_sbp_idx == -1) {
        select_sbp_idx = i;
        min_copy_cost = total_copy_cost;
代码能简化很多。

2022-01-07 04:28 UTC, wyg1997 commented on oneflow/core/operator/operator.cpp
> +        min_copy_cost = total_copy_cost;
好的

2022-01-07 04:37 UTC, wyg1997 commented on oneflow/core/operator/operator.cpp
> +        min_copy_cost = total_copy_cost;
done

2022-01-07 04:38 UTC, wyg1997 commented on oneflow/core/framework/sbp_infer_util.cpp
> +  }
done

2022-01-07 04:38 UTC, wyg1997 commented on oneflow/core/framework/sbp_infer_util.cpp
> +      total_cost += JUST(ComputCopyCostBetweenTwoSbpParallel(
done

2022-01-07 06:48 UTC, Yipeng1994 commented on oneflow/core/framework/sbp_infer_util.cpp
> +        total_cost *= reduced_out_parallel_desc.hierarchy()->At(i);
这是不同placement之间的算法：就是这里分开了以后，for里面用乘法，for之间用加法。
注：但是因为eager的实现很魔性，P到B还真就用了乘法。
如果P到B的bug修复了，从n平方掉回了2n，就一定要改回来。

2022-01-07 07:14 UTC, wyg1997 commented on oneflow/core/framework/sbp_infer_util.cpp
> +        total_cost *= reduced_out_parallel_desc.hierarchy()->At(i);
这里加了注释，表示现在 P->B 是直接传数据的，所以用乘法

2022-01-07 07:53 UTC, Yipeng1994 approved these changes

2022-01-10 13:11 UTC, wyg1997 commented
这个单测本地跑 1000 次没复现，先重跑一下

2022-01-10 14:35 UTC, merged

2022-01-27 07:36 UTC, chengtbf commented on oneflow/core/operator/operator.cpp
> +    err << "Condidate nd sbp signature are: "
这里有个拼写错误 😂 ，应该是 Candidate 吧

2022-01-27 07:39 UTC, wyg1997 commented on oneflow/core/operator/operator.cpp
> +    err << "Condidate nd sbp signature are: "
@Yipeng1994 你在你那个 PR 把这个 typo 改了吧