add specific interface of tensor
Oneflow-Inc/oneflow pull request #7443
Opened 2022-02-08 10:26 UTC by Aries-chen

支持除 BFloat16Tensor 外 HalfTensor、FloatTensor 和 DoubleTensor 等特定 dtype Tensor。

2022-02-08 10:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Oneflow-Inc/oneflow?pullRequest=7443) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Oneflow-Inc/oneflow?pullRequest=7443) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Oneflow-Inc/oneflow?pullRequest=7443) it.</sub>

2022-02-11 06:45 UTC, wyg1997 commented on python/oneflow/test/modules/test_type_tensor.py
> +    # {"specific tensor": flow.BFloat16Tensor, "dtype": flow.bfloat16},
这里忘改了

2022-02-11 06:45 UTC, wyg1997 commented on python/oneflow/test/modules/test_type_tensor.py
> +
每个文件的结尾有多余空行，可能是你编辑器的问题，试着解决一下

2022-02-11 09:15 UTC, Aries-chen commented on python/oneflow/test/modules/test_type_tensor.py
> +    # {"specific tensor": flow.BFloat16Tensor, "dtype": flow.bfloat16},
已经修改

2022-02-11 09:29 UTC, Aries-chen reviewed
![image](https://user-images.githubusercontent.com/62194666/153567465-4f9e8ab6-39f2-4c91-9ee6-8998aca3d3e4.png)

2022-02-11 09:29 UTC, Aries-chen commented on python/oneflow/test/modules/test_type_tensor.py
> +
居然是每个 我待会修改 请问代码最后换行是规定吗 比如
![image](https://user-images.githubusercontent.com/62194666/153565554-36773e33-fac8-4497-a077-155ac1a4e915.png)
最后一行没有代码

2022-02-11 09:29 UTC, Aries-chen commented on python/oneflow/test/modules/test_type_tensor.py
> +
> 每个文件的结尾有多余空行，可能是你编辑器的问题，试着解决一下
请问代码最后换行是规定吗 比如 最后一行没有代码 
![image](https://user-images.githubusercontent.com/62194666/153566548-08c7c677-9f59-42b7-88dc-1f131f912d68.png)

2022-02-11 09:29 UTC, Aries-chen commented on python/oneflow/test/modules/test_type_tensor.py
> +
![image](https://user-images.githubusercontent.com/62194666/153567033-f48693d9-5f3f-4ab1-9b1c-cb3c1f90803b.png)

2022-02-11 09:32 UTC, wyg1997 commented on python/oneflow/test/modules/test_type_tensor.py
> +
哦哦，好像也没问题，代码格式化工具会自动处理，那点 resolve 吧

2022-02-11 09:33 UTC, wyg1997 reviewed
然后你需要把这个文件导出，截图放在 issue 的描述中

2022-02-14 02:59 UTC, wyg1997 approved these changes

2022-02-14 03:11 UTC, MARD1NO requested changes

2022-02-14 03:11 UTC, MARD1NO commented on python/oneflow/framework/type_tensor.py
> +    return flow.Tensor(*args, **kwargs).to(flow.float16).to("cuda")
写反了，放错文件了

2022-02-14 03:11 UTC, MARD1NO commented on python/oneflow/test/modules/test_type_tensor.py
> +@unittest.skipIf(os.getenv("ONEFLOW_TEST_CPU_ONLY"), "only test cpu cases")
这个不对吧，CPU tensor测试应该单独提出来，然后不用加skip

然后GPU tensor测试需要加这个skip

2022-02-14 03:19 UTC, MARD1NO commented on python/oneflow/cuda/type_tensor.py
> +    return flow.Tensor(*args, **kwargs).to(flow.int64).to("cuda")
代码最后换行（of的习惯

2022-02-14 03:19 UTC, MARD1NO commented on python/oneflow/framework/type_tensor.py
> +
要不在这里也加个todo:BFloat16Tensor，在单测里加可能不太好记起来

2022-02-14 03:25 UTC, wyg1997 reviewed
给文档中的 oneflow.Tensor 加个超链接吧

2022-02-14 03:25 UTC, wyg1997 commented on python/oneflow/cuda/type_tensor.py
> +    Creates a Tensor with the dtype of float16 and it has the same parameters as oneflow.Tensor.
```suggestion
    Creates a Tensor with the dtype of float16 and it has the same parameters as :func:`oneflow.Tensor`.
```

2022-02-14 03:28 UTC, Aries-chen commented on python/oneflow/cuda/type_tensor.py
> +    return flow.Tensor(*args, **kwargs).to(flow.int64).to("cuda")
OK

2022-02-14 03:29 UTC, Aries-chen commented on python/oneflow/framework/type_tensor.py
> +
放的具体位置有讲究吗 
![image](https://user-images.githubusercontent.com/62194666/153795358-3cefee6b-3b5c-47d3-83c3-95ab8b81e784.png)

2022-02-14 04:20 UTC, Aries-chen reviewed
增加了 todo 和句末 Tensor 的超链接 可点击跳转
![image](https://user-images.githubusercontent.com/62194666/153799299-92ac2959-3baa-40ff-9e88-56fa35c85890.png)
![image](https://user-images.githubusercontent.com/62194666/153799348-d8ce3a1e-002e-4b12-a63c-2eda676d8958.png)
@wyg1997  @MARD1NO

2022-02-14 04:25 UTC, MARD1NO approved these changes

2022-02-14 04:52 UTC, Aries-chen reviewed
增加了 Tensor 超链接和 todo
![image](https://user-images.githubusercontent.com/62194666/153801988-213674eb-b83f-4c73-a3f2-d656295ac7d3.png)
![image](https://user-images.githubusercontent.com/62194666/153802089-29caf269-8e1d-4489-8ce5-e8b152e8bc4d.png)

2022-02-14 12:41 UTC, merged