Fix a bug (typo)
Oneflow-Inc/oneflow pull request #7657
Opened 2022-03-02 12:53 UTC by Yipeng1994

Fix a bug in the middle nodes algorithm

2022-03-02 12:56 UTC, hjchen2 approved these changes

2022-03-02 13:04 UTC, L1aoXingyu approved these changes

2022-03-02 13:20 UTC, wyg1997 approved these changes

2022-03-02 13:35 UTC, clackhan approved these changes

2022-03-04 05:50 UTC, strint commented on oneflow/core/auto_parallel/boxing_collector.cpp
> +        std::cout << "Consumer: "
需要改下日志等级到VLOG(3)

2022-03-04 05:53 UTC, strint requested changes

2022-03-04 05:53 UTC, strint commented on oneflow/core/auto_parallel/boxing_collector.cpp
> +          std::cout << boxing_collector_consumer->minimum_copy_cost_[diag_consumer][id_consumer];
需要改下日志等级到VLOG(3)

2022-03-04 05:53 UTC, strint commented on oneflow/core/framework/sbp_infer_util.cpp
> +    if (LazyMode::is_enabled() || /*single_client=*/(!JUST(IsMultiClient()))) {
single_client 已经从0.7删除，无效考虑了

2022-03-04 06:08 UTC, strint commented on oneflow/core/auto_parallel/boxing_collector.cpp
> +        std::cout << "Consumer: "
现在执行会默认就打出这个日志

2022-03-04 06:33 UTC, Yipeng1994 commented on oneflow/core/auto_parallel/boxing_collector.cpp
> +        std::cout << "Consumer: "
呃。。。这是我debug的code，没注意，我去删掉

2022-03-04 08:19 UTC, strint approved these changes

2022-03-05 03:30 UTC, chengtbf commented
这个 PR 是不是 CI 过了就能合并了？

2022-03-05 04:21 UTC, Yipeng1994 commented
> 这个 PR 是不是 CI 过了就能合并了？

对对对，不过之前CI一直申请不到机器

2022-03-05 04:37 UTC, jackalcooper commented
merged to https://github.com/Oneflow-Inc/oneflow/pull/7687

2022-03-05 04:38 UTC, closed without merging

2022-03-05 10:16 UTC, Yipeng1994 commented
merged了，高优就是开心啊