Add unbind op
Oneflow-Inc/oneflow pull request #7730
Opened 2022-03-08 14:34 UTC by chengyuma

接口文档
![截屏2022-03-08 下午10 28 39](https://user-images.githubusercontent.com/32220480/157259079-66b7dfcf-02f5-4d75-9bee-9e90ea66ad24.png)

2022-03-10 09:20 UTC, Flowingsun007 commented on oneflow/core/functional/impl/array_functor.cpp
> +  Maybe<TensorTuple> operator()(const std::shared_ptr<one::Tensor>& x, const int64_t& dim) const {
dim用int32就行

2022-03-10 09:21 UTC, Flowingsun007 approved these changes

2022-03-10 09:24 UTC, simonJJJ approved these changes

2022-03-10 09:36 UTC, BBuf approved these changes

2022-03-10 09:36 UTC, BBuf commented on oneflow/core/functional/impl/array_functor.cpp
> +    int32_t ndim = x->ndim();
```suggestion
    const int32_t ndim = x->ndim();
```

2022-03-10 09:36 UTC, BBuf commented on python/oneflow/test/modules/test_unbind.py
> +    @autotest(check_graph=True)
5次吧

2022-03-10 11:01 UTC, chengyuma commented on oneflow/core/functional/impl/array_functor.cpp
> +    int32_t ndim = x->ndim();
已修改

2022-03-11 09:23 UTC, hjchen2 commented
加一个global的单测

2022-03-11 09:23 UTC, hjchen2 requested changes
加global的测试

2022-04-13 13:22 UTC, hjchen2 commented on python/oneflow/test/modules/test_consistent_unbind.py
> +    dim_size = random(2, 6).to(int).value() * 8
(2, 6)太大了，改成（1， 3）吧

2022-04-14 01:41 UTC, Flowingsun007 commented on python/oneflow/test/modules/test_consistent_unbind.py
> +    dim_size = random(2, 6).to(int).value() * 8
已修改

2022-04-14 13:25 UTC, merged