Fix gather kernel check
Oneflow-Inc/oneflow pull request #7979
Opened 2022-04-07 13:49 UTC by BBuf

给gather op加了index check，使它的值限制在指定维度的长度中，对齐报错信息。

2022-04-07 13:50 UTC, BBuf commented on oneflow/user/kernels/dim_gather_kernel_util.h
> +#ifdef __CUDA_ARCH__
cpu的报错信息对齐了pytorch，但gpu这里没有类似于pytorch CUDA_KERNEL_ASSERT这种宏就没完全对齐这个信息。

2022-04-08 02:54 UTC, MARD1NO approved these changes

2022-04-08 02:54 UTC, MARD1NO commented on oneflow/user/kernels/dim_gather_kernel_util.h
> +    assert(x < dim_lengh && "gather index is out of bounds");
dim_lengh -> dim_length？

2022-04-08 02:58 UTC, BBuf commented on oneflow/user/kernels/dim_gather_kernel_util.h
> +    assert(x < dim_lengh && "gather index is out of bounds");
拼写错误，我改下

2022-04-08 02:59 UTC, MARD1NO requested changes

2022-04-08 02:59 UTC, MARD1NO commented on oneflow/user/kernels/dim_gather_kernel_util.h
> +#ifdef WITH_CUDA
问了下juncheng，这里应该是 `__CUDA_ARCH__`

2022-04-08 03:00 UTC, Flowingsun007 approved these changes

2022-04-08 03:01 UTC, BBuf commented on oneflow/user/kernels/dim_gather_kernel_util.h
> +#ifdef WITH_CUDA
ok

2022-04-08 03:04 UTC, BBuf commented on oneflow/user/kernels/dim_gather_kernel_util.h
> +#ifdef WITH_CUDA
这里的区别是什么？

2022-04-08 03:24 UTC, doombeaker approved these changes

2022-04-08 03:24 UTC, doombeaker commented on oneflow/user/kernels/dim_gather_kernel_util.h
> +    assert(x < dim_length && "gather index is out of bounds");
```suggestion
    assert(x < dim_length); // gather index is out of bounds
```

是不是用注释就可以了，这个字符串的作业也只是注释作用？

2022-04-08 03:24 UTC, doombeaker commented on oneflow/user/kernels/dim_gather_kernel_util.cu
> +                                int64_t elem_cnt, int64_t dim_length, int32_t dim, const IDX_T* index,
```suggestion
                                int64_t elem_cnt, int64_t dim_length, int32_t dim, const IDX_T* index,
```
 int64_t dim_length 如果用 `int32_t` 也够的话，最好用 `int32_t` ，给 global kernel 的传参瘦身是很重要的。
不过我不确定 `int32_t` 是否够用，你更能准确判断吧。

2022-04-08 03:26 UTC, BBuf commented on oneflow/user/kernels/dim_gather_kernel_util.cu
> +                                int64_t elem_cnt, int64_t dim_length, int32_t dim, const IDX_T* index,
好的，我改回int32_t

2022-04-08 03:27 UTC, BBuf commented on oneflow/user/kernels/dim_gather_kernel_util.h
> +    assert(x < dim_length && "gather index is out of bounds");
好像不太一样，如果触发了这个检查会直接在命令行上抛出这个错误。

2022-04-08 04:43 UTC, MARD1NO approved these changes

2022-04-08 23:58 UTC, doombeaker commented on oneflow/user/kernels/dim_gather_kernel_util.h
> +    assert(x < dim_length && "gather index is out of bounds");
不会吧，assert应该是没有打印的能力的。

这里的字符串只是一个表达式，表达式的值是一个有效的指针地址(总不为0)。所以assert到底值是多少，完全取决于dim_length，所以这个字符串我觉得就只是注释用了。

另外我搜了下代码里，.cu 文件里的assert都没这样加字符串的

2022-04-17 15:00 UTC, merged