fix upsample shape infer bug
Oneflow-Inc/oneflow pull request #8105
Opened 2022-04-27 02:42 UTC by BBuf

fix upsample shape infer bug caused by float precision. linked: https://github.com/Oneflow-Inc/libai/pull/260#issuecomment-1108372399

2022-04-27 03:55 UTC, MARD1NO requested changes
Add Attr<vector>("output_size")

2022-04-27 05:40 UTC, simonJJJ reviewed
为什么设置eps=1e-5呢

2022-04-27 05:43 UTC, BBuf commented
> 为什么设置eps=1e-5呢

准备基于output_size重构一下，先忽略这个改动，会去掉。

2022-05-11 06:20 UTC, simonJJJ reviewed
这个地方还有必要保留scale吗

2022-05-11 06:28 UTC, MARD1NO commented on oneflow/core/functional/impl/array_functor.cpp
> +                           const Optional<std::vector<int64_t>>& output_size,
我看底下好像都没用到output_size，是不是可以不用传

2022-05-11 06:28 UTC, MARD1NO commented on oneflow/ir/include/OneFlow/OneFlowUserOps.td
> +    SI64ArrayAttr:$output_size,
要不要包一个optional？

2022-05-11 06:28 UTC, MARD1NO commented on oneflow/user/kernels/upsample_bicubic_2d_kernel.cu
> +      height_scale = out_height * 1.0 / in_height;
height_scale = static_cast<double>(out_height) / static_cast<double>(in_height);

2022-05-11 06:28 UTC, MARD1NO commented on oneflow/user/ops/upsample_op.cpp
> +        Shape({x_desc.shape().At(0), x_desc.shape().At(1), static_cast<int32_t>(output_size[0])});
应该是cast 成 int64_t

2022-05-11 06:28 UTC, MARD1NO commented on oneflow/user/kernels/upsample_bicubic_2d_kernel.cpp
> +    const std::vector<int64_t> output_size = ctx->Attr<std::vector<int64_t>>("output_size");
output_size, scale 二者留一个

2022-05-11 06:35 UTC, BBuf commented on oneflow/core/functional/impl/array_functor.cpp
> +                           const Optional<std::vector<int64_t>>& output_size,
@zhongshsh 这里是写漏了吧，可以再检查一下。

2022-05-11 06:36 UTC, BBuf commented on oneflow/ir/include/OneFlow/OneFlowUserOps.td
> +    SI64ArrayAttr:$output_size,
ODS不支持optional attr，只支持optional tensor

2022-05-11 06:37 UTC, BBuf commented on oneflow/user/kernels/upsample_bicubic_2d_kernel.cpp
> +    const std::vector<int64_t> output_size = ctx->Attr<std::vector<int64_t>>("output_size");
这个地方目前有一点点难改，留到后续pr处理，暂不影响功能。

2022-05-11 06:37 UTC, BBuf commented on oneflow/user/ops/upsample_op.cpp
> +        Shape({x_desc.shape().At(0), x_desc.shape().At(1), static_cast<int32_t>(output_size[0])});
好的

2022-05-11 06:40 UTC, BBuf commented on oneflow/user/kernels/upsample_bicubic_2d_kernel.cu
> +      height_scale = out_height * 1.0 / in_height;
好的

2022-05-11 07:03 UTC, BBuf commented
> interpolate.py 103行这个地方还有必要保留scale吗

这个暂时去不掉，因为scale不是Optional的，改起来工作量依然比较大，准备下个pr来做。

2022-05-11 07:55 UTC, simonJJJ commented on oneflow/user/ops/upsample_op.cpp
> +                                  static_cast<int32_t>(scale_factor * x_desc.shape().At(2))});
这里是不是要cast成int64_t？下面还有好几个类似的情况

2022-05-11 08:12 UTC, BBuf commented on oneflow/user/ops/upsample_op.cpp
> +                                  static_cast<int32_t>(scale_factor * x_desc.shape().At(2))});
done!

2022-05-11 08:15 UTC, simonJJJ approved these changes

2022-05-11 08:48 UTC, MARD1NO commented on oneflow/core/functional/impl/array_functor.cpp
> +                           const Optional<std::vector<int64_t>>& output_size,
这个outputsize好像也没用到

2022-05-11 08:48 UTC, MARD1NO commented on oneflow/user/kernels/upsample_linear_1d_kernel.cpp
>      dy_helper.OffsetToNdIndex(index, n, c, h);
```cpp
OF_DEVICE_FUNC T GetLinearInputIndex(const int64_t out_dim_idx, const T scale, bool align_corners) {
```
应该是直接
```
template<IndexType> // 这里你们都默认是int64_t，有没有这个模板参数也无所谓了
OF_DEVICE_FUNC IndexType GetLinearInputIndex(const int64_t out_dim_idx, const double scale, bool align_corners) {
    static_cast<IndexType>(...); 
}
```
然后底下也不用
```cpp
const T h1r = GetLinearInputIndex(h, scale_factor, align_corners);
const int64_t h1 = h1r;
```
直接
```cpp
const int64_t h1r = GetLinearInputIndex<int64_t>(h, scale_factor, align_corners);
```
就可以了吧，所有kernel都要改一下

2022-05-11 08:48 UTC, MARD1NO commented on oneflow/user/ops/upsample_op.cpp
> +        Shape({x_desc.shape().At(0), x_desc.shape().At(1), static_cast<int64_t>(output_size[0])});
这里不用static_cast了，output_size本身就是int64_t，下同

2022-05-11 09:22 UTC, BBuf commented on oneflow/user/kernels/upsample_linear_1d_kernel.cpp
>      dy_helper.OffsetToNdIndex(index, n, c, h);
不是特别明白，这里的完整代码是：

```c++
const T h1r = GetLinearInputIndex(h, scale_factor, align_corners);
  const int64_t h1 = h1r;
  const int64_t h1p = (h1 < in_height - 1) ? 1 : 0;
  const T h1lambda = h1r - h1;
  const T h0lambda = static_cast<T>(1.) - h1lambda;
```

需要h1r和h1的插值来作为插值的系数

2022-05-11 09:23 UTC, BBuf commented on oneflow/user/ops/upsample_op.cpp
> +        Shape({x_desc.shape().At(0), x_desc.shape().At(1), static_cast<int64_t>(output_size[0])});
done

2022-05-11 09:23 UTC, BBuf commented on oneflow/core/functional/impl/array_functor.cpp
> +                           const Optional<std::vector<int64_t>>& output_size,
done

2022-05-11 09:26 UTC, BBuf commented on oneflow/user/kernels/upsample_linear_1d_kernel.cpp
>      dy_helper.OffsetToNdIndex(index, n, c, h);
> template<IndexType> // 这里你们都默认是int64_t，有没有这个模板参数也无所谓了

这句话没看懂，没有默认是int64_t，应该是double

2022-05-12 00:03 UTC, MARD1NO approved these changes

2022-05-21 15:25 UTC, merged