unique identity
Oneflow-Inc/oneflow pull request #8509
Opened 2022-06-28 08:57 UTC by strint

- [x] Avoid duplicated identity op for Activation Checkpointing or  Pipeline.
- [x] Special scope name for identity op.

2022-06-30 03:36 UTC, chengtbf commented on python/oneflow/nn/graph/block.py
> +        print("==>key: ", key)
这里 debug 的内容可以先删掉

2022-06-30 06:29 UTC, chengtbf commented on python/oneflow/nn/graph/block.py
> +            ident_name_scope = graph_build_util.make_new_name_scope(self.prev_scope, self.name_prefix + self.name)
这个 name，包含当前 identity 即将进入的这个 module 的 name 吗？

2022-06-30 06:35 UTC, strint commented on python/oneflow/nn/graph/block.py
> +            ident_name_scope = graph_build_util.make_new_name_scope(self.prev_scope, self.name_prefix + self.name)
包括了。 

self.name_prefix 是前缀， self.name就是当前module的name。当前module就是配置了 activation_checkpointing 或者 stage_id，触发 identity 创建的 module。

2022-06-30 06:43 UTC, strint commented on python/oneflow/nn/graph/block.py
> +        print("==>key: ", key)
done

2022-06-30 07:14 UTC, chengtbf commented
这个优化是有效的：

对于 BERT 单机单卡， layer = 8 , bsz = 16

master 显存占用： 5.5G
本 分支 ： 5.0G

主要是节省了： 

- master  `In Device: 0 Chunk id: 0 MemBlock id: 201 has num = 831 ops with mem size = 3587.81 is reused 1`
- 本分支 `In Device: 0 Chunk id: 0 MemBlock id: 201 has num = 840 ops with mem size = 3170.51 is reused 1`

对于 BERT 1n2g pp2 ， layer 8， bsz = 16

- master: 

```
 Graph name GraphBase_0 in Rank: 0, Device: 0 needs to allocate [ 3802.45 MiB ] device memory.                                                                             In general, Chunk id: 0  memory is [ 2546.23 MiB ];                                                
Memory out of Chunk is  [ 1256.22 MiB ]; and in particular: Eager Variable Tensor total memory is [ 616.327 MiB ].
Graph name GraphBase_0 in Rank: 1, Device: 1 needs to allocate [ 2680.12 MiB ] device memory.
 In general, Chunk id: 1  memory is [ 1961.65 MiB ];      
```

- 本分支

```
in Rank: 0, Device: 0 needs to allocate [ 3752.12 MiB ] device memory.                                                                             
 In general, Chunk id: 0  memory is [ 2546.23 MiB ];                                                
Memory out of Chunk is  [ 1205.89 MiB ]; and in particular: Eager Variable Tensor total memory is [ 616.327 MiB ].
Graph name GraphBase_0 in Rank: 1, Device: 1 needs to allocate [ 2680.12 MiB ] device memory.
In general, Chunk id: 1  memory is [ 1961.65 MiB ];                                                
Memory out of Chunk is  [ 718.471 MiB ]; and in particular: Eager Variable Tensor total memory is [ 430.25 MiB ]
```

可以先测试一下。 BERT 还有别的内存问题，但是比较隐晦，正在查。先用这个 commit 看一下内存省到多少吧。

2022-07-04 01:29 UTC, chengtbf approved these changes

2022-07-04 07:01 UTC, leaves-zwx approved these changes

2022-07-04 07:08 UTC, chengtbf commented on python/oneflow/nn/graph/block.py
> +        key = input_tensor
这里应该还是有问题。

在流水并行 PP = 4 的情况下， stage 0 没问题，但是 stage 1、2、3 均没有复用第一个 identity，而是仍然创建了多个 identity。

```
 350708 I20220704 06:57:41.285405 2289291 plan_util.cpp:1011]      In Device: 1 Chunk id: 3 MemBlock id: 81 has num = 210 tensor with mem size = 299.893                                                                              
 350709 I20220704 06:57:41.285413 2289291 plan_util.cpp:1021] In Chunk id: 3, MemBlock id: 81 Order: 0 ,duration: 175 ,size: 2.09722 MiB, name: model.bert.encoders.12-identity-389/out_0
 350710 shape: (8,1,512,512) ,dtype: kBool ,alloc_order: 0 ,free_order: 174                                 
 350711 I20220704 06:57:41.285420 2289291 plan_util.cpp:1021] In Chunk id: 3, MemBlock id: 81 Order: 1 ,duration: 174 ,size: 2.09722 MiB, name: model.bert.encoders.9-identity-296/out_0 350712 shape: (8,1,512,512) ,dtype: kBool ,alloc_order: 1 ,free_order: 174                                 
 350713 I20220704 06:57:41.285427 2289291 plan_util.cpp:1021] In Chunk id: 3, MemBlock id: 81 Order: 2 ,duration: 173 ,size: 2.09722 MiB, name: model.bert.encoders.8-identity-265/out_0
 350714 shape: (8,1,512,512) ,dtype: kBool ,alloc_order: 2 ,free_order: 174                                  350715 I20220704 06:57:41.285435 2289291 plan_util.cpp:1021] In Chunk id: 3, MemBlock id: 81 Order: 3 ,duration: 172 ,size: 2.09722 MiB, name: model.bert.encoders.7-identity-234/out_0
 350716 shape: (8,1,512,512) ,dtype: kBool ,alloc_order: 3 ,free_order: 174                                 
 350717 I20220704 06:57:41.285446 2289291 plan_util.cpp:1021] In Chunk id: 3, MemBlock id: 81 Order: 4 ,duration: 171 ,size: 2.09722 MiB, name: model.bert.encoders.11-identity-358/out_0 350718 shape: (8,1,512,512) ,dtype: kBool ,alloc_order: 4 ,free_order: 174                                 
 350719 I20220704 06:57:41.285454 2289291 plan_util.cpp:1021] In Chunk id: 3, MemBlock id: 81 Order: 5 ,duration: 170 ,size: 2.09722 MiB, name: model.bert.encoders.10-identity-327/out_0
 350720 shape: (8,1,512,512) ,dtype: kBool ,alloc_order: 5 ,free_order: 174                                  350721 I20220704 06:57:41.285462 2289291 plan_util.cpp:1021] In Chunk id: 3, MemBlock id: 81 Order: 6 ,duration: 169 ,size: 2.09722 MiB, name: model.bert.encoders.6-identity-203/out_0
 350722 shape: (8,1,512,512) ,dtype: kBool ,alloc_order: 6 ,free_order: 174                                 
 350723 I20220704 06:57:41.285470 2289291 plan_util.cpp:1021] In Chunk id: 3, MemBlock id: 81 Order: 7 ,duration: 168 ,size: 6.29152 MiB, name: model.bert.encoders.6-identity-202/out_0
 350724 shape: (8,512,768) ,dtype: kFloat16 ,alloc_order: 7 ,free_order: 174 
```

2022-07-04 07:09 UTC, chengtbf requested changes
需要再调整一下 key，让 每个 Placement 只消费第一个 layer 的 mask。 在 PP=4 下得到验证。

2022-07-04 07:20 UTC, strint commented
> 需要再调整一下 key，让 每个 Placement 只消费第一个 layer 的 mask。 在 PP=4 下得到验证。

还是需要把 key 加上 placement 信息对吧，因为identity 每个 placement 都需要有一个

2022-07-04 07:24 UTC, chengtbf commented
> > 需要再调整一下 key，让 每个 Placement 只消费第一个 layer 的 mask。 在 PP=4 下得到验证。
> 
> 还是需要把 key 加上 placement 信息对吧，因为identity 每个 placement 都需要有一个

应该不是这个问题。应该是每个 layer 消费 同一个 input mask，但是跨了 Placement 以后，经过的是不同的 to global ，生成的是不同的 tensor。 只能用 lbn？

2022-07-04 07:45 UTC, chengtbf commented
> > > 需要再调整一下 key，让 每个 Placement 只消费第一个 layer 的 mask。 在 PP=4 下得到验证。
> > 
> > 
> > 还是需要把 key 加上 placement 信息对吧，因为identity 每个 placement 都需要有一个
> 
> 应该不是这个问题。应该是每个 layer 消费 同一个 input mask，但是跨了 Placement 以后，经过的是不同的 to global ，生成的是不同的 tensor。 只能用 lbn？

还是需要拿到 input tensor 的 lbn + placement 作为 key 才可以。 tensor 作为 value。

2022-07-04 14:15 UTC, chengtbf commented
```
  File "/home/chengcheng/oneflow/python/oneflow/nn/graph/block.py", line 302, in __get_or_create_global
    key = id(input_tensor) + str(placement)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

2022-07-04 14:16 UTC, chengtbf commented on python/oneflow/nn/graph/block.py
> +        key = id(input_tensor) + str(placement)
```
  File "/home/chengcheng/oneflow/python/oneflow/nn/graph/block.py", line 302, in __get_or_create_global
    key = id(input_tensor) + str(placement)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

2022-07-04 14:31 UTC, chengtbf commented on python/oneflow/nn/graph/block.py
> +        key = str(id(input_tensor)) + str(placement)
对比 这种确实有效，从 2602 -> 2489

2022-07-04 14:33 UTC, chengtbf commented on python/oneflow/nn/graph/block.py
> +        key = str(id(input_tensor)) + str(placement)
![image](https://user-images.githubusercontent.com/12186261/177175535-345788f5-71bb-4eaa-aea8-ae4d088f013e.png)

确实中间 stage 的 identity 少了

![image](https://user-images.githubusercontent.com/12186261/177175566-1a826f0b-56d7-4ca6-b976-dbcfe925938c.png)

2022-07-04 14:34 UTC, chengtbf approved these changes

2022-07-04 14:41 UTC, strint commented on python/oneflow/nn/graph/block.py
> +            # store input tensor to avoid tensor id recycle
tensor 缓存了一下，避免了 id recycle

2022-07-04 14:41 UTC, strint commented on python/oneflow/nn/graph/block.py
> +        # key can use only input tensor.
因为 placement 变化了，那么 identity 这里输入的 tenosr 是 to_global 之后的，一定会变化；这样就可以自然的用 to_global 之后的 tensor 做 find or create：
- 输入的 to_global_tensor 没找到，那么就是一个新的placement，需要创建 identity
- 输入的 to_global_tensor 找到了，就复用 identity

2022-07-04 14:43 UTC, strint commented on python/oneflow/nn/graph/graph.py
> +        self._unique_identity_op_dict.clear()
构图完成后，就释放dict

2022-07-04 14:49 UTC, chengtbf commented
用这个分支做一下 bert 1n1g 和 1n4g pp 的正确性验证吧~ @CPFLAME

2022-07-04 17:48 UTC, merged