Add nn functional fold
Oneflow-Inc/oneflow pull request #8667
Opened 2022-07-15 10:30 UTC by zhongshsh

![image](https://user-images.githubusercontent.com/62104945/179205957-0364bef0-0389-483a-8631-a337262c37f5.png)
![image](https://user-images.githubusercontent.com/62104945/179206012-a2e066f6-23f2-4bb6-8eec-0fb91114fa6c.png)

2022-07-15 10:37 UTC, BBuf commented on python/oneflow/framework/docstr/convolution.py
> +add_docstr(
这个文件的命名又一点奇怪，为什么是卷积？

2022-07-15 10:37 UTC, BBuf commented on python/oneflow/framework/docstr/convolution.py
> +    .. warning::
我们没有这个限制吧? @MARD1NO

2022-07-15 10:37 UTC, BBuf commented on python/oneflow/framework/docstr/convolution.py
> +        Currently, only 4-D input tensors (batched image-like tensors) are supported.
同上

2022-07-15 10:39 UTC, MARD1NO commented on python/oneflow/framework/docstr/convolution.py
> +    .. warning::
我们没有，但是pytorch是限制4D输入的，所以接口还是对齐，没暴露出来

2022-07-15 10:40 UTC, BBuf reviewed
可以添加functional接口的测试。

2022-07-15 10:41 UTC, zhongshsh commented on python/oneflow/framework/docstr/convolution.py
> +add_docstr(
functional 这部分文档主要以下图侧边栏进行划分，但是 convolution 这部分比较乱，已经划分了成 conv 和 deconv，所以 fold 这部分我还是命名为 convolution
![image](https://user-images.githubusercontent.com/62104945/179207533-f5869829-ac74-4459-b88c-9ef6d57392cb.png)

2022-07-15 10:41 UTC, zhongshsh commented
> 可以添加functional接口的测试。

收到

2022-07-18 03:18 UTC, BBuf approved these changes
LGTM!

2022-07-18 03:27 UTC, MARD1NO requested changes

2022-07-18 03:27 UTC, MARD1NO commented on oneflow/core/functional/impl/nn_functor.cpp
> +namespace {
删除，组合pair的逻辑放到python层

2022-07-18 03:27 UTC, MARD1NO commented on oneflow/core/functional/functional_api.yaml
> +    Int32List[1] stride=1, String data_format="channels_first") => Unfold'
我觉得不改这里，组合成pair的逻辑，放到python层

2022-07-18 03:27 UTC, MARD1NO commented on oneflow/core/functional/impl/nn_functor.cpp
> +    JUST(attrs.SetAttr<std::vector<int32_t>>("kernel_size", *JUST(CheckPair(kernel_size))));
不改动这里

2022-07-18 03:27 UTC, MARD1NO commented on oneflow/core/functional/impl/nn_functor.cpp
> +    JUST(attrs.SetAttr<std::vector<int32_t>>("kernel_size", *JUST(CheckPair(kernel_size))));
同上

2022-07-18 03:27 UTC, MARD1NO commented on python/oneflow/nn/functional/__init__.py
> +from oneflow._C import unfold
我倾向不直接从._C导出，而是包多一层python，来检查kernel size这些是不是pair，如 https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L4663-L4668。

现有的在functor的处理有点太过trick了，可以问问后江的意见

2022-07-18 03:27 UTC, MARD1NO commented on oneflow/core/functional/impl/nn_functor.cpp
> +Maybe<std::vector<int32_t>> CheckPair(const std::vector<int32_t>& vec) {
即使要加，放在这个文件也是不对的，nn_functor的主要功能是将nn神经网络相关算子注册进functional，他不承担这种工具类的功能。要放也应该放到common.cpp里，而且我觉得他用的地方就 unfold 和 fold，不够common

2022-07-18 03:30 UTC, BBuf commented on python/oneflow/test/modules/test_global_fold.py
> +    m = m.to_global(placement, sbp)
这里是没有必要的，这个Module没有parameter和buffer

2022-07-18 03:33 UTC, zhongshsh commented on oneflow/core/functional/impl/nn_functor.cpp
> +Maybe<std::vector<int32_t>> CheckPair(const std::vector<int32_t>& vec) {
放在 nn_functor 的匿名空间就是考虑到只有 fold 和 unfold 用到了，

2022-07-18 03:34 UTC, zhongshsh commented on oneflow/core/functional/impl/nn_functor.cpp
> +namespace {
我有点迷了，一般不是把处理逻辑放在 C++ 层吗？

2022-07-18 03:35 UTC, zhongshsh commented on python/oneflow/nn/functional/__init__.py
> +from oneflow._C import unfold
好的 @hjchen2

2022-07-18 03:35 UTC, BBuf commented on oneflow/core/functional/impl/nn_functor.cpp
> +Maybe<std::vector<int32_t>> CheckPair(const std::vector<int32_t>& vec) {
这里改个名可以吗，指明是给Fold/Unfold用的？

2022-07-18 03:37 UTC, zhongshsh commented on python/oneflow/test/modules/test_global_fold.py
> +    m = m.to_global(placement, sbp)
收到

2022-07-18 03:40 UTC, hjchen2 commented on oneflow/core/functional/impl/nn_functor.cpp
> +Maybe<std::vector<int32_t>> CheckPair(const std::vector<int32_t>& vec) {
如果是要让这些vec size都是2，直接指定Int32List[2]就行了吧，不需要在这里check一遍

2022-07-18 03:44 UTC, zhongshsh commented on oneflow/core/functional/impl/nn_functor.cpp
> +Maybe<std::vector<int32_t>> CheckPair(const std::vector<int32_t>& vec) {
如果输入值为 1，那么 Int32List[2] = 1 也可以让 vec 是 [1, 1] 吗？

2022-07-18 03:47 UTC, hjchen2 commented on oneflow/core/functional/impl/nn_functor.cpp
> +Maybe<std::vector<int32_t>> CheckPair(const std::vector<int32_t>& vec) {
可以，会自动扩充

2022-07-18 03:56 UTC, zhongshsh commented on oneflow/core/functional/impl/nn_functor.cpp
> +Maybe<std::vector<int32_t>> CheckPair(const std::vector<int32_t>& vec) {
👍

2022-07-18 09:48 UTC, MARD1NO approved these changes

2022-07-20 15:29 UTC, merged