Refactor 1n1d sbp
Oneflow-Inc/oneflow pull request #8755
Opened 2022-07-27 00:48 UTC by REYGU

2022-07-27 01:20 UTC, reygu commented on oneflow/core/job/sbp_parallel.cpp
>    auto& bn2sbp = bigger.bn_in_op2sbp_parallel();
从逻辑看是需要 bigger 必须包含 smaller 中所有的 key, 1n1d 下 System-AutoTick-SinkTick 触发过 bigger 缺失 out

2022-07-27 01:46 UTC, wyg1997 commented on python/oneflow/test/modules/test_global_slice_update.py
>              #            Remove this judgement after refactor sbp infer method in Operator class.
删的话这些注释就也不需要了

2022-07-27 05:38 UTC, reygu commented on python/oneflow/test/modules/test_global_slice_update.py
>              #            Remove this judgement after refactor sbp infer method in Operator class.
已修改

2022-07-27 11:56 UTC, wyg1997 approved these changes

2022-07-27 13:48 UTC, Yipeng1994 commented on oneflow/core/operator/sink_tick_op.cpp
> +      .Build(sbp_sig_list->mutable_sbp_signature()->Add());
sink tick有output吗？

2022-07-27 13:52 UTC, wyg1997 commented on oneflow/core/operator/sink_tick_op.cpp
> +      .Build(sbp_sig_list->mutable_sbp_signature()->Add());
有的，你往这个文件的上面看

2022-07-27 13:55 UTC, Yipeng1994 reviewed
测试一下各模型在1n1d以及多机下跑是否会有bug，多机时有些op在cpu上，比如learning rate
看下是否有其他的地方也有类似的强制单机改为B的操作

2022-07-28 01:27 UTC, reygu commented
> 测试一下各模型在1n1d以及多机下跑是否会有bug，多机时有些op在cpu上，比如learning rate 看下是否有其他的地方也有类似的强制单机改为B的操作

OK

2022-07-28 09:57 UTC, reygu commented on oneflow/core/operator/operator.cpp
> +
这里也是强制 broadcast, 不过 InferSbpSignatureIf 没有被调用过

2022-07-28 09:59 UTC, Yipeng1994 approved these changes
甚好

2022-07-28 11:42 UTC, Yipeng1994 requested changes

2022-07-28 11:42 UTC, Yipeng1994 commented on oneflow/core/operator/operator.cpp
>      std::function<Maybe<const SbpInferHint*>(const std::string&)> SbpInferHint4Ibn,
```suggestion
    const std::function<Maybe<const SbpInferHint*>(const std::string&)>& SbpInferHint4Ibn,
```

2022-07-28 11:42 UTC, Yipeng1994 commented on oneflow/core/operator/operator.cpp
> +                         std::move(SbpInferHint4Ibn), parallel_desc));
```suggestion
  JUST(InferSbpSignature(&signature, sbp_sig_conf, CalcOrderValue4SbpSig,
                         SbpInferHint4Ibn, parallel_desc));
```

2022-07-28 12:53 UTC, Yipeng1994 approved these changes

2022-07-29 01:55 UTC, wyg1997 commented
> python/oneflow/test/modules/test_flatten.py::TestFlattenModule::test_flatten_with_0dim_data

这个错误好像是必现的，可以本地 debug 一下看看和本 PR 有什么关系

2022-07-30 12:42 UTC, wyg1997 commented
File "/home/ci-user/runners/gpu/_work/oneflow/oneflow/python/oneflow/test/expensive/test_layernorm.py", line 214 in test_layernorm_without_affine

在 reduce_like GetSbp 中应该还有类似的问题

2022-07-30 12:56 UTC, reygu commented
> File "/home/ci-user/runners/gpu/_work/oneflow/oneflow/python/oneflow/test/expensive/test_layernorm.py", line 214 in test_layernorm_without_affine
> 
> 在 reduce_like GetSbp 中应该还有类似的问题

这个不是 0Dim/0Size 导致的，好像和智敏那个是同一个问题？https://github.com/Oneflow-Inc/oneflow/pull/8762

2022-08-05 08:22 UTC, merged