[WIP] add nansum
Oneflow-Inc/oneflow pull request #9113
Opened 2022-09-20 04:09 UTC by marigoold

还在开发中，不要 review

2022-09-24 14:08 UTC, BBuf approved these changes

2022-09-24 14:08 UTC, BBuf commented on oneflow/core/ndarray/xpu_ndarray_assign.h
> +    CHECK(y.shape() == x.shape());
这里可以给一个提示或者nolint

2022-09-26 02:19 UTC, marigoold commented on oneflow/core/ndarray/xpu_ndarray_assign.h
> +    CHECK(y.shape() == x.shape());
已改

2022-09-26 02:19 UTC, marigoold commented on oneflow/ir/include/OneFlow/OneFlowUserOps.td
> +def OneFlow_ReduceNanSumOp : OneFlow_BaseOp<"reduce_nansum", [NoSideEffect, DeclareOpInterfaceMethods<UserOpCompatibleInterface>]> {
已改

2022-09-26 02:19 UTC, marigoold commented on oneflow/core/functional/impl/math_functor.cpp
> +    const int32_t naxis = tensor->ndim();
已改

2022-09-26 02:23 UTC, MARD1NO requested changes

2022-09-26 02:23 UTC, MARD1NO commented on oneflow/core/ndarray/binary_func.h
> +    if (std::isnan(__half2float(x))) return std::isnan(__half2float(y)) ? __double2half(0.) : y;
这里half类型就只会有cuda了，不用std库的isnan

2022-09-26 02:23 UTC, MARD1NO commented on oneflow/core/ndarray/binary_func.h
> +    if (std::isnan(x)) return std::isnan(y) ? T{0} : y;
这里要区分下，参考BinaryFuncFloorMod，用宏做条件编译

2022-09-26 02:23 UTC, MARD1NO commented on oneflow/core/ndarray/ndarray_reduce_impl.cu
> +OF_PP_FOR_EACH_ATOMIC(SPECIALIZE_CUB_FUNCTOR_4_BINARY_FUNC, (NanSum));
合并到166行吧

2022-09-26 02:37 UTC, marigoold commented on oneflow/core/ndarray/ndarray_reduce_impl.cu
> +OF_PP_FOR_EACH_ATOMIC(SPECIALIZE_CUB_FUNCTOR_4_BINARY_FUNC, (NanSum));
已改

2022-09-26 02:37 UTC, marigoold commented on oneflow/core/ndarray/binary_func.h
> +    if (std::isnan(x)) return std::isnan(y) ? T{0} : y;
已改

2022-09-26 02:37 UTC, marigoold commented on oneflow/core/ndarray/binary_func.h
> +    if (std::isnan(__half2float(x))) return std::isnan(__half2float(y)) ? __double2half(0.) : y;
已改

2022-09-26 02:55 UTC, MARD1NO approved these changes

2022-09-26 02:55 UTC, MARD1NO commented on oneflow/core/ndarray/ndarray_reduce_impl.h
> +#include "oneflow/core/common/data_type.h"
这三个头文件是不是没必要

2022-09-26 02:55 UTC, MARD1NO commented on python/oneflow/test/modules/test_global_nansum.py
> +class TestGlobalSumModule(flow.unittest.TestCase):
GlobalNanSum，下面的名字也要区别出来

2022-09-26 07:43 UTC, merged