Feat: isclose and allclose
Oneflow-Inc/oneflow pull request #9280
Opened 2022-10-20 13:24 UTC by farmerzhang1

增加两个算子，`isclose`和`allclose`

2022-10-24 01:29 UTC, farmerzhang1 commented on oneflow/core/ndarray/binary_func.h
> +
占位，不需要具体定义

2022-10-24 01:30 UTC, farmerzhang1 commented on python/oneflow/_C/__init__.py
> +    return isclose(input, other, atol, rtol, equal_nan).all().item()
allclose返回Bool类型而非BoolTensor，需要调用.item方法，故在python层拼接

2022-10-24 03:38 UTC, daquexian commented on oneflow/core/functional/impl/binary_functor.cpp
> +      return OpInterpUtil::Dispatch<Tensor>(*neq_nan_op_, {x, y}, attr);
我们的规范是 if else 和 for 即使 body 只有一行也要加大括号

2022-10-24 03:38 UTC, daquexian commented on oneflow/core/ep/common/primitive/binary_functor.h
> +    close |= (std::isfinite(actual_error) and (actual_error <= allowed_error));
😂 这里用 and/or 而不是常用的 &&/|| 有什么理由吗

2022-10-24 03:38 UTC, daquexian commented on python/oneflow/test/modules/test_isclose.py
> +    def test_less(test_case):
这个测试可以去掉，能用 autotest 的就不需要手写测试数据了

2022-10-24 03:38 UTC, daquexian commented on python/oneflow/test/modules/test_isclose.py
> +        shape = random_tensor().oneflow.shape
这个 shape 木有用到

2022-10-24 03:38 UTC, daquexian commented on python/oneflow/test/modules/test_isclose.py
> +        y = torch.isclose(x1, oneof(x2, random().to(int).to(float)))
这样测不是很稳妥，完全随机的两个 tensor 求 isclose 几乎一定会全都是 False，可以考虑这样

```python
rtol = 1e-3
diff = random_tensor(len(shape), *shape, low=-1, high=1, requires_grad=False).to(device) * rtol * 2
x2 = x1 + diff
```
这样有 50% 的概率分别得到 True/False

2022-10-24 03:38 UTC, daquexian commented on python/oneflow/test/modules/test_isclose.py
> +
可以再加一下涉及到 broadcasting 的测试

2022-10-24 03:38 UTC, daquexian commented on oneflow/core/ep/common/primitive/binary_functor.h
> +    if (atol == 0 and rtol == 0) return close;
特殊处理 atol == 0 and rtol == 0 是为了加快速度吗

2022-10-24 03:41 UTC, farmerzhang1 commented on oneflow/core/ep/common/primitive/binary_functor.h
> +    close |= (std::isfinite(actual_error) and (actual_error <= allowed_error));
比较好看（？）

2022-10-24 03:42 UTC, farmerzhang1 commented on oneflow/core/ep/common/primitive/binary_functor.h
> +    if (atol == 0 and rtol == 0) return close;
应该是的，我看pytorch也是这样写的，就照抄了

2022-10-24 03:43 UTC, daquexian commented on oneflow/core/ep/common/primitive/binary_functor.h
> +    close |= (std::isfinite(actual_error) and (actual_error <= allowed_error));
也行（

2022-10-24 08:30 UTC, daquexian commented on python/oneflow/test/modules/test_allclose.py
> +def perturbate(device, shape, x):
是不是可以把 shape 参数去掉直接用 x.oneflow.shape

2022-10-24 08:30 UTC, daquexian commented on python/oneflow/test/modules/test_allclose.py
> +        x2 = random_tensor(len(shape), 2, 1, requires_grad=False).to(device)
可以以 x[0, :, :1] 为基础用 perturbate 生成一个 x2

2022-10-24 12:06 UTC, farmerzhang1 commented on python/oneflow/test/modules/test_allclose.py
> +def perturbate(device, shape, x):
shape和device都从x得到

2022-10-25 07:54 UTC, daquexian approved these changes

2022-10-27 02:31 UTC, BBuf commented on python/oneflow/framework/docstr/comparison.py
> +    Returns a new tensor with boolean elements representing if each element of input is "close" to the corresponding element of other. Closeness is defined as:
文档这里说明一下参考了pytorch，附上链接。可以看一下其它api的例子

2022-10-27 02:36 UTC, BBuf commented on oneflow/core/ndarray/binary_func.h
> +struct BinaryFuncIEN final {
这个有用到吗？而且看起来代码是注释无效的。

2022-10-27 02:36 UTC, BBuf approved these changes

2022-10-27 03:03 UTC, farmerzhang1 commented on oneflow/core/ndarray/binary_func.h
> +struct BinaryFuncIEN final {
有用到的，定义这个struct，后面用来注册op

2022-10-28 08:40 UTC, liujuncheng requested changes

2022-10-28 08:40 UTC, liujuncheng commented on oneflow/core/ep/common/primitive/binary_functor.h
> +#endif  // CUDA_VERSION >= 11000
这部分逻辑放到 oneflow/core/ep/cuda/primitive/binary_functor.cuh

2022-10-28 08:53 UTC, liujuncheng commented on oneflow/core/ep/include/primitive/binary_op.h
> +  kIsCloseEqNan,
可以改成 kIsClose和 kIsCloseEuqalNan，不用Eq

2022-10-28 08:53 UTC, liujuncheng commented on oneflow/core/ep/common/primitive/binary_functor.h
> +    float fp32_src0 = static_cast<float>(src0);
如果这里都是转成 FLOAT 来计算的，是不是可以直接调用float的functor，参考 SPECIALIZATION_PSEUDO_HALF_BINARY_FUNCTOR

2022-10-31 07:04 UTC, liujuncheng approved these changes

2022-11-01 02:47 UTC, merged

2022-11-01 02:49 UTC, farmerzhang1 commented
#close https://github.com/Oneflow-Inc/oneflow/issues/9146

2022-11-01 04:10 UTC, leaves-zwx commented
出现了大量的编译警告：

```
oneflow/oneflow/core/ep/cuda/primitive/broadcast_elementwise_binary.cuh(389): here
            instantiation of "std::unique_ptr<oneflow::ep::primitive::BroadcastElementwiseBinary, std::default_delete<oneflow::ep::primitive::BroadcastElementwiseBinary>> oneflow::ep::primitive::broadcast_elementwise_binary::NewBroadcastElementwiseBinary<binary_op,Src,Dst>(oneflow::Scalar, oneflow::Scalar) [with binary_op=oneflow::ep::primitive::BinaryOp::kIsCloseEqualNan, Src=int64_t, Dst=__nv_bool]"
oneflow/oneflow/core/ep/cuda/primitive/broadcast_elementwise_binary_comparision.cu(30): here

oneflow/oneflow/core/ep/cuda/primitive/binary_functor.cuh(209): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
          detected during:
            instantiation of "Dst oneflow::ep::primitive::broadcast_elementwise_binary::BinaryFunctor<oneflow::kCUDA, oneflow::ep::primitive::BinaryOp::kIsCloseEqualNan, Src, Dst>::operator()(Src, Src) const [with Src=int64_t, Dst=__nv_bool]"
```

calling a constexpr __host__ function from a __host__ __device__ function is not allowed.

2022-11-01 04:12 UTC, leaves-zwx commented on oneflow/core/ep/common/primitive/binary_functor.h
> +    close |= (std::isnan(src0) and std::isnan(src1));
std::isnan 放到 OF_DEVICE_FUNC 可能会有警告吧？OF_DEVICE_FUNC 可能是 `__host__` 也可能是 `__device__`，而 std::isnan 只能是 `__host__` 的吧？

2022-11-01 04:19 UTC, farmerzhang1 commented on oneflow/core/ep/common/primitive/binary_functor.h
> +    close |= (std::isnan(src0) and std::isnan(src1));
cuda有对应的函数吗

2022-11-01 04:20 UTC, leaves-zwx commented on oneflow/core/ep/common/primitive/binary_functor.h
> +    close |= (std::isnan(src0) and std::isnan(src1));
有，就是 isnan 函数，在 oneflow/core/kernel/util/numerics.cuh 里面有定义。

2022-11-01 04:21 UTC, farmerzhang1 commented on oneflow/core/ep/common/primitive/binary_functor.h
> +    close |= (std::isnan(src0) and std::isnan(src1));
好的，我再开个PR修一下