Support bufferizable in okl
Oneflow-Inc/oneflow pull request #9787
Opened 2023-01-28 09:28 UTC by howin98

2023-02-24 09:50 UTC, jackalcooper commented on oneflow/ir/lib/OneFlow/OKL/Kernel/LauncherState.cpp
> +      graph_index_(GetGraphIndex(*module_)){};
`graph_index_` 没用，应该去掉

2023-02-24 10:30 UTC, jackalcooper commented on oneflow/ir/include/OneFlow/OKL/Kernel/RegContext.h
> +class ComputeContext;
这是需要 forward declaration 吗

2023-02-24 10:36 UTC, jackalcooper commented on oneflow/ir/include/OneFlow/OKL/Kernel/TensorManger.h
> +    void* raw_dptr_;
`raw_dptr_` 这个成员是为了？是为了优化吗，应该没必要。这种函数调用应该会被 inline

2023-02-24 10:42 UTC, Yipeng1994 commented on oneflow/core/job/intra_job_mem_sharing_util.h
> +}
这个函数现在有了变化，需要把新的code搞过来

2023-02-24 10:50 UTC, Yipeng1994 commented on oneflow/core/job/intra_job_mem_sharing_util.cpp
> +    MemBlockResultInfo<RegstDescProto*>* result) {
对于 MemReusedAlgorithmAllocateByOrder() 这个函数，因为用了template所以必须在头文件里面就有实现。
在头文件里面有实现以后，原来的匿名空间里面的实现就可以删掉了。

删的时候会有conflict，因为里面的代码有变动。到时候需要把这些变动一并挪到头文件里面。

2023-02-24 10:53 UTC, Yipeng1994 requested changes
合并前需要解决上面2个comments

2023-02-24 12:16 UTC, howin98 commented on oneflow/ir/include/OneFlow/OKL/Kernel/TensorManger.h
> +    void* raw_dptr_;
这里是为了减少获取地址的计算，在创建对象的时候就把ptr计算出来，不用每次获取ptr的时候都需要通过偏移值计算地址

2023-02-24 13:26 UTC, Yipeng1994 commented on oneflow/core/job/intra_job_mem_sharing_util.h
> +    const HashMap<T, size_t>& mem_reused_regst2size, MemBlockResultInfo<T>* result) {
除了原有内存分配的地方，这个函数还在哪里用到了？

我看你单独使用这个函数，用的时候你的compact_insert是设为true还是设为false呢？
如果只是MemFirst这一个函数，建议使用的时候设为false。因为设为false不仅时间复杂度比compact的少一半，而且达到最佳效果的次数比compact的mem first多15%。（测试参见 https://github.com/Oneflow-Inc/OneTeam/issues/1911 ）

2023-02-24 13:29 UTC, Yipeng1994 approved these changes
内存分配的部分没有其他问题了。到时候可以再测试一下效果。（最好打印一下log看下这个pr会不会改变原来Graph的内存分配得出的内存）

2023-02-26 04:36 UTC, howin98 commented on oneflow/core/job/intra_job_mem_sharing_util.h
> +    const HashMap<T, size_t>& mem_reused_regst2size, MemBlockResultInfo<T>* result) {
https://github.com/Oneflow-Inc/oneflow/blob/dadceff26469845127c6c71482b7c53dc854b848/oneflow/ir/lib/OneFlow/OKM/passes.cpp#L327
嗯嗯，只用一次，是设为false的

2023-03-02 09:45 UTC, jackalcooper commented on oneflow/ir/include/OneFlow/OKL/Kernel/RegContext.h
> +#include <memory>
这些是有必要放到头文件吗，头文件只放和接口有关的include就行吧

2023-03-02 10:16 UTC, jackalcooper commented on oneflow/ir/lib/OneFlow/Passes.cpp
> +      if (failed(LowerToOKLOp(rewriter, &op, okl_func, index++))) {
单独写一行 index += 1;

2023-03-03 02:54 UTC, mosout commented on oneflow/ir/include/OneFlow/OKL/Kernel/ComputeContext.h
> +  user_op::Tensor* CreateTensor4ArgNameAndIndex(const std::string& arg_name, int32_t index);
```suggestion
  user_op::Tensor* CreateTensorWithArgNameAndIndex(const std::string& arg_name, int32_t index);
```

2023-03-03 02:54 UTC, mosout commented on oneflow/ir/include/OneFlow/OKL/Kernel/ComputeContext.h
> +  TmpBufferManager& GetTmpBufferManager() { return tmp_buffer_; }
这个是不是没有用到

2023-03-03 02:54 UTC, mosout commented on oneflow/ir/include/OneFlow/OKL/Kernel/TensorManger.h
> +  explicit TmpBufferManager(user_op::Tensor* tensor) : tensor_(tensor) {}
这个应该是TensorManager？

2023-03-03 02:54 UTC, mosout commented on oneflow/ir/include/OneFlow/OKL/OKLOps.td
> +def PoolToTensorOp : OKL_Op<"pool_to_tensor"> {
这个pool代指什么

2023-03-03 03:04 UTC, mosout commented
TensorManager和TmpBufferManager这两个类型包括其内置类的的写法我感觉有点混乱，我建议把内置类都独立出来，然后把声明都写到同一个头文件里面（或者把这两个类放一个头文件，内置类们放一个头文件，没必要把每个类都放一个头文件）

这几个类型也是有交叉的，有些操作不需要写两遍，建议抽出基类使用继承或者使用Mixin。

实现统一放到cpp里，尽量别在头文件里搞。

2023-03-03 04:11 UTC, howin98 commented on oneflow/ir/include/OneFlow/OKL/Kernel/ComputeContext.h
> +  TmpBufferManager& GetTmpBufferManager() { return tmp_buffer_; }
嗯，删掉了

2023-03-03 04:11 UTC, howin98 commented on oneflow/ir/include/OneFlow/OKL/OKLOps.td
> +def PoolToTensorOp : OKL_Op<"pool_to_tensor"> {
pool指kernel launch op的tmp buffer作为一个缓冲池给子op复用

2023-03-03 04:18 UTC, howin98 commented on oneflow/ir/include/OneFlow/OKL/Kernel/TensorManger.h
> +  explicit TmpBufferManager(user_op::Tensor* tensor) : tensor_(tensor) {}
这个忘记删了，其实就是tmpbuffermanager，后面没用到

2023-03-03 04:20 UTC, howin98 commented
> TensorManager和TmpBufferManager这两个类型包括其内置类的的写法我感觉有点混乱，我建议把内置类都独立出来，然后把声明都写到同一个头文件里面（或者把这两个类放一个头文件，内置类们放一个头文件，没必要把每个类都放一个头文件）
> 
> 这几个类型也是有交叉的，有些操作不需要写两遍，建议抽出基类使用继承或者使用Mixin。
> 
> 实现统一放到cpp里，尽量别在头文件里搞。
嗯嗯。其实只有tmp buffer manager，tensor manager是之前tmp buffer manager的改名，但是防止改名对定义产生误解，所以又改回去了，但当时应该是忘记删除tensormanger的头文件了。tmp buffer manger的内置类主要只服务于tmp buffer manager的内部，不对外暴露。

2023-03-03 11:49 UTC, mosout approved these changes

2023-03-06 01:40 UTC, merged