Plan sep compile
Oneflow-Inc/oneflow pull request #9920
Opened 2023-03-01 13:48 UTC by strint

2023-03-01 14:03 UTC, strint commented on python/oneflow/test/graph/test_alexnet_auto_parallel.py
> +    def _test_alexnet_auto_parallel_1d_sbp(test_case):
这个做 4 卡测试，master 和本分支都会卡住

2023-03-01 14:11 UTC, strint commented on python/oneflow/test/graph/test_alexnet_auto_parallel.py
> +    def _test_alexnet_auto_parallel_1d_sbp(test_case):
其它分布式测试使用 logical chian ( https://github.com/Oneflow-Inc/OneTeam/issues/1791#issuecomment-1423738537 ) + nccl  logical（ https://github.com/Oneflow-Inc/OneTeam/issues/1791#issuecomment-1432919122 ） + 非拉直算法（ https://github.com/Oneflow-Inc/OneTeam/issues/1791#issuecomment-1445059667 ）都可以跑通。

2023-03-01 14:15 UTC, strint commented on oneflow/core/register/register_desc.proto
> +  optional ShapeProto time_shape = 3;
分离编译的情况下，部分 time_shape 是还没生成的。

protobuf 3 也删除了 required 关键字，因为它导致升级和维护困难，不推荐使用了。

2023-03-09 01:41 UTC, strint commented on CMakeLists.txt
> +  add_definitions(-DOF_DEBUG_LAZY_RUNTIME)
增加一个编译选项，打开后可以增加 actor 的执行日志，帮助定位死锁问题

2023-03-09 01:43 UTC, strint commented on oneflow/core/common/async_deallocate_context.cpp
> +  thread_pool_->AddWork(Handle);
支持在一个独立线程里释放大对象

2023-03-09 01:43 UTC, strint commented on oneflow/core/common/balanced_splitter.cpp
> +int64_t BalancedSplitter::GetRangIndex(int64_t value) const {
获取一个 index 所在的段的编号

2023-03-09 01:45 UTC, strint commented on oneflow/core/common/deallocate_context.h
> +    Dispatch([data] { const_cast<std::shared_ptr<T>*>(&data)->reset(); });
支持自定义释放一个指针的Dispatch方式，比如在一个独立线程里面释放，注意T也需要是个智能指针。

2023-03-09 01:48 UTC, strint commented on oneflow/core/common/env_var/lazy.h
> +DEFINE_THREAD_LOCAL_ENV_INTEGER(ONEFLOW_LAZY_COMPILE_RPC_THREAD_NUM, 16);
默认编译模式和默认编译时的线程数量

2023-03-09 01:54 UTC, strint commented on oneflow/core/common/id_pairs.proto
> +  repeated Int64Pair int64_pair = 1;
用于存储有可达关系的 task id 对

2023-03-09 01:55 UTC, strint commented on oneflow/core/framework/instructions_builder.cpp
> -
过时代码

2023-03-09 01:58 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +void MergeIntoFirst(std::vector<HashSet<T>>* data) {
把 std::vector<HashSet<T>> 合并到 vector.at(0) 位置的 HashSet<T>

2023-03-09 01:59 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +Maybe<void> NNGraph::MasterRankCompile() {
这个可以不用关注，是中间状态，用于调试的

2023-03-09 02:03 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +                                                              Y* worker_data) {
master -> wokers 广播数据

2023-03-09 02:03 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +                                                         const DoEachT& DoEach) {
workers -> master 汇总数据

2023-03-09 02:04 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +                                                         const PrepareEachT& PrepareEach) {
master -> workers 对每个 worker 发送不同的数据

2023-03-09 02:04 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +Maybe<void> NNGraph::MasterAndWorkerRanksCompile() {
主要逻辑：多进程分离编译

2023-03-09 02:05 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +      world_size, name_ + std::string(__FUNCTION__) + "_job", job_, &job_));
master 广播 job

2023-03-09 02:54 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +    boxing_task_graph = JUST(BoxingTaskGraph::New(ParallelLoop));
master 构建 boxing task graph

2023-03-09 02:55 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +      PrepareWorkerBoxingTaskGraphProto));
序列化 boxing task graph 后，分发到 workers

2023-03-09 02:57 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +    });
master 做 CollectiveBoxingPlan 的编译

2023-03-09 02:57 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +      plan_.collective_boxing_plan(), plan_.mutable_collective_boxing_plan()));
广播 CollectiveBoxingPlan 到 wokers

2023-03-09 02:58 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +Maybe<void> NNGraph::NaiveCompile() {
原来的 master 做 plan compile 的逻辑，没有变化

2023-03-09 02:58 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +Maybe<void> NNGraph::CompilePlanForRuntime() {
plan 编译函数

2023-03-09 02:59 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +    static CompileMethodT VisitRankPerProcess() { return &NNGraph::MasterAndWorkerRanksCompile; }
4种编译模式，实际使用第一种 master 编译（默认）和第四种 rank 分离编译。

2023-03-09 03:00 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +Maybe<void> NNGraph::InitRuntime() {
只是拆分了函数，逻辑没有变化

2023-03-09 03:01 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> -Maybe<void> NNGraph::CompilePlanForRuntime() {
该函数被替换成了上面的 CompilePlanForRuntime

2023-03-09 03:09 UTC, strint commented on oneflow/core/graph/boxing_identity_task_node.cpp
> +Maybe<void> BoxingIdentityTaskNode::InitTransportTaskFromProto(
TaskNode 部分增加了序列化、反序列化的操作

2023-03-09 04:27 UTC, strint commented on oneflow/core/graph/compute_task_node.cpp
> +void CompTaskNode::ConsumeFakeRegstsIf() {
在 rank 0 上编译 BoxingTaskGraph 时，由于 TransportTaskNode 编译必须要获得自己的真实的 input，所以要构造其输入 BlobDesc，这样需要消费其上游的 ComputeTaskNode。而非 rank 0 的 compute task node （与 Transport 相连的那部分）并不需要真正的生成（因为只有它的下游 TransportTaskNode 用到了，其他的没用了），因此非 rank 0 的 compute task node只生成自己的 output regst 提供 regst id、task id、shape 给下游即可，而这些自己的 output 是通过自己的 global shape  + ndsbp 推导得到的，所以无需 input blob desc。

2023-03-09 04:27 UTC, strint commented on oneflow/core/graph/compute_task_node.h
> +    static ExecNode::InferBlobDescsMethod VisitNaive() { return &ExecNode::InferBlobDescsByInputs; }
Base 编译方式，跟进输入 BlobDesc 推理输出 BlobDesc，和 master 相同。

2023-03-09 04:27 UTC, strint commented on oneflow/core/graph/exec_graph.cpp
> +    const Operator& op, const PbRpf<std::string>& bns,
InferPhysicalBlobDesc 使用 SBP 推理

2023-03-09 04:27 UTC, strint commented on oneflow/core/graph/exec_graph.cpp
> +      nd_sbp_signature, parallel_ctx, GetBlobDesc4BnInOp));
用 sbp 推理 input blob desc

2023-03-09 04:27 UTC, strint commented on oneflow/core/graph/exec_graph.cpp
> +                 std::stringstream() << " infer blob descs if failed, op name " << op_->op_loc());
用 input 推理 output

2023-03-09 04:27 UTC, strint commented on oneflow/core/graph/exec_graph.cpp
> +      nd_sbp_signature, parallel_ctx, GetBlobDesc4BnInOp));
用 sbp 检查 output。

TODO： 这里可以优化，直接用 SBP 推理出 output，节省2/3开销。

2023-03-09 06:31 UTC, strint commented on oneflow/core/lazy/actor/actor.cpp
> +#ifdef OF_DEBUG_LAZY_RUNTIME
debug actor 执行

2023-03-09 08:17 UTC, strint commented on oneflow/core/graph/task_type.h
> +struct TaskTypeVisitor {
所有 TaskType 相关的 Visitor 基类

2023-03-09 08:22 UTC, strint commented on oneflow/core/graph/task_type.h
> +struct TransportTaskTypeVisitor {
TransportTask 特有的 Visitor

2023-03-09 08:24 UTC, strint commented on oneflow/core/graph/create_transport_task.h
> +struct CreateTransportTask final : public TransportTaskTypeVisitor<CreateTransportTask> {
用于从 BoxingTaskGraph 的 Proto 创建出 Task 对象

2023-03-09 08:40 UTC, strint commented on oneflow/core/graph/plan_task_graph.cpp
> +RankPlanTaskGraph::RankPlanTaskGraph(
分 rank 的 PlanTaskGraph 初始化

2023-03-09 08:41 UTC, strint commented on oneflow/core/graph/plan_task_graph.cpp
> +  InitCtrlEdges(reachable_cb_pairs);
给有可达关系但是在本 rank 内确定不了的 task 间连上控制边

2023-03-09 08:50 UTC, strint commented on oneflow/core/graph/plan_task_graph.h
> +class NaivePlanTaskGraph final : public PlanTaskGraph {
全图的 task graph

2023-03-09 09:02 UTC, strint commented on oneflow/core/graph/task_graph.cpp
> +void TaskGraph::InitOrderedTaskNodes() {
来自PR：https://github.com/Oneflow-Inc/oneflow/pull/9909

2023-03-09 09:13 UTC, strint commented on oneflow/core/graph/task_graph.cpp
> +Maybe<void> BoxingTaskGraph::Init(
- BoxingTaskGraph 只包含 boxing 子图中的 TransportTaskNode + 其上下游的直连 ComputeTaskNode（用于基于ComputeTaskNode 的 SBP 来做 BlobDesc 推理 ）
- Master 需要保存全部的 boxing 子图； 其他 rank 只保存 boxing 子图中本 rank 中的分量

2023-03-09 09:19 UTC, strint commented on oneflow/core/graph/task_graph.cpp
> +Maybe<void> RankTaskGraph::Init(const HashSet<std::string>& var_op_names) {
RankTaskGraph 的构建

2023-03-10 02:15 UTC, jackalcooper commented on oneflow/core/common/deallocate_context.h
> +    Dispatch([data] { const_cast<std::shared_ptr<T>*>(&data)->reset(); });
这些注释直接写代码里面吧？

2023-03-10 02:41 UTC, strint commented on oneflow/core/common/deallocate_context.h
> +    Dispatch([data] { const_cast<std::shared_ptr<T>*>(&data)->reset(); });
可以

2023-03-10 06:21 UTC, Yipeng1994 commented on oneflow/core/common/id_pairs.proto
> +  repeated Int64Pair int64_pair = 1;
为什么不用类似于IsReachable的数据结构呢？
如果全部都储存了是不是太大了？比如1500个op的图（swin）就会有约50w个可达关系了。
如果是7万个op的图呢？

2023-03-10 06:23 UTC, chengtbf commented on oneflow/core/common/id_pairs.proto
> +  repeated Int64Pair int64_pair = 1;
这个可达关系，哪里用到了呢？

2023-03-10 06:34 UTC, Yipeng1994 commented on oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.cpp
> +  // so the ids here are unique amonge all ranks.
```suggestion
  // The boxing task graph is built on rank 0 and broadcasted to all the ranks,
  // so the ids here are unique among all the ranks.
```

2023-03-10 07:30 UTC, Yipeng1994 commented on oneflow/core/graph/compute_task_node.cpp
> +void CompTaskNode::ConsumeFakeRegstsIf() {
review的时候看到了很多的评论，这些评论可以写到注释里面吗？后人看的时候能理解里面的意思。增强代码的可读性

2023-03-10 07:32 UTC, strint commented on oneflow/core/graph/compute_task_node.cpp
> +void CompTaskNode::ConsumeFakeRegstsIf() {
可以

2023-03-10 07:56 UTC, Yipeng1994 commented on oneflow/core/graph/exec_graph.cpp
> +      nd_sbp_signature, parallel_ctx, GetBlobDesc4BnInOp));
这里有点好奇如何优化，可以mark一下，写到注释里，大概介绍如何优化

2023-03-10 08:16 UTC, strint commented on oneflow/core/graph/exec_graph.cpp
> +      nd_sbp_signature, parallel_ctx, GetBlobDesc4BnInOp));
因为这里是
- 1、使用 input global shape + sbp 推理出输入 BlobDesc
- 2、使用 infer physical blob desc，根据输入推出输出的 BlobDesc
- 3、用 output global shape + sbp 推理的 shape 来 check 步骤2中推理出的输出 BlobDesc

这样看，实际只用做第三步就好了

2023-03-14 02:47 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +          Singleton<CtrlClient>::Get()->PushKV(key, data);
MultiThreadBroadcastFromMasterToWorkers 这里把 master data 发送了 split_num 次。然后每个 woker get 对应 range 的数据。

但都还是从 master 拿到的数据，所以怀疑 MultiThreadBroadcastFromMasterToWorkers 这里是不是不能加速？CtrlClient 下面的 grpc 有做负载均衡（可以不都从 master 来拉取数据么）

需要去阅读下 CtrlClient 的 PushKV 和 PullKV，搞清楚这部分的执行机制。

2023-03-15 11:12 UTC, Yipeng1994 reviewed
很多注释都没加进去，代码可读性太弱了

2023-03-15 11:21 UTC, Yipeng1994 commented on python/oneflow/test/graph/test_comb1to2d.py
> +
这些是临时的code吧？是不是最后要移除

2023-03-15 11:22 UTC, Yipeng1994 commented on python/oneflow/test/graph/test_comb1to2d.py
> +                        test_cnt += 1
临时代码？

2023-03-15 11:23 UTC, Yipeng1994 commented on python/oneflow/nn/graph/graph_config.py
> +            )
临时代码？

2023-03-15 12:10 UTC, Yipeng1994 commented on oneflow/core/job/plan_util.h
> +  // liimited_rank.
```suggestion
  // limited_rank equals -1 means taking care of all ranks.
  // Otherwise, only take care of rank limited_rank.
```

2023-03-15 12:14 UTC, Yipeng1994 commented on oneflow/core/job/plan_util.cpp
> +  NaivePlanTaskGraph plan_task_graph(plan);
这里要从plan生成全图的task graph会不会很费时间？
有没有其他地方已经生成好的全图 task graph可以复用？

2023-03-15 12:21 UTC, Yipeng1994 commented on oneflow/core/job/plan_util.h
> +      HashSet<std::pair<int64_t /*src task_id*/, int64_t /*dst task_id*/>>* reachable_task_pairs);
这个函数在哪里调用了？好像没看到

2023-03-15 12:25 UTC, Yipeng1994 commented on oneflow/core/job/plan_util.cpp
> +        set->insert(nearests.begin(), nearests.end());
非常多的copy，而且类型还是set，这段代码要是在大模型跑起来肯定会巨慢。参考之前mem resue的互斥关系。
不过好像没有地方调用这个函数。

2023-03-15 12:31 UTC, Yipeng1994 commented on oneflow/core/job/plan_util.cpp
> +    return a->task_id() < b->task_id();
问一下task id() 在分离编译场景以及原来的场景是唯一的嘛？
有没有可能有某些场景下有2个task他们的id是一样的？

然后他们的序列是一致的嘛？
比如在 0卡上 a 是 100， b是101
在1卡会不会 a 是 101， b是100

2023-03-15 12:48 UTC, Yipeng1994 commented on oneflow/core/job/plan_util.cpp
> +        // Skip when do rank compile and this logical chain group is not related with this rank.
```suggestion
        // Skip when doing rank compile and this logical chain group is not related to this rank.
```

2023-03-15 12:50 UTC, Yipeng1994 commented on oneflow/core/job/parallel_desc.h
> +  Maybe<bool> TryGetParallelId(int64_t rank, int64_t* parallel_id) const;
这个函数在哪里调用了？好像也没用调用到。

2023-03-15 13:02 UTC, Yipeng1994 commented on oneflow/core/job/parallel_desc.h
> +  Maybe<bool> TryGetParallelId(int64_t rank, int64_t* parallel_id) const;
找到了 task_graph.cpp里面

2023-03-15 15:20 UTC, strint commented on oneflow/core/graph/fake_consumed_regst_provider.h
> +  virtual ~FakeConsumedRegstProvider() = default;
是这样。提供一个 compute task node，然后该 compute task node 的输入 regst 是 fake 的，它的输出 regst 可以用 SBP + Placement 推理得到。该 Fake compute task node 可以帮助 task 子图做 blob desc 推理，主要是使得 transport task node 有正确的输入 blob desc。

 好的，之后把注释 push 上来。

2023-03-15 17:03 UTC, strint commented on oneflow/core/common/id_pairs.proto
> +  repeated Int64Pair int64_pair = 1;
> 这个可达关系，哪里用到了呢？

子图的 collective boxing task 可达关系，用于生成 CollectiveBoxingPlan
```cpp
    // CollectiveBoxingPlan needs to know the reachable relation of collective boxing nodes.
    PlanUtil::GenCollectiveBoxingPlan(&deallocate_ctx, &job_, &plan_, [&] {
      return std::make_unique<RankPlanTaskGraph>(plan_, *reachable_cb_pairs);
    });
```

2023-03-15 17:07 UTC, strint commented on oneflow/core/common/id_pairs.proto
> +  repeated Int64Pair int64_pair = 1;
> 为什么不用类似于IsReachable的数据结构呢？

在生成时，用的是 `HashSet<std::pair<int64_t /*src task_id*/, int64_t /*dst task_id*/>>* reachable_task_pairs)`

传输时，为了数据结构简单采用的这个 IdPairs 结构。

> 如果全部都储存了是不是太大了？比如1500个op的图（swin）就会有约50w个可达关系了。

因为只存的是 rank 子图中有可达关系的 CollectiveBoxing task pairs，所以数量级应该低很多。

2023-03-15 17:08 UTC, strint commented on oneflow/core/common/id_pairs.proto
> +  repeated Int64Pair int64_pair = 1;
已经修改了函数名和实现，之前看起来像是生成了所有 task node 的可达关系。

2023-03-15 17:58 UTC, strint commented on python/oneflow/test/graph/test_comb1to2d.py
> +
这个是以个分开的测试，用于debug 一个小分组变化的问题。可以注释掉。

2023-03-15 18:00 UTC, strint commented on python/oneflow/test/graph/test_comb1to2d.py
> +
已经注释掉

2023-03-15 18:01 UTC, strint commented on python/oneflow/test/graph/test_comb1to2d.py
> +                        test_cnt += 1
这个也是拆分的小 case 的测试。已经注释掉。

2023-03-15 18:02 UTC, strint commented on python/oneflow/nn/graph/graph_config.py
> +            )
这个不是，是为了可以用环境变量控制拉直算法，方便 CI 测试等调试场景。

2023-03-15 18:05 UTC, strint commented on oneflow/core/job/plan_util.h
> +      HashSet<std::pair<int64_t /*src task_id*/, int64_t /*dst task_id*/>>* reachable_task_pairs);
生成 CollectiveBoxingPlan 那里

2023-03-15 18:06 UTC, strint commented on oneflow/core/job/plan_util.cpp
> +        set->insert(nearests.begin(), nearests.end());
生成 CollectiveBoxingPlan 那里，已经更新了一下，只有 生成 CollectiveBoxing node，按说数量会少很多。

2023-03-15 18:06 UTC, strint commented on oneflow/core/job/plan_util.cpp
> +  NaivePlanTaskGraph plan_task_graph(plan);
这里不是全图的，已经更新，可以在看下

2023-03-16 02:54 UTC, strint commented on oneflow/core/common/id_pairs.proto
> +  repeated Int64Pair int64_pair = 1;
@Yipeng1994 @chengtbf

2023-03-16 03:11 UTC, Yipeng1994 commented on python/oneflow/nn/graph/graph_config.py
> +            )
拉直算法有专门的接口 
```
enable_straighten_algorithm()
```
使用多个接口会让用户感到困惑。
如果CI需要，可以在CI的那几个Script 用环境变量来控制拉直的选定，而不是在内部另开后门。

2023-03-16 03:12 UTC, Yipeng1994 submitted a review, later dismissed
拉直的内部接口需要去掉

2023-03-16 03:14 UTC, Yipeng1994 commented on python/oneflow/nn/graph/graph_config.py
> +            )
或者是改一下拉直的接口，直接统一用环境变量，但是输入不能是整形，而是便于用户阅读的形式，就是MemoryFirst一类的字符串

2023-03-16 03:26 UTC, strint commented on python/oneflow/nn/graph/graph_config.py
> +            )
拉直的接口我改成 string 吧，然后环境变量和 python 都保留（兼容）。

环境变量的优先级低于python 的。

2023-03-16 04:13 UTC, leaves-zwx commented on oneflow/core/common/async_deallocate_context.cpp
> +  thread_pool_->AddWork(Handle);
需要实现一个新的类吗？直接调用全局 thread pool 是不是也是一样的效果？

2023-03-16 04:26 UTC, leaves-zwx commented on oneflow/core/common/id_pairs.h
> +void InitIdPairs(const std::unordered_set<std::pair<int64_t, int64_t>>& pairs, IdPairs* proto) {
头文件里面的函数定义要加 inline，否则在 link 时有冲突。

2023-03-16 08:04 UTC, leaves-zwx commented on oneflow/core/framework/nn_graph.cpp
> +Maybe<void> NNGraph::NaiveCompile() {
这个函数跟原来的 CompilePlanForRuntime 实现没有任何变化对吗？

2023-03-16 08:07 UTC, leaves-zwx commented on oneflow/core/framework/nn_graph.h
> +#include <cstddef>
可以注意下对头文件的 include，特别是 header include other headers 的情况，有时会产生意想不到的问题。去掉一下非必要的 include。

2023-03-16 08:41 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +//   d. Master CollectiveBoxingPlan and then broadcast to all the workers.
补充了一批注释，后面还会在加一批

2023-03-16 08:41 UTC, strint commented on oneflow/core/graph/exec_graph.cpp
> +  // Infer input blob desc with SBP, the infer results are set intuo the temp input blob desc.
这里改造只有 user op 成立，改动比较多，所以列了个 TODO

2023-03-16 08:41 UTC, strint commented on oneflow/core/graph/fake_consumed_regst_provider.h
> +  virtual ~FakeConsumedRegstProvider() = default;
已经增加了注释

2023-03-16 08:41 UTC, strint commented on oneflow/core/graph/plan_task_graph.cpp
>  }
这里同之前讨论的一样，只给 collective boxing task 加了 控制边。

2023-03-16 08:41 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +    // TODO(strint): Optimize the reachable_cb_pairs if it cost a lot.
这里和 @Yipeng1994 讨论后，列了一个 TODO 项

2023-03-16 08:41 UTC, strint commented on oneflow/core/graph/task_graph.h
> +class GlobalTaskGraph final : public TaskGraph {
从 NaiveTaskGraph 改为了 GlobalTaskGraph，以体现全局

2023-03-16 08:41 UTC, strint commented on oneflow/core/graph/task_node.cpp
> +  }
> 这里的debug code最后是不是也需要移除？

已经移除

2023-03-16 08:41 UTC, strint commented on oneflow/core/job/id_manager.h
> +  std::atomic<int64_t> chunk_id_count_;
后来合并了一个分支，做了分 rank 的 task id 生成，也加上了锁，现在应该没有这个问题了

```
inline TaskId TaskIdGenerator::Generate(const StreamId& stream_id) {
  std::unique_lock<std::mutex> lock(mutex_);
  task_index_t task_index = stream_id2task_index_counter_[stream_id]++;
  return TaskId{stream_id, task_index};
}
```

2023-03-16 08:41 UTC, strint commented on oneflow/core/job/plan_util.cpp
> +    return a->task_id() < b->task_id();
task id 做成了分 rank 的，所以是唯一的。
```
inline TaskId TaskIdGenerator::Generate(const StreamId& stream_id) {
  std::unique_lock<std::mutex> lock(mutex_);
  task_index_t task_index = stream_id2task_index_counter_[stream_id]++;
  return TaskId{stream_id, task_index};
}
```
这里的 compare 无所谓，是用于日志打印的。实际排序用的是  logical chain 中的 order。

2023-03-16 08:41 UTC, strint commented on oneflow/core/lazy/actor/light_actor.cpp
> +                << " current act is at the " << act_cnt_ << "th execution.";
已经 refine 了 actor 的 debug 日志

2023-03-16 08:52 UTC, Yipeng1994 commented on oneflow/core/job/plan_util.cpp
> +    return a->task_id() < b->task_id();
嗯嗯，酱紫

2023-03-16 09:35 UTC, strint commented on python/oneflow/nn/graph/graph_config.py
> +        if "ONEFLOW_SEP_COMPILE_STRAIGHTEN_ALG" in os.environ:
已经改成了 ONEFLOW_SEP_COMPILE_STRAIGHTEN_ALG，且注明是 debug 用的，不打算提供给用户。

2023-03-16 10:58 UTC, chengtbf commented on oneflow/core/lazy/actor/light_actor.cpp
> +                << " current act is at the " << act_cnt_ << "th execution.";
我想开发一个更全的 actor log，且不是编译选项控制的，不然想看还得重新编译。

2023-03-16 11:59 UTC, strint commented on oneflow/core/lazy/actor/light_actor.cpp
> +                << " current act is at the " << act_cnt_ << "th execution.";
可以的，这个也可以合并，主要是考虑执行效率问题。

你那边可以独立写一个，因为这里如果有冲突也是很好处理的，后面在你 pr 里面把这个删了。

2023-03-16 12:29 UTC, strint commented on oneflow/core/graph/task_stream_index_manager.h
> +  virtual stream_index_t GetTaskStreamIndex(TaskType task_type, const DeviceId& device_id);
TaskStreamIndexManager 部分会有函数触发创建 cuda context 么

@leaves-zwx

2023-03-20 08:08 UTC, strint commented on oneflow/core/job/rank_compiler.cpp
> +  CudaCurrentDeviceGuard guard(GetCudaDeviceIndex());
修复分离编译时非 rank 0 进程在 cuda 0 创建 cuda context 造成的显存、进程问题

2023-03-20 10:17 UTC, strint commented on oneflow/core/common/util.cpp
> -COMMAND(std::signal(SIGINT, AbortSignalHandler));
一个对残留进程的修复，参见 https://github.com/Oneflow-Inc/OneTeam/issues/1954

2023-03-22 04:44 UTC, strint commented on oneflow/core/job/env_global_objects_scope.cpp
> +  OF_ENV_BARRIER();
这里调换了一下 OF_ENV_BARRIER 的位置，先检查是否正常退出，不正常是直接退出。否则可能会卡在 OF_ENV_BARRIER。

关联：https://github.com/Oneflow-Inc/OneTeam/issues/1954

2023-03-23 11:58 UTC, strint commented on oneflow/core/job/plan_util.cpp
> +    if (limited_rank >= 0 && task->machine_id() != limited_rank) { continue; }
GradAcc 产生的 repeat op 会做 inplace 消费。这里出现非本 rank 的task，会导致输出 regst 去找输入 regst 时找不到，因而GradAcc报错。

2023-03-24 09:15 UTC, chengtbf commented on oneflow/core/job/plan_util.cpp
> +    if (limited_rank >= 0 && task->machine_id() != limited_rank) { continue; }
这里为什么会出现 非本 rank 的 task 呢？

2023-03-24 09:24 UTC, strint commented on oneflow/core/job/plan_util.cpp
> +    if (limited_rank >= 0 && task->machine_id() != limited_rank) { continue; }
> 这里为什么会出现 非本 rank 的 task 呢？

boxing task graph 关联的多个 rank 的 compute task node，在 rank 0 上全保留了

2023-03-29 09:55 UTC, strint commented on oneflow/core/common/id_pairs.h
> +void InitIdPairs(const std::unordered_set<std::pair<int64_t, int64_t>>& pairs, IdPairs* proto) {
fixed

2023-03-29 09:55 UTC, strint commented on oneflow/core/common/id_pairs.h
> +void InitIdPairs(const std::unordered_set<std::pair<int64_t, int64_t>>& pairs, IdPairs* proto) {
> 头文件里面的函数定义（非 template）要加 inline，否则在 link 时有冲突。

fixed

2023-03-30 01:25 UTC, strint commented on python/oneflow/test/graph/test_alexnet_auto_parallel.py
> +                break
这里从进500轮迭代减少到20轮，验证可执行即可，节约下 CI 时间

2023-03-30 09:14 UTC, strint commented on python/oneflow/test/graph/test_graph_pipeline.py
> +            self.pp_m.stage_3_m.to(GraphModule).activation_checkpointing = True
activation_checkpointing 的多卡测试执行

2023-04-06 07:59 UTC, chengtbf commented on python/oneflow/test/graph/test_alexnet_auto_parallel.py
> +    def _test_alexnet_auto_parallel_1d_sbp(test_case):
这个问题解决了吧

2023-04-06 08:22 UTC, chengtbf commented on oneflow/core/common/id_pairs.proto
> +  repeated Int64Pair int64_pair = 1;
> 子图的 collective boxing task 可达关系，用于生成 CollectiveBoxingPlan

介于当前分离编译下，没有打开 CollectiveBoxing， 我觉得这里可以不用提供类似的接口。 即 分离编译仅在 nccl use compute stream 下生效
在分离编译场景下想要获取任意两个 task node 的可达关系是不合理的。

2023-04-06 08:31 UTC, chengtbf commented on oneflow/core/graph/plan_task_graph.cpp
> +  InitCtrlEdges(reachable_cb_pairs);
为什么这里需要连控制边呢？

2023-04-06 08:34 UTC, strint commented on oneflow/core/graph/task_graph.cpp
> +void TaskGraph::InitOrderedTaskNodes() {
可以的，你拆吧，我来 merge 到这里

2023-04-06 14:53 UTC, strint commented on oneflow/core/graph/plan_task_graph.cpp
> +  InitCtrlEdges(reachable_cb_pairs);
因为 boxing task graph 里面的 collective boxing task node，划分到 rank plan 里面，也变成部分了，这可能导致失去了可达关系。

通过这个 ctrl 可以保持他们在原始 graph 中的顺序关系。

2023-04-06 15:04 UTC, strint commented on oneflow/core/common/id_pairs.proto
> +  repeated Int64Pair int64_pair = 1;
nccl use compute stream 可以避免 CollectiveBoxing plan 的生成是吧？

2023-04-11 06:30 UTC, chengtbf commented on oneflow/core/common/env_var/lazy.h
> +DEFINE_THREAD_LOCAL_ENV_STRING(ONEFLOW_LAZY_COMPILE_MODE, "naive");
这里应该把合法的 "mode" str 罗列出来

2023-04-11 08:03 UTC, strint commented
已经把合并且把 dev_cc_order_in_chain 作为上游

2023-04-11 08:10 UTC, strint commented on oneflow/core/common/async_deallocate_context.cpp
> +  thread_pool_->AddWork(Handle);
这里是为了临时启用一个线程，做异步的大对象释放，主线程可以省掉大对象析构的时间。

这个线程在做对象释放时，主线程可能在驱动 Global thread pool 去做通信。所以不适合复用。

2023-04-11 08:21 UTC, chengtbf commented on oneflow/core/common/async_deallocate_context.cpp
> +  thread_pool_->AddWork(Handle);
> 主线程可能在驱动 Global thread pool 去做通信

什么情况下 Global thread pool 会去做通信呢

2023-04-11 08:22 UTC, chengtbf commented on oneflow/core/common/id_pairs.proto
> +  repeated Int64Pair int64_pair = 1;
是的

2023-04-11 08:25 UTC, strint commented on oneflow/core/common/async_deallocate_context.cpp
> +  thread_pool_->AddWork(Handle);
> > 主线程可能在驱动 Global thread pool 去做通信
> 
> 什么情况下 Global thread pool 会去做通信呢

// Separation plan compilation is done by:
//   a. Master broadcast job(or logical graph) to all workers, make all rank use the same job.
//   b. Mater compile BoxingTaskGraph and broadcast it to all workers. BoxingTaskGraph needs to be
//      done on master rank.
//   c. Each rank compile it's related task node with RankCompiler. RankCompiler compile with the
//      BoxingTaskGraph and the job.
//   d. Master CollectiveBoxingPlan and then broadcast to all the workers.

比如 a d 里面的同步数据的操作，调用了 MultiThreadLoop

2023-04-11 08:31 UTC, strint commented on oneflow/core/common/env_var/lazy.h
> +DEFINE_THREAD_LOCAL_ENV_STRING(ONEFLOW_LAZY_COMPILE_MODE, "naive");
> 这里应该把合法的 "mode" str 罗列出来

done

2023-04-11 08:47 UTC, chengtbf commented on oneflow/core/common/id_pairs.h
> +void InitIdPairs(const std::unordered_set<std::pair<int64_t, int64_t>>& pairs, IdPairs* proto);
这个分支要做一次重构，或者把这部分代码拆到后一个 PR 去（但是不会合并）。

分离编译的开关打开以后，走多进程分离编译的分支，此时，强制开启： logical chain + nccl use compute stream，在这个情况下，不会需要 collective boxing plan 及其相关逻辑。 因此，分离编译下，对于 collective boxing 引入的额外处理（这里的 id pairs）是不必要的。

2023-04-11 08:49 UTC, chengtbf commented on oneflow/core/common/async_deallocate_context.cpp
> +  thread_pool_->AddWork(Handle);
> // b. Mater compile BoxingTaskGraph and broadcast it to all workers. BoxingTaskGraph needs to be
> // done on master rank.

b 里面不会触发数据同步 和 MultiThreadLoop 吗？

2023-04-11 10:43 UTC, chengtbf requested changes
看了一下午，整个 PR 还是太大太难以 review 了。  实际上可以拆分成非常多个小 PR。

这里我仅仅看了前十几个文件，还有一百个文件没看。

分析了以下，主要是因为分离编译整个功能横跨了半年的时间，还有工作交接的问题，包含了非常多的细节，把 feature、前置依赖、重构、bug fix、后置性能优化 都杂糅到一起了。

从前十几个文件来看，至少可以拆成以下多个 PR：

1.  移除 Collective Boxing 部分的全部改动； 移除 id pairs ， rank plan task graph 等
2. 前置 PR 1： TaskNode / TaskEdge  From/To Proto 序列化
3. 前置 PR 2： TaskNode/ExecNode::GetInferBlobDescsMethod 
4. 前置 PR 3： Master <-> Workers push/pull kv multi-thread
5. 主逻辑 PR ： nn.Graph Compile by master/ranks
6. 后置 PR 1： 性能优化： 使用异步 thread pool 析构大对象
...

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/framework/nn_graph.cpp
> +    // TODO(strint): Optimize the reachable_cb_pairs if it cost a lot.
这个 TODO 可以去掉了，直接移除这部分逻辑

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/framework/nn_graph.cpp
> +  // d. Master CollectiveBoxingPlan and then broadcast to all the workers.
移除 644 : 677

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/framework/nn_graph.cpp
> +        [i](TaskNode* task_node) { return BoxingTaskGraph::SelectTaskNodeByRank(task_node, i); },
这里 master 上是不是也应该做一次 select，保证 master 最终参与 rank compiler 的 boxing proto 只有本 rank ，而不是全部的 rank。

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/framework/nn_graph.cpp
> +    PlanUtil::ToDotFile(*plan, "job_" + name_ + "_plan" + std::to_string(rank) + ".dot");
rank 之前应该加一个 _

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/framework/nn_graph.cpp
> +  auto compile_tc = std::make_unique<CostCounter<std::chrono::seconds>>(true, true);
这个函数最多只是改个名字吧，怎么全部都是 diff 了

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/framework/nn_graph.cpp
> +      // Multi thread run seperation compile. Just for debug.
这里最终合并的版本是一个 if else （分离编译 true / false）即可

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/framework/nn_graph.cpp
> +      TeePersistentLogStream::Create(plan_name)->Write(plan_);
为什么在这里又写一遍呢？

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/framework/nn_graph.cpp
> +Maybe<void> NNGraph::InitRuntime() {
理论上 init runtime 不需要任何改动，这里没有 diff

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/framework/nn_graph.h
> +  Maybe<void> MasterRankCompile();
移除

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/framework/symbol_storage_util.cpp
> -    new symbol::Storage<OperatorConfSymbol>()));
这个是过时代码吗

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/functional/impl/common.cpp
> +      // needs to be greater than 0, and dim_b should be equal to 1.
无关改动其实可以另提 pr

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/graph/boxing_identity_task_node.cpp
> +Maybe<void> BoxingIdentityTaskNode::InitTransportTaskFromProto(
感觉这个可以作为前置 PR，针对所有 task node 的 序列化接口

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/common/deallocate_context.h
> +  void Deallocate(std::shared_ptr<T>&& ptr) {
单独的多线程释放，可以单独一个 PR（后置优化 PR）

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/framework/nn_graph.cpp
> +  deallocate_ctx.Deallocate(std::move(boxing_task_graph_proto));
这个异步析构可以作为优化的后续 PR 提供。

这里有一个隐患，析构 和 push/pull kv 数据同步之间没有任何的 barrier 做顺序保证，可能存在问题。 但一旦出现问题，就很难 debug。

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/graph/task_node.cpp
> +Maybe<void> TaskEdge::InitFromProto(const TaskEdgeProto& proto,
同样，提供一个前置 PR

2023-04-11 10:43 UTC, chengtbf commented on oneflow/core/graph/task_node.h
> +  virtual ExecNode::InferBlobDescsMethod GetInferBlobDescsMethod() const = 0;
这是一个独立的新特性，作为前置 PR

2023-04-12 09:40 UTC, chengtbf commented on python/oneflow/test/graph/test_comb1to2d.py
> +    def _test_lazy_boxing_2d_all_combination_diff_placement_middle(test_case):
这个是如何做到不被 CI 执行的呢？

2023-04-12 09:43 UTC, strint commented on python/oneflow/test/graph/test_comb1to2d.py
> +    def _test_lazy_boxing_2d_all_combination_diff_placement_middle(test_case):
只要加上一个前缀 "_" 就会被忽略

2023-04-12 09:58 UTC, chengtbf commented on python/oneflow/test/graph/test_comb1to2d.py
>          graph_diff_placement = _TestGraph(model_diff_placement)
这里还是有问题。 把 placement 拆分到下面来，但是是 true，那就少测了 collective boxing 在 nccl compute false 时的 placement 表现（这个是原本测试用例希望的），虽然这个 case 之前在分离编译下过不了。

2023-04-12 09:59 UTC, strint commented on python/oneflow/test/graph/test_comb1to2d.py
>          graph_diff_placement = _TestGraph(model_diff_placement)
嗯，那这里看起来要构造两个case，一个打开，一个不打开？

2023-04-13 03:34 UTC, strint commented on oneflow/core/graph/task_graph.cpp
> +    JUST(task_graph_rebuild_ctx_->AddTaskEdge(edge, task_edge_proto.task_edge_uid()));
重建 boxing task graph 中的 edge

2023-04-13 03:58 UTC, chengtbf commented on oneflow/core/graph/task_graph.cpp
> +  JUST(AddTransportTaskEdgesFromProto());
这个 edge 的原始代码是新奇兄写的还是后来加的？

2023-04-13 06:34 UTC, strint commented on oneflow/core/graph/task_graph.cpp
> +  JUST(AddTransportTaskEdgesFromProto());
> 这个 edge 的原始代码是新奇兄写的还是后来加的？

是之前加的

2023-04-13 07:22 UTC, strint commented on oneflow/core/common/async_deallocate_context.cpp
> +  thread_pool_->AddWork(Handle);
> b 里面不会触发数据同步 和 MultiThreadLoop 吗？

也会

2023-04-13 08:49 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +Maybe<void> NNGraph::MasterRankCompile() {
> 在 master 上做伪分离编译，仅用于调试。这些逻辑不应该合并到 master。

可以后面功能稳定了再删掉怎么样，要不调试会比较麻烦。

现在需要这么大规模编译的真实用户估计不超过 5 个。所以合并后，我们可以保持一个月的试用期( Beta 发布），之后再改成正式 API。

2023-04-13 08:52 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +  }
> 这里不需要做同步嘛，session barrier

MultiThreadLoop 里面有个 bc.WaitForeverUntilCntEqualZero(); 来保证所有子任务都执行完成了。

2023-04-13 09:06 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +    boxing_task_graph->ToProto([](TaskNode*) { return true; }, boxing_task_graph_proto.get());
> 有没有统计过最复杂情形下（比如 1000 卡）， boxing task graph proto 的大小

参见这里，T5 1000 卡 DP，boxing task graph proto 也会分 rank 发送，拆分后，一个大概是 22 M。

2023-04-13 11:08 UTC, Yipeng1994 approved these changes
测试正常的话我觉得没问题了

2023-04-14 09:03 UTC, chengtbf commented on oneflow/core/framework/nn_graph.cpp
> +  Singleton<OpGraph>::Get()->UpdateCachedPredicatorIsReachable();
这个我清楚。 我说的是这里 OpGraph 没有根据同步好的 job 重新 new 吧？ 还是说： OpGraphSingletonGuard  里重新 new 了 `Singleton<OpGraph>` ？

2023-04-14 09:05 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +  Singleton<OpGraph>::Get()->UpdateCachedPredicatorIsReachable();
> 这个我清楚。 我说的是这里 OpGraph 没有根据同步好的 job 重新 new 吧？ 还是说： OpGraphSingletonGuard 里重新 new 了 `Singleton<OpGraph>` ？

是的，通过这个 Guard 去做了 new 和 delete

2023-04-14 09:18 UTC, chengtbf commented on oneflow/core/graph/compute_task_node.h
> +  virtual void ConsumeFakeRegsts() = 0;
FakeRegst 一整套逻辑可以作为前置 PR

2023-06-04 09:24 UTC, strint commented
> 至少可以拆成以下多个 PR：
> 
> 1. 移除 Collective Boxing 部分的全部改动； 移除 id pairs ， rank plan task graph 等
>    ...

done

2023-06-04 10:51 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +          Singleton<CtrlClient>::Get()->PullKV(key, &data);
> 这里为啥需要重复发送 split_num 次 master data？

https://github.com/Oneflow-Inc/OneTeam/issues/1952#issuecomment-1498440375

这个 issue 里面做了验证，在 rank 很多时，这个方法可以避免 master 的带宽限制，达到一种树状的通信拓扑。

具体的 std::string key = prefix + std::to_string(i);  这里构造了 split_num 个 kv，v 相同，key 不同。key 不同在 grpc 下就会被 hash 到不同的机器作为 server 提供数据，这样就会有 split_num 个 rank 作为 server。使得 master rank 带宽不会成为瓶颈。

2023-06-04 10:54 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +          Singleton<CtrlClient>::Get()->PullKV(key, &data);
> 这里可能会有加速，因为每个 rank 收集来的数据是不同的。 具体这里会 pull 什么 data 呢？

之前是 pull 那个可达关系的 idpair 的，已经删掉了

2023-06-04 10:55 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +void MergeByMod(size_t index, size_t n, std::vector<HashSet<T>>* data) {
MergeByMod 已经删掉了

2023-06-04 11:16 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +  deallocate_ctx.Deallocate(std::move(boxing_task_graph));
> 这里仅有 master 上会真正析构吧， master 上析构 boxing_task_graph 和 分发： boxing_task_graph_proto 是同时执行的吗？

Deallocate 在析构时才会触发析构，应该是每个 rank 都会执行。 不过Deallocate 已经移动到了后面的 pr ，这里不需要考虑这个问题了。

2023-06-04 11:18 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +    PlanUtil::ToDotFile(*plan, "job_" + name_ + "_plan" + std::to_string(rank) + ".dot");
> rank 之前应该加一个 _

done

2023-06-04 11:25 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +  auto compile_tc = std::make_unique<CostCounter<std::chrono::seconds>>(true, true);
原来的 CompilePlanForRuntime 很长，改成了下面的小函数，其中编译 plan 被完全拆出来命名为 NaiveCompile。可能是结构变化大，没识别出来：

```
Maybe<void> NNGraph::CompilePlanForRuntime() {
  // A global variable to get graph configurations.
  auto current_graph_config = std::make_unique<GlobalJobDescScope>(job_.job_conf(), job_id());
  auto compile_tc = std::make_unique<CostCounter<std::chrono::seconds>>(true, true);
  typedef Maybe<void> (NNGraph::*CompileMethodT)();
  struct GetCompileMethod final : public CompileModeVisitor<GetCompileMethod> {
    static CompileMethodT VisitNaive() {
      // Master rank compile the full plan.
      return &NNGraph::NaiveCompile;
    }
    static CompileMethodT VisitRankPerProcess() {
      // Multi process(rank) run seperation compile.
      return &NNGraph::MasterAndWorkerRanksCompile;
    }
    static CompileMethodT VisitInValid() { return nullptr; }
  };
  JUST((this->*GetCompileMethod::Visit(JUST(CurrentCompileMode())))());
  compile_tc->Count("[GraphCompile]" + name_ + " CompileAndSyncPlan", 0);
  PlanUtil::PopulateOpAttribute(&plan_, plan_.job_id2op_attribute_ref_table());
  compile_tc->Count("[GraphCompile]" + name_ + " PopulateOpAttribute", 0);
  return Maybe<void>::Ok();
}
```

2023-06-04 11:29 UTC, strint commented on oneflow/core/framework/nn_graph.cpp
> +      TeePersistentLogStream::Create(plan_name)->Write(plan_);
> 为什么在这里又写一遍呢？

已经改了，只会写一遍

2023-06-04 11:29 UTC, strint commented on oneflow/core/framework/nn_graph.h
> +  Maybe<void> MasterRankCompile();
> 移除

done

2023-06-04 11:29 UTC, strint commented on oneflow/core/common/deallocate_context.h
> +  void Deallocate(std::shared_ptr<T>&& ptr) {
> 单独的多线程释放，可以单独一个 PR（后置优化 PR）

done

2023-06-04 11:30 UTC, strint commented on oneflow/core/graph/compute_task_node.h
> +  virtual void ConsumeFakeRegsts() = 0;
> FakeRegst 一整套逻辑可以作为前置 PR

done

2023-06-20 06:02 UTC, chengtbf approved these changes

2023-06-20 06:20 UTC, merged